# -*- coding: utf-8 -*-
"""Derin bolumu ek: alt kategori tamamlayici tarama (57 kesit) - vitra.com.tr kategori sayfalari, pazaryeri ve fiyat karsilastirma aramalari, rakip magaza aramalari, ayni model kodunda fiyat (D30)."""
from ortak import *
import json, os, re
D2 = os.path.join(veri.V, "ham", "derin", "pazaryeri_derin2")
def L2(f): return [json.loads(l) for l in open(os.path.join(D2, f), encoding="utf-8")]
K2 = L2("kesitler.jsonl"); VS = L2("vitra_site_kategori.jsonl")
FE = json.load(open(os.path.join(D2, "fiyat_eslesme.json"), encoding="utf-8"))
ANA = {"Klozet": "WC", "Lavabo": "Washbasin", "Armatür": "Taps", "Duşlar": "Showers", "Rezervuar": "Cisterns", "Yıkanma alanları": "Bathing", "Banyo mobilyası": "Bathroom furniture", "Banyo aksesuarı": "Accessories", "Vitrifiye tamamlayıcı": "Sanitaryware accessories"}
AD2 = {"yerden-tek-klozet": ("Yerden tek klozet (ayaklı)", "Floor-standing one-piece WC"), "asma-klozet-takimi": ("Asma klozet takımı", "Wall-hung WC set"), "tuvalet-tasi-alaturka": ("Tuvalet taşı (alaturka)", "Squat toilet"), "cocuk-klozet": ("Çocuk klozet", "Children's WC"), "engelli-klozet": ("Engelli klozet", "Accessible WC"),
       "canak-lavabo": ("Çanak lavabo", "Bowl washbasins"), "monoblok-lavabo": ("Monoblok lavabo", "Monoblock basin"), "yarim-tezgah-lavabo": ("Yarım tezgah lavabo", "Semi-recessed basin"), "etajerli-lavabo": ("Etajerli lavabo", "Basin with shelf"), "ayakli-lavabo": ("Ayaklı (standart) lavabo", "Pedestal basin"), "kose-lavabo": ("Köşe lavabo", "Corner basin"), "lavabo-ayagi": ("Lavabo ayağı", "Basin pedestal"),
       "bide-bataryasi": ("Bide bataryası", "Bidet tap"), "kuvet-bataryasi": ("Küvet bataryası", "Bath filler tap"), "termostatik-batarya": ("Termostatik batarya", "Thermostatic tap"), "fotoselli-lavabo-bataryasi": ("Temassız (fotoselli) lavabo bataryası", "Touchless basin tap"), "siva-ustu-banyo-bataryasi": ("Duvardan (sıva üstü) banyo bataryası", "Exposed bath tap"),
       "yuksek-canak-lavabo-bataryasi": ("Çanak lavabo bataryası (yüksek)", "Tall bowl-basin tap"), "ankastre-stop-valf": ("Ankastre stop valf", "Concealed stop valve"), "lavabo-sifonu-susuzgeci": ("Lavabo sifon ve süzgeci", "Basin trap and waste"), "armatur-cikis-ucu-dirsek": ("Armatür tamamlayıcı (çıkış ucu, dirsek)", "Tap accessories (outlet, elbow)"),
       "dus-kolonu": ("Duş kolonu", "Shower column"), "el-dusu-takimi": ("El duşu takımı", "Hand shower set"), "surgulu-el-dusu-takimi": ("Sürgülü el duşu takımı", "Sliding-rail hand shower set"), "masajli-dus-sistemi": ("Masajlı duş sistemi", "Massage shower system"), "bataryali-dus-sistemi": ("Bataryalı duş sistemi", "Shower system with mixer"), "ankastre-dus-yonlendirici": ("Ankastre duş yönlendirici", "Concealed diverter"),
       "kumanda-paneli-mekanik": ("Kumanda paneli (mekanik)", "Flush plate (mechanical)"), "kumanda-paneli-temassiz": ("Kumanda paneli (temassız)", "Flush plate (touchless)"), "kumanda-paneli-akilli": ("Kumanda paneli (akıllı)", "Flush plate (smart)"), "tasiyici-aparat": ("Taşıyıcı aparat", "WC frame"), "duvar-onu-rezervuar": ("Duvar önü rezervuar", "Exposed cistern"), "tuvalet-tasi-rezervuari": ("Tuvalet taşı rezervuarı", "Squat toilet cistern"),
       "dus-kanali": ("Duş kanalı", "Shower channel"), "dus-unitesi": ("Duş ünitesi (kompakt kabin)", "Shower unit (compact cabin)"), "hidromasajli-kuvet": ("Hidromasajlı küvet", "Whirlpool bath"), "bagimsiz-kuvet": ("Bağımsız küvet", "Freestanding bath"), "kuvet-paneli": ("Küvet paneli", "Bath panel"), "dus-teknesi-paneli": ("Duş teknesi paneli", "Shower tray panel"), "kaydirmaz": ("Kaydırmaz", "Anti-slip mat"),
       "banyo-tezgahi": ("Banyo tezgahı", "Bathroom countertop"), "banyo-konsolu": ("Banyo konsolu", "Bathroom console"), "banyo-set-modulu": ("Banyo set modülü", "Furniture set module"), "malzemelik": ("Malzemelik", "Storage unit"), "dolap-kulpu": ("Dolap kulpu", "Cabinet handle"), "dolap-ayagi": ("Dolap ayağı", "Cabinet leg"), "makyaj-aynasi": ("Makyaj aynası", "Make-up mirror"), "aynali-dolap": ("Aynalı dolap", "Mirror cabinet"),
       "sabunluk": ("Sabunluk", "Soap dish"), "dis-fircaligi": ("Diş fırçalığı", "Toothbrush holder"), "tuvalet-kagitligi": ("Tuvalet kağıtlığı", "Toilet roll holder"), "tuvalet-fircasi": ("Tuvalet fırçası", "Toilet brush"), "banyo-askisi": ("Banyo askısı", "Robe hook"), "banyo-cop-kovasi": ("Banyo çöp kovası", "Bathroom bin"), "havluluk": ("Havluluk", "Towel rail"),
       "pisuvar-ara-bolmesi": ("Pisuvar ara bölmesi", "Urinal divider"), "pisuvar-yikama-sistemi": ("Pisuvar yıkama sistemi", "Urinal flush system")}
KAN = {"trendyol": "Trendyol", "hepsiburada": "Hepsiburada", "akakce": "Akakçe", "cimri": "Cimri"}
def _m(o):
    f = (o or {}).get("fiyat") or {}; m = f.get("medyan")
    return bin(round(m)) if m else "-"
def pz(o, cap=False):
    """toplam · medyan (Trendyol, Hepsiburada)."""
    if not o or not o.get("okunan"): return n("-")
    t = o.get("total"); ts = "10.000+" if (cap and t == 10000) else (bin(t) if t else "-")
    return n("%s · %s" % (ts, _m(o)))
def fk(o):
    """medyan · satıcı sayısı medyanı (Akakçe, Cimri)."""
    if not o or not o.get("okunan"): return n("-")
    sm = o.get("satici_medyan"); sm = ("%g" % sm).replace(".", ",") if sm is not None else "-"
    return n("%s · %s" % (_m(o), sm))
def va(q, c):
    o = q.get(c)
    return "-" if not o or not o.get("okunan") else str(o.get("vitra_adet") or 0)
def marka1(q):
    for c in ("ty", "hb"):
        o = q.get(c) or {}
        top = sorted([m for m in (o.get("marka_top5") or []) if m.get("yorum")], key=lambda m: -m["yorum"])
        if top: return veri_m("%s · %s" % (top[0]["marka"], yzd(top[0]["yorum_payi"])))
    return n("-")
def site(q):
    v = q.get("vitra_site") or {}
    if not v.get("urun"): return n("-")
    return n("%d / %d · %s - %s" % (v["urun"], v.get("stokta_yok") or 0, bin(v["fiyat_min"]), bin(v["fiyat_max"])))
rows5 = []
for q in K2:
    a, b = AD2[q["kesit"]]
    rows5.append([x("%s > %s" % (q["ana_kategori"], a), "%s > %s" % (ANA[q["ana_kategori"]], b)), site(q), pz(q.get("ty")), pz(q.get("hb"), True), fk(q.get("akakce")), fk(q.get("cimri")),
                  n(" / ".join(va(q, c) for c in ("ty", "hb", "akakce", "cimri"))), marka1(q)])
T5 = tablo([th("Ana > alt kategori", "Main > sub-category", "Sezonsallık dosyasındaki VitrA ana kategorisi ve vitra.com.tr alt kategori adı; arama ifadesi pazaryerinde kullanılan karşılıktır.", "VitrA main category from the seasonality file and the vitra.com.tr sub-category name; the search phrase is the marketplace equivalent."),
            th("vitra.com.tr: ürün / stokta yok · fiyat aralığı (TL)", "vitra.com.tr: products / out of stock · price range (TL)", "Kategori sayfasındaki renk ve varyant kartı sayısı / \"Gelince Haber Ver\" işaretli kart sayısı · liste fiyatı aralığı; 30.09.2026.", "Colour and variant cards on the category page / cards marked \"notify when available\" · list price range; 30.09.2026.", True),
            th("Trendyol: toplam · medyan", "Trendyol: total · median", "Arama sonucu toplamı · çok satan sıralı ilk 36 üründe kesitle eşleşen ürünlerin medyan fiyatı (TL).", "Search result total · median price (TL) of the products matching the segment among the first 36 best sellers.", True),
            th("Hepsiburada: toplam · medyan", "Hepsiburada: total · median", "Arama sonucu toplamı (10.000 üst sınır) · çok satan sıralı ilk 36 üründe eşleşen ürünlerin medyan fiyatı (TL).", "Search result total (capped at 10,000) · median price (TL) of matching products among the first 36 best sellers.", True),
            th("Akakçe: medyan · satıcı", "Akakçe: median · sellers", "Eşleşen ürünlerin en düşük fiyat medyanı (TL) · ürün başına satıcı sayısı medyanı.", "Median of the lowest prices of matching products (TL) · median number of sellers per product.", True),
            th("Cimri: medyan · satıcı", "Cimri: median · sellers", "Eşleşen ürünlerin en düşük fiyat medyanı (TL) · ürün başına satıcı sayısı medyanı; 429 yanıtı nedeniyle okunmayan kesitler \"-\".", "Median of the lowest prices of matching products (TL) · median sellers per product; segments not read because of 429 responses show \"-\".", True),
            th("VitrA / Artema adet (TY / HB / Ak / Ci)", "VitrA / Artema count (TY / HB / Ak / Ci)", "Eşleşen ürünler içinde VitrA ya da Artema markalı ürün sayısı; sırasıyla Trendyol, Hepsiburada, Akakçe, Cimri.", "Number of VitrA or Artema products among matching products; Trendyol, Hepsiburada, Akakçe, Cimri in that order.", True),
            th("En çok değerlendirilen marka", "Most-reviewed brand", "Trendyol (yoksa Hepsiburada) eşleşen ürünlerinde değerlendirme sayısı en yüksek marka ve kesitteki değerlendirme payı.", "Brand with the most reviews among matching Trendyol (else Hepsiburada) products and its share of the segment's reviews.")], rows5, "uzun")
# vitra.com.tr kategori sayfalari
rows6 = []
for r in VS:
    if "kesit" not in r or r.get("urun") is None: continue
    a, b = AD2[r["kesit"]]
    st = r.get("stoklu") or 0
    rows6.append([x(a, b), u("https://www.vitra.com.tr" + r["yol"], r["yol"]), cell(r["urun"]), n("%s - %s" % (bin(r["fiyat_min"]), bin(r["fiyat_max"])) if r.get("fiyat_min") else "-"),
                  n('<span class="dn">0</span>') if not st else cell(st), cell(r.get("stokta_yok") or 0), n("%d / %d" % (r.get("ilk_sayfa_sepet_indirimli") or 0, r.get("ilk_sayfa_n") or 0)), cell(r.get("ucretsiz_montaj_liste") or 0)])
T6 = tablo([th("Alt kategori", "Sub-category", "vitra.com.tr kategori sayfası.", "vitra.com.tr category page."), th("Sayfa yolu", "Page path", "Kategori sayfasının yolu; yeni sekmede açılır.", "Path of the category page; opens in a new tab."),
            th("Ürün (varyant)", "Products (variants)", "Sayfadaki \"N sonuç listeleniyor\" değeri; renk ve varyant kartları ayrı sayılır.", "The \"N results\" value on the page; colour and variant cards are counted separately.", True),
            th("Fiyat aralığı (TL)", "Price range (TL)", "Liste fiyatı; fiyata göre artan ve azalan sıralamanın ilk kartları.", "List price; first cards of ascending and descending price order.", True),
            th("Stoklu", "In stock", "\"Sadece stoklu ürünleri göster\" süzgeciyle listelenen kart sayısı; 0 olan sayfalarda ilk sayfadaki tüm kartlar \"Gelince Haber Ver\" işaretlidir.", "Cards listed with the \"show only in-stock products\" filter; on pages with 0 every card on the first page is marked \"notify when available\".", True),
            th("Stokta yok", "Out of stock", "Sayfa toplamı ile stoklu kart sayısı arasındaki fark.", "Difference between the page total and the in-stock count.", True),
            th("İlk sayfada \"Sepette indirim\"", "\"Basket discount\" on first page", "İlk sayfadaki kartların kaçında \"Sepette %N indirim\" etiketi bulunduğu / ilk sayfadaki kart sayısı.", "How many first-page cards carry a \"N% off in basket\" label / number of first-page cards.", True),
            th("Ücretsiz montaj (liste)", "Free installation (list)", "/c-ucretsiz-montaj listesinde bu kategoriden yer alan ürün sayısı.", "Products from this category in the /c-ucretsiz-montaj list.", True)], rows6, "uzun")
# rakip magazalar
MAG2 = [("koctas", "Koçtaş"), ("bauhaus", "Bauhaus"), ("banyomarka", "Banyomarka"), ("banyomega", "Banyomega"), ("banyoline", "Banyoline"), ("creavit", "Creavit (e-mağaza)")]
def mg(o):
    if not o or not o.get("eslesen"): return n("-")
    return n("%d · %s · %s" % (o["eslesen"], _m(o), str(o.get("vitra_adet")) if o.get("vitra_adet") is not None else "-"))
rows7 = [[x(AD2[q["kesit"]][0], AD2[q["kesit"]][1])] + [mg((q.get("magazalar") or {}).get(c)) for c, _ in MAG2] for q in K2]
T7 = tablo([th("Alt kategori", "Sub-category", "Kesit.", "Segment.")] + [th(m, m, "Mağaza aramasında kesitle eşleşen ürün sayısı · eşleşen ürünlerin medyan fiyatı (TL) · VitrA ve Artema ürün sayısı; Koçtaş çok satan sıralı, diğerleri arama sırası; Bauhaus ve Creavit'te VitrA sayısı okunmamıştır (\"-\").", "Products matching the segment in the store search · median price (TL) of matching products · VitrA and Artema products; Koçtaş in best-seller order, others in search order; VitrA count not read at Bauhaus and Creavit (\"-\").", True) for _, m in MAG2], rows7, "uzun")
# ayni model kodunda fiyat
def fyz2(v):
    if v is None: return n("-")
    return n(("%+.1f" % v).replace(".", ",").replace("+", "+%").replace("-", "-%") if v else "%0")
rows8 = []
for c in ("trendyol", "hepsiburada", "akakce", "cimri"):
    o = FE["kanal"][c]
    rows8.append([veri_m(KAN[c]), cell(o["n"]), cell(o["kod"]), fyz2(o["medyan_liste"]), fyz2(o["medyan_sepet"]), n(yzd(o["altinda"], 0)), n(yzd(o["ustunde_sepet"], 0))])
T8 = tablo([th("Kanal", "Channel", "Pazaryeri ya da fiyat karşılaştırma sitesi; Akakçe ve Cimri'de ürünün en düşük teklifi alınmıştır.", "Marketplace or price comparison site; on Akakçe and Cimri the product's lowest offer is used."),
            th("Eşleşme", "Matches", "Ürün adında vitra.com.tr model kodu birebir geçen VitrA ve Artema satırı.", "VitrA and Artema rows whose product name contains a vitra.com.tr model code verbatim.", True),
            th("Model kodu sayısı", "Model codes", "Benzersiz model kodu sayısı.", "Number of unique model codes.", True),
            th("Liste fiyatına göre medyan fark", "Median gap to list price", "Pazaryeri fiyatı ile vitra.com.tr liste fiyatı arasındaki yüzde farkın medyanı; negatif değer pazaryerinin daha düşük olduğunu gösterir.", "Median percentage gap between the marketplace price and the vitra.com.tr list price; a negative value means the marketplace is lower.", True),
            th("Sepet fiyatına göre medyan fark", "Median gap to basket price", "Aynı fark, vitra.com.tr \"Sepette %N indirim\" uygulanmış fiyata göre.", "The same gap measured against the vitra.com.tr price after the \"N% off in basket\" label is applied.", True),
            th("Liste fiyatının altında pay", "Share below list price", "Eşleşmelerin yüzde kaçında pazaryeri fiyatı liste fiyatının altındadır.", "Percentage of matches where the marketplace price is below the list price.", True),
            th("Sepet fiyatının üstünde pay", "Share above basket price", "Eşleşmelerin yüzde kaçında pazaryeri fiyatı sepet fiyatının üstündedir.", "Percentage of matches where the marketplace price is above the basket price.", True)], rows8, "dar")
def _ad(s): return re.sub(r"\s+", " ", s or "").strip()
def _sat(s): return "-" if not s or s.startswith("no:") else s
rows9 = []
for e in FE["en_yuksek"][:6] + FE["en_dusuk"][:4]:
    rows9.append([veri_m(_ad(e["site_ad"])), veri_m(e["kod"]), veri_m("%s · %s" % (KAN[e["kanal"]], _sat(e["satici"]))), n("%s / %s" % (bin(e["liste"]), bin(e["sepet"]))), cell(round(e["pazar"])), fyz2(round((e["pazar"] / e["liste"] - 1) * 100, 1))])
T9 = tablo([th("Ürün (vitra.com.tr adı)", "Product (vitra.com.tr name)", "vitra.com.tr kategori kartındaki ürün adı.", "Product name on the vitra.com.tr category card."), th("Model kodu", "Model code", "vitra.com.tr kartındaki model kodu; pazaryeri ürün adında birebir geçmektedir.", "Model code on the vitra.com.tr card; appears verbatim in the marketplace product name."),
            th("Kanal · satıcı", "Channel · seller", "Pazaryeri ve ilan satıcısı; Akakçe'de en düşük teklif, satıcı adı okunmamıştır.", "Marketplace and listing seller; on Akakçe the lowest offer, seller name not read."),
            th("vitra.com.tr liste / sepet (TL)", "vitra.com.tr list / basket (TL)", "Liste fiyatı / \"Sepette %N indirim\" uygulanmış fiyat.", "List price / price after the \"N% off in basket\" label.", True),
            th("Pazaryeri fiyatı (TL)", "Marketplace price (TL)", "İlanın 30.09.2026 tarihli fiyatı.", "Listing price on 30.09.2026.", True), th("Liste fiyatına göre fark", "Gap to list price", "Pazaryeri fiyatının liste fiyatına göre yüzde farkı.", "Percentage gap of the marketplace price to the list price.", True)], rows9, "dar")
# KPI degerleri
vk = [r for r in VS if "kesit" in r and r.get("urun") is not None]
top_kart = sum(r["urun"] for r in vk); top_yok = sum(r.get("stokta_yok") or 0 for r in vk)
sifir = sorted({r["kesit"] for r in vk if all(not (q.get("stoklu") or 0) for q in vk if q["kesit"] == r["kesit"])})
sepet_n = sum(r.get("ilk_sayfa_sepet_indirimli") or 0 for r in vk); sepet_t = sum(r.get("ilk_sayfa_n") or 0 for r in vk)
vitrasiz = [q["kesit"] for q in K2 if not any((q.get(c) or {}).get("vitra_adet") for c in ("ty", "hb", "akakce", "cimri"))]
G = FE["genel"]; KA = FE["kanal"]
def fz(v): return ("%+.1f" % v).replace(".", ",").replace("+", "+%").replace("-", "-%")
def fz_en(v): return ("%+.1f%%" % v)
EK = """
<h3>%s</h3>
<p>%s</p>
<div class="kpis">%s%s%s%s</div>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
%s
%s
%s
""" % (
 x("Alt kesitler: vitra.com.tr, pazaryeri ve fiyat karşılaştırma siteleri", "Sub-segments: vitra.com.tr, marketplaces and price comparison sites"),
 x("Sezonsallık dosyasındaki dokuz ana kategorinin (klozet, lavabo, armatür, duşlar, rezervuar, yıkanma alanları, banyo mobilyası, banyo aksesuarı ve vitrifiye tamamlayıcıları) daha önce taranmamış 57 alt kesiti için vitra.com.tr kategori sayfaları, Trendyol ve Hepsiburada çok satan aramaları, Akakçe ve Cimri aramaları ile altı rakip mağazanın arama sayfaları 30.09.2026'da okunmuştur; toplam 11.982 ürün satırı ve 58 vitra.com.tr sayfası. Akıllı klozet, klozet kapağı, lavabo dolabı, boy dolabı, gömme rezervuar, lavabo ve banyo bataryası gibi daha önce taranan kesitler yukarıdaki tablolarda kalmaktadır.",
   "For 57 previously unscanned sub-segments of the nine main categories in the seasonality file (WC, washbasin, taps, showers, cisterns, bathing, bathroom furniture, accessories and sanitaryware accessories), the vitra.com.tr category pages, Trendyol and Hepsiburada best-seller searches, Akakçe and Cimri searches and the search pages of six competitor stores were read on 30.09.2026; 11,982 product rows and 58 vitra.com.tr pages in total. Previously scanned segments such as smart WCs, toilet seats, basin units, tall cabinets, concealed cisterns and basin and bath taps remain in the tables above."),
 kpi_kart(yzd(top_yok / top_kart * 100), "vitra.com.tr'de 55 kategori sayfasındaki %s varyant kartının stoklu süzgeci dışında kalan payı (%s kart \"Gelince Haber Ver\")" % (bin(top_kart), bin(top_yok)), "Share of the %s variant cards on 55 vitra.com.tr category pages outside the in-stock filter (%s cards \"notify when available\")" % (k(top_kart), k(top_yok)), "dn"),
 kpi_kart(str(len(sifir)), "Stoklu ürün bulunmayan alt kategori sayfası (14 sayfa): duş ünitesi 119, bağımsız küvet 44, bide bataryası 33, pisuvar yıkama sistemi 12 kart", "Sub-category pages without any in-stock product (14 pages): shower unit 119, freestanding bath 44, bidet tap 33, urinal flush system 12 cards", "dn"),
 kpi_kart(fz(G["medyan_liste"]), "Aynı model kodunda pazaryeri fiyatının vitra.com.tr liste fiyatına göre medyan farkı (%s eşleşme, %s model kodu); sepet fiyatına göre Trendyol %s, Hepsiburada %s" % (FE["toplam_eslesme"], FE["benzersiz_kod"], fz(KA["trendyol"]["medyan_sepet"]), fz(KA["hepsiburada"]["medyan_sepet"])),
          "Median gap of the marketplace price to the vitra.com.tr list price for the same model code (%s matches, %s model codes); against the basket price Trendyol %s, Hepsiburada %s" % (FE["toplam_eslesme"], FE["benzersiz_kod"], fz_en(KA["trendyol"]["medyan_sepet"]), fz_en(KA["hepsiburada"]["medyan_sepet"])), "dn"),
 kpi_kart("%d / 57" % len(vitrasiz), "Dört listede (Trendyol, Hepsiburada, Akakçe, Cimri) hiç VitrA ya da Artema ürünü görülmeyen alt kesit; 10'unda vitra.com.tr'de ürün sayfası var", "Sub-segments with no VitrA or Artema product in any of the four lists (Trendyol, Hepsiburada, Akakçe, Cimri); 10 of them have product pages on vitra.com.tr", "hi"),
 T5,
 insight("VitrA ve Artema, duş ve armatür tamamlayıcılarında pazaryeri listelerinin büyük bölümünü doldurmaktadır: sürgülü el duşu takımında Trendyol'da eşleşen 36 ürünün 26'sı, Hepsiburada'da 33'ün 21'i, Akakçe'de 32'nin 25'i ve Cimri'de 32'nin 16'sı VitrA ya da Artema'dır; Trendyol'da kesit değerlendirmelerinin %95,6'sı Artema'ya aittir. Ankastre stop valfte Hepsiburada 36'nın 21'i, Akakçe 32'nin 22'si, Cimri 31'in 20'si; taşıyıcı aparatta Hepsiburada değerlendirmelerinin %100'ü VitrA'dadır. Seramik ve küvet kesitlerinde tablo tersine dönmektedir: 11 alt kesitte (yarım tezgah lavabo, köşe lavabo, duş ünitesi, hidromasajlı küvet, küvet paneli, duş teknesi paneli, kaydırmaz, banyo konsolu, dolap kulpu, dolap ayağı ve sabunluk) dört listenin hiçbirinde VitrA ürünü görülmemekte, bunların 10'unda vitra.com.tr'de ürün sayfası bulunmaktadır (sabunluk 70, duş ünitesi 119, hidromasajlı küvet 84 kart). Çanak lavaboda Trendyol değerlendirmelerinin %96,4'ü ve etajerli lavaboda Hepsiburada'nın %94,2'si Turkuaz'da toplanmakta; bağımsız küvette Trendyol listesi bebek küveti ürünleriyle (Zuu Baby %97,6) dolmaktadır. Çocuk klozeti aramasında Trendyol 2.238 ve Hepsiburada 1.659 sonuç, engelli klozeti için Trendyol'da 43 ürünlük ayrı kategori bulunurken vitra.com.tr'de bu iki başlık ile köşe lavabo ve lavabo ayağı için ayrı kategori sayfası yoktur.",
         "VitrA and Artema fill most of the marketplace lists in shower and tap accessories: in sliding-rail hand shower sets 26 of the 36 matching products on Trendyol, 21 of 33 on Hepsiburada, 25 of 32 on Akakçe and 16 of 32 on Cimri are VitrA or Artema; on Trendyol 95.6% of the segment's reviews belong to Artema. In concealed stop valves 21 of 36 on Hepsiburada, 22 of 32 on Akakçe and 20 of 31 on Cimri; in WC frames 100% of Hepsiburada reviews are VitrA's. In ceramic and bath segments the picture reverses: in 11 sub-segments (semi-recessed basin, corner basin, shower unit, whirlpool bath, bath panel, shower tray panel, anti-slip mat, bathroom console, cabinet handle, cabinet leg and soap dish) no VitrA product appears in any of the four lists, and 10 of them have product pages on vitra.com.tr (soap dish 70, shower unit 119, whirlpool bath 84 cards). In bowl basins 96.4% of Trendyol reviews and in basins with shelf 94.2% of Hepsiburada reviews sit with Turkuaz; the Trendyol freestanding bath list is filled with baby bath products (Zuu Baby 97.6%). The children's WC search returns 2,238 results on Trendyol and 1,659 on Hepsiburada, and Trendyol has a separate 43-product category for accessible WCs, while vitra.com.tr has no separate category page for these two headings or for corner basins and basin pedestals."),
 x("vitra.com.tr kategori sayfaları: ürün, fiyat aralığı ve stok", "vitra.com.tr category pages: products, price range and stock"), T6,
 insight("Taranan 55 kategori sayfasındaki %s renk ve varyant kartının %s'sı (%s) stoklu süzgecinin dışında kalmaktadır ve %d alt kategoride (14 sayfa) hiç stoklu ürün bulunmamaktadır: duş ünitesi (119 kart), bağımsız küvet (44), bide bataryası (33), pisuvar yıkama sistemi (12), duvar önü rezervuar (8), taşıyıcı aparat (3) ve yedi kesit daha. Kartlarda fiyat gösterilmeye devam ettiğinden stokta olmayan ürünler kategori sayfasının ürün sayısına ve fiyat aralığına dahil kalmaktadır; %s listesindeki 89 ürünün 42'si de \"Gelince Haber Ver\" durumundadır. İlk sayfadaki %s kartın %s'ünde (%s) \"Sepette %%N indirim\" etiketi bulunmaktadır; oranlar %%10 (358 kart), %%14 (237) ve %%15 (98) düzeyindedir ve %s sayfası 413 varyantla listelenmektedir. Yönlendirme döngüsüne giren %s sayfası sitemap'te listelenmeye devam etmektedir." % (bin(top_kart), yzd(top_yok / top_kart * 100), bin(top_yok), len(sifir), u("https://www.vitra.com.tr/c-ucretsiz-montaj", "/c-ucretsiz-montaj"), bin(sepet_t), yzd(sepet_n / sepet_t * 100), bin(sepet_n), u("https://www.vitra.com.tr/c-kampanyali-urunler", "/c-kampanyali-urunler"), veri_m("/c-online-ozel")),
         "Of the %s colour and variant cards on the 55 category pages scanned, %s (%s) fall outside the in-stock filter and %d sub-categories (14 pages) have no in-stock product at all: shower unit (119 cards), freestanding bath (44), bidet tap (33), urinal flush system (12), exposed cistern (8), WC frame (3) and seven more segments. Because the cards keep showing a price, out-of-stock products remain in the category page's product count and price range; 42 of the 89 products in the %s list are also \"notify when available\". %s of the %s first-page cards (%s) carry an \"N%% off in basket\" label; the rates are 10%% (358 cards), 14%% (237) and 15%% (98), and the %s page lists 413 variants. The %s page, which enters a redirect loop, is still listed in the sitemap." % (k(top_kart), k(top_yok), yzd(top_yok / top_kart * 100).replace("%", "").replace(",", ".") + "%", len(sifir), u("https://www.vitra.com.tr/c-ucretsiz-montaj", "/c-ucretsiz-montaj"), yzd(sepet_n / sepet_t * 100).replace("%", "").replace(",", ".") + "%", k(sepet_t), k(sepet_n), u("https://www.vitra.com.tr/c-kampanyali-urunler", "/c-kampanyali-urunler"), veri_m("/c-online-ozel"))),
 x("Alt kesitlerde rakip mağazalar", "Competitor stores in the sub-segments"), T7,
 insight("Banyomarka (249 eşleşen VitrA satırı, 28 kesit) ve Banyoline (125 satır, 32 kesit) alt kesitlerde de VitrA'yı geniş listeleyen mağazalardır; Koçtaş'ta VitrA 84 ve Artema 64 satır (25 kesit) bulunurken Bauhaus'ta VitrA ve Artema üçer satırla sınırlı kalmaktadır. Banyomarka'da sürgülü el duşu takımında eşleşen 32 ürünün 32'si VitrA ya da Artema'dır; markanın Grohe (203 satır), Artema (96) ve Duravit (64) ile birlikte listelendiği görülmektedir. Fiyat düzeyi mağazaya göre belirgin biçimde ayrışmaktadır: çanak lavaboda medyan Banyomega'da 15.340 TL, Banyomarka'da 13.595 TL, Creavit e-mağazasında 7.686 TL, Koçtaş'ta 5.315 TL ve Banyoline'da 3.293 TL'dir; Banyomarka'da monoblok lavabo medyanı 60.025 TL ve hidromasajlı küvet medyanı 254.250 TL ile yüksek fiyat bandındadır. Koçtaş'ın \"Koçtaş Basic\" markası sabunluk kesitinde 7 ürün ve %72 değerlendirme payıyla, Bauhaus sonuçlarında Primanova 68 satırla (sabunluk aramasında 24 ürünün 24'ü) yer almaktadır; Creavit e-mağazası tüm ürünleri liste fiyatının altında indirimli göstermektedir.",
         "Banyomarka (249 matching VitrA rows, 28 segments) and Banyoline (125 rows, 32 segments) are also the stores listing VitrA widely in the sub-segments; Koçtaş carries 84 VitrA and 64 Artema rows (25 segments), while Bauhaus is limited to three VitrA and three Artema rows. At Banyomarka all 32 matching sliding-rail hand shower sets are VitrA or Artema; the brand is listed alongside Grohe (203 rows), Artema (96) and Duravit (64). Price levels differ clearly by store: the bowl basin median is 15,340 TL at Banyomega, 13,595 TL at Banyomarka, 7,686 TL at the Creavit e-store, 5,315 TL at Koçtaş and 3,293 TL at Banyoline; at Banyomarka the monoblock basin median of 60,025 TL and the whirlpool bath median of 254,250 TL sit in the high price band. Koçtaş's \"Koçtaş Basic\" brand appears in the soap dish segment with 7 products and a 72% review share, and Primanova appears in Bauhaus results with 68 rows (24 of 24 products in the soap dish search); the Creavit e-store shows all products discounted below list price."),
 x("Aynı model kodunda vitra.com.tr ve pazaryeri fiyatı", "vitra.com.tr and marketplace price for the same model code"), T8, T9,
 insight("Ürün adında vitra.com.tr model kodu birebir geçen %s eşleşmede (%s model kodu) pazaryeri fiyatı liste fiyatının medyan %s altındadır: Akakçe %s (%s eşleşme), Cimri %s (%s), Trendyol %s (%s) ve Hepsiburada %s (%s). \"Sepette %%N indirim\" uygulanmış fiyata göre fark Trendyol'da %s ve Cimri'de %s ile kapanmakta, Hepsiburada'da %s ile pazaryeri lehine dönmektedir; yani pazaryeri fiyatı sitenin sepet fiyatına yakın seyretmekte, liste fiyatı ise kategori sayfasında görünen fiyat olmaya devam etmektedir. Fark iki yönde de açılabilmektedir: üçüncü taraf satıcılarda pisuvar yıkama sistemi 310-2521 (site 7.412 TL) Hepsiburada'da üç satıcıda 14.848 - 15.923 TL, Root Round küvet bataryası A42743 (site 29.882 TL) 65.948 TL, Arkitekta köşe malzemelik A44051 (site 3.747 TL) Trendyol'da 10.129 TL ile liste fiyatının 2 ila 2,7 katına listelenmiştir; %s eşleşmede pazaryeri fiyatı liste fiyatının 1,5 katını aşmaktadır. Trendyol'da VitrA ve Artema satırlarının 105'inden 33'ü resmi mağazadan, Hepsiburada'da 180 satırın 19'u VitrA mağazasından ve 21'i Hepsiburada'nın kendi satışından gelmekte, kalan satırlar 37 ve 69 farklı üçüncü taraf satıcıya dağılmaktadır." % (FE["toplam_eslesme"], FE["benzersiz_kod"], yzd(abs(G["medyan_liste"])), fz(KA["akakce"]["medyan_liste"]), KA["akakce"]["n"], fz(KA["cimri"]["medyan_liste"]), KA["cimri"]["n"], fz(KA["trendyol"]["medyan_liste"]), KA["trendyol"]["n"], fz(KA["hepsiburada"]["medyan_liste"]), KA["hepsiburada"]["n"], fz(KA["trendyol"]["medyan_sepet"]), fz(KA["cimri"]["medyan_sepet"]), fz(KA["hepsiburada"]["medyan_sepet"]), FE["ustu_1_5x"]),
         "In the %s matches (%s model codes) whose product name contains a vitra.com.tr model code verbatim, the marketplace price is a median %s below the list price: Akakçe %s (%s matches), Cimri %s (%s), Trendyol %s (%s) and Hepsiburada %s (%s). Against the price after the \"N%% off in basket\" label the gap closes to %s on Trendyol and %s on Cimri and turns in the marketplace's favour at %s on Hepsiburada; in other words the marketplace price tracks the site's basket price while the list price remains the price shown on the category page. The gap opens in both directions: at third-party sellers the urinal flush system 310-2521 (site 7,412 TL) is listed at 14,848 - 15,923 TL by three Hepsiburada sellers, the Root Round bath filler A42743 (site 29,882 TL) at 65,948 TL and the Arkitekta corner storage unit A44051 (site 3,747 TL) at 10,129 TL on Trendyol, 2 to 2.7 times the list price; in %s matches the marketplace price exceeds 1.5 times the list price. On Trendyol 33 of the 105 VitrA and Artema rows come from the official store, on Hepsiburada 19 of 180 rows from the VitrA store and 21 from Hepsiburada's own sales, with the remaining rows spread over 37 and 69 different third-party sellers." % (FE["toplam_eslesme"], FE["benzersiz_kod"], ("%.1f%%" % abs(G["medyan_liste"])), fz_en(KA["akakce"]["medyan_liste"]), KA["akakce"]["n"], fz_en(KA["cimri"]["medyan_liste"]), KA["cimri"]["n"], fz_en(KA["trendyol"]["medyan_liste"]), KA["trendyol"]["n"], fz_en(KA["hepsiburada"]["medyan_liste"]), KA["hepsiburada"]["n"], fz_en(KA["trendyol"]["medyan_sepet"]), fz_en(KA["cimri"]["medyan_sepet"]), fz_en(KA["hepsiburada"]["medyan_sepet"]), FE["ustu_1_5x"])),
 note("KISIT", "LIMITATION", ul_b([("Arama tabanlı kesitler:", "Search-based segments:", "pazaryerlerinde ve mağazalarda bu alt kategoriler için birebir kategori sayfası çoğunlukla bulunmadığından sonuçlar arama sırasına bağlıdır; eşleşme, ürün ya da kategori adında kesit anahtar sözcüğünün geçmesiyle yapılmıştır ve toplam değerleri aramanın tüm sonuçlarını kapsar.", "marketplaces and stores mostly have no exact category page for these sub-categories, so results depend on search order; matching is based on the segment keyword appearing in the product or category name, and totals cover all search results."),
                                   ("Cimri:", "Cimri:", "iki denemede 429 yanıtı alındığından 5 kesit okunmamış (banyo askısı, banyo çöp kovası, havluluk, pisuvar ara bölmesi, pisuvar yıkama sistemi), farklı kart düzenindeki 12 kesitte sonuç alınamamıştır.", "5 segments were not read after 429 responses in two attempts (robe hook, bathroom bin, towel rail, urinal divider, urinal flush system), and 12 segments with a different card layout returned no results."),
                                   ("vitra.com.tr stok sayımı:", "vitra.com.tr stock count:", "14 sayfada \"Sadece stoklu ürünleri göster\" süzgeci sonuç döndürmediğinden stoklu sayı 0 kabul edilmiş, ilk sayfadaki tüm kartların \"Gelince Haber Ver\" işaretli olması dayanak alınmıştır; sepet indirimi sayfa veri katmanına yansımadığından liste fiyatı üzerinden hesaplanmıştır.", "on 14 pages the \"show only in-stock products\" filter returned no results, so the in-stock count was taken as 0 based on every first-page card being marked \"notify when available\"; the basket discount is not reflected in the page data layer and was calculated from the list price."),
                                   ("Toplam değerleri:", "Totals:", "Hepsiburada 11 kesitte 10.000 üst sınırındadır; Akakçe arama sayfalarında toplam gösterilmemektedir; Koçtaş dışındaki mağazalarda çok satan sıralaması bulunmamaktadır. Fiyat, stok ve etiketler 30.09.2026 tarama anına aittir.", "Hepsiburada is capped at 10,000 in 11 segments; Akakçe search pages show no total; stores other than Koçtaş have no best-seller order. Prices, stock and labels belong to the 30.09.2026 scan.")])),
 kaynak("vitra.com.tr 55 kategori ve 3 özel sayfa · Trendyol, Hepsiburada, Akakçe ve Cimri aramaları (57 kesit) · Koçtaş, Bauhaus, Banyomarka, Banyomega, Banyoline ve Creavit e-mağaza aramaları · Chrome · 30.09.2026", "vitra.com.tr 55 category and 3 special pages · Trendyol, Hepsiburada, Akakçe and Cimri searches (57 segments) · Koçtaş, Bauhaus, Banyomarka, Banyomega, Banyoline and Creavit e-store searches · Chrome · 30.09.2026", "D30"),
)
