# -*- coding: utf-8 -*-
"""Bolum: Kanal rolleri, etkilesim modeli, set ve tamamlayici urun, satis sonrasi."""
from ortak import *
from rapor_parca1 import T
from b_talep import kat
NI = A["niyet"]; GS = A["gsc_sorgu_niyet"]; AU = A["auto"]
KANAL = tablo([th("Kanal", "Channel", "Satış kanalı.", "Sales channel."),
               th("Bugünkü rol", "Current role", "Bu çalışmadaki gözlemlere dayalı mevcut konum; VitrA'nın panel verisiyle doğrulanacaktır.", "Current position based on the observations in this study; to be verified with VitrA's panel data."),
               th("Önerilen rol", "Proposed role", "Kanalın büyüme planında üstlenebileceği rol.", "The role the channel can take in the growth plan."),
               th("Öne çıkarılabilecek ürün grubu", "Product group to feature", "Talep ve ihtiyaç verisine göre kanalda öne çıkarılabilecek grup.", "Group that can be featured in the channel according to demand and need data.")],
              [[x("vitra.com.tr", "vitra.com.tr"), x("Marka ve kategori aramalarının vardığı bilgi ve satın alma noktası; organik tıkların %s'i kategori sayfalarına gelmektedir" % yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())), "The information and purchase point where brand and category searches arrive; %s of organic clicks land on category pages" % (yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())).replace("%", "") + "%")),
                x("Tam katalog, set kurgusu, yedek parça ve montaj hizmetinin tek adresi; yüksek sepetli ürünlerde danışmanlık ve geri arama", "The single address for the full catalogue, set design, spare parts and installation service; consultation and call-back for high-basket products"),
                x("Gömme rezervuar setleri, akıllı klozet, banyo mobilyası setleri, yedek parça", "Concealed cistern sets, smart WC, bathroom furniture sets, spare parts")],
               [x("Trendyol", "Trendyol"), x("Kategoride en yüksek trafikli pazaryeri (tahmini aylık %s organik ziyaret); fiyat ve kampanya odaklı karşılaştırma" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com")), "The highest-traffic marketplace in the category (estimated %s monthly organic visits); price and campaign-led comparison" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com"))),
                x("Giriş fiyatlı ve hızlı karar ürünlerinde erişim kanalı; kupon ve taksit kampanyalarıyla hacim", "Reach channel for entry-priced and quick-decision products; volume through coupon and instalment campaigns"),
                x("Klozet kapağı, batarya, aksesuar, duş seti, iç takım", "Toilet seats, taps, accessories, shower sets, inner mechanisms")],
               [x("Hepsiburada", "Hepsiburada"), x("İkinci pazaryeri (tahmini aylık %s organik ziyaret); ev ve yapı kategorisinde güçlü, teslimat ve taksit vurgulu" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com")), "The second marketplace (estimated %s monthly organic visits); strong in home and construction, delivery and instalment led" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com"))),
                x("Orta segment ve büyük hacimli ürünlerde taksit ve teslimat vaadiyle ikinci erişim kanalı", "Second reach channel for mid-segment and bulky products with instalment and delivery promise"),
                x("Klozet takımı, banyo dolabı, duşakabin, küvet", "WC sets, bathroom cabinets, shower enclosures, bathtubs")],
               [x("Yapı market (Koçtaş, Bauhaus, Tekzen)", "DIY retailers (Koçtaş, Bauhaus, Tekzen)"), x("Kategori aramalarında VitrA ile en çok ortak kelimeye sahip kanal; \"vitra klozet fiyatları koçtaş\" gibi aramalar mevcut", "The channel sharing the most keywords with VitrA in category searches; searches such as \"vitra klozet fiyatları koçtaş\" exist"),
                x("Tamamlayıcı ürün ve montaj hizmetiyle birlikte satış; VitrA'nın üretmediği düşük fiyatlı tamamlayıcı ürünlerde kendi kanalına satıcı modeli", "Sales together with complementary products and installation service; a seller model in the own channel for low-priced complementary products VitrA does not make"),
                x("Klozet, lavabo, batarya, montaj malzemesi", "WCs, washbasins, taps, fitting materials")]])
ADIM = "".join([
 step(1, "Fiyat ve stok netliği", "Price and stock clarity", "Hacimli üründe ilk soru \"fiyat aynı mı, stokta var mı\" olmaktadır; ürün sayfasında güncel fiyat, taksit tablosu ve teslim aralığı birlikte gösterilebilir.", "For a bulky product the first question is \"is the price the same, is it in stock\"; current price, instalment table and delivery window can be shown together on the product page."),
 step(2, "Geri arama ve keşif", "Call-back and site survey", "Banyo mobilyası, duşakabin ve küvet gibi ölçüye bağlı ürünlerde \"beni arayın\" formu ve ücretli/ücretsiz keşif hizmeti; talep, ilgili ile bayiye yönlendirilebilir.", "For dimension-dependent products such as bathroom furniture, shower enclosures and bathtubs, a \"call me\" form and a paid/free site survey; the request can be routed to the relevant dealer."),
 step(3, "Lokal bayi ve stok", "Local dealer and stock", "Sipariş, kullanıcıya en yakın bayinin stoğundan karşılanabilir; teslim süresi kısalır, montaj aynı bayi tarafından planlanabilir.", "The order can be fulfilled from the stock of the dealer nearest to the user; delivery time shortens and installation can be planned by the same dealer."),
 step(4, "Montaj ve usta eşleşmesi", "Installation and installer matching", "\"klozet montaj ücreti\", \"klozet taktırma fiyatı\" aramaları montaj hizmetinin ürünle birlikte istendiğini göstermektedir; sepette montaj seçeneği ve sabit ücret tanımlanabilir.", "Searches such as \"klozet montaj ücreti\" and \"klozet taktırma fiyatı\" show the installation service is wanted with the product; an installation option with a fixed fee can be defined in the basket."),
 step(5, "Eksik ürün kontrolü", "Missing item check", "Klozet için iç takım, bağlantı borusu ve montaj aparatı; batarya için ara musluk ve hortum gibi tamamlayıcılar sepette önerilebilir.", "Complementary items such as the inner mechanism, connection pipe and fitting kit for a WC, or stop valves and hoses for a tap, can be suggested in the basket."),
 step(6, "Yapay zeka destekli ön görüşme", "AI-assisted pre-consultation", "Bir dakikalık sesli veya yazılı görüşmeyle ölçü, mevcut ürün ve ihtiyacın alınması; sonuç bayiye veya çağrı merkezine iletilebilir.", "A one-minute voice or text conversation to capture dimensions, the existing product and the need; the result can be passed to the dealer or call centre."),
])
tam = NI["Tamir ve bakım"]; mon = NI["Montaj"]
TAMAMLAYICI = tablo([th("Ürün grubu", "Product group", "VitrA'nın üretmediği veya sınırlı ürettiği, kategori satın almasıyla birlikte ihtiyaç duyulan grup.", "Group VitrA does not make or makes in limited range, needed together with the category purchase."),
                     th("Talep sinyali", "Demand signal", "Kelime araştırması, autocomplete veya Search Console'daki ifade.", "Phrase in keyword research, autocomplete or Search Console."),
                     th("Bugün nerede satılıyor?", "Where is it sold today?", "Kullanıcının bu ürünü bulduğu kanal; rakip site incelemesine göre.", "Channel where the user finds this product; according to the competitor site review."),
                     th("Model önerisi", "Model proposal", "vitra.com.tr için değerlendirilebilecek satış modeli.", "Sales model that can be considered for vitra.com.tr.")],
                    [[x("Montaj malzemesi ve bağlantı parçaları", "Fitting materials and connection parts"), x("\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\"", "\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\""), x("Yapı market, nalbur, pazaryeri", "DIY retailer, hardware store, marketplace"), x("Üçüncü taraf satıcı veya kendi stok; klozet sepetine otomatik öneri", "Third-party seller or own stock; automatic suggestion in the WC basket")],
                     [x("Taharet musluğu ve ara musluk", "Bidet spray and stop valve"), x("\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\"", "\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\""), x("Artema kataloğu, yapı market", "Artema catalogue, DIY retailer"), x("Artema ürünleriyle klozet seti; tek sepet", "WC set with Artema products; single basket")],
                     [x("Banyo tekstili ve küçük aksesuar", "Bathroom textiles and small accessories"), x("Aksesuar setleri talebi daralmakta (%s); tek parça aksesuar aramaları sürmekte" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"]), "Accessory set demand contracting (%s); single-item accessory searches continue" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"])), x("Pazaryeri, ev tekstili markaları", "Marketplace, home textile brands"), x("Seçili üçüncü taraf markalarla sepet tamamlama", "Basket completion with selected third-party brands")],
                     [x("Su ısıtıcı, havlupan, aydınlatma", "Water heater, towel radiator, lighting"), x("\"havlupan\" kategori sayfası organik tık almakta (c-havlupanlar); banyo yenilemesinde birlikte alınan ürünler", "The \"havlupan\" category page receives organic clicks (c-havlupanlar); products bought together in a bathroom renovation"), x("Yapı market, pazaryeri", "DIY retailer, marketplace"), x("Yenileme paketi içinde üçüncü taraf ürün; VitrA ürünü sepetin merkezinde", "Third-party product within a renovation package; the VitrA product at the centre of the basket")],
                     [x("Yedek parça (iç takım, şamandıra, menteşe, conta)", "Spare parts (inner mechanism, float valve, hinge, gasket)"), x("Tamir ve bakım aramaları aylık %s; autocomplete önerilerinin %s'i" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values()))), "Repair and maintenance searches %s per month; %s of autocomplete suggestions" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values())).replace("%", "") + "%")), x("Yetkili servis, nalbur, pazaryeri üçüncü taraf satıcılar", "Authorised service, hardware store, third-party marketplace sellers"), x("Ürün koduna göre yedek parça sayfası; montaj videosu ile birlikte satış", "Spare-part page by product code; sale together with the installation video")]])
HTML = """
<p class="lede">%s</p>
<h3>%s</h3>
%s
%s
<h3>%s</h3>
<p>%s</p>
<div class="steps">%s</div>
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
""" % (
 x("Bu bölüm, talep ve davranış verisinin e-ticaret modeline nasıl çevrilebileceğini ele almaktadır: kanalların rol paylaşımı, düşük dönüşümlü hacimli ürünler için etkileşim modeli, set ve tamamlayıcı ürün kurgusu ve satış sonrası döngü. Öneriler, VitrA'dan beklenen pazaryeri ve GA4 verisiyle güncellenecektir.",
   "This section addresses how demand and behaviour data can be translated into the e-commerce model: role sharing across channels, an engagement model for low-conversion bulky products, set and complementary product design, and the after-sales loop. The proposals will be updated with the marketplace and GA4 data expected from VitrA."),
 x("Kanal rolleri", "Channel roles"), KANAL,
 insight("Üç kanal aynı ürünü aynı fiyatla listelediğinde kullanıcı en tanıdık ve en hızlı kanalı seçmekte, marka sitesi karşılaştırma listesinin dışında kalmaktadır. Rol ayrımı, her kanalın kendi güçlü olduğu ürün grubu ve hizmetle konumlanmasını sağlar: pazaryerinde hızlı karar ürünleri ve kampanya, marka sitesinde set, yedek parça, montaj ve danışmanlık. Kanallar arası fiyat tutarlılığı ise her durumda korunmalıdır; aksi halde marka sitesi \"pahalı kanal\" olarak algılanmaktadır.",
         "When three channels list the same product at the same price the user picks the most familiar and fastest channel, and the brand site drops off the comparison list. Role separation lets each channel position itself with the product group and service it is strong in: quick-decision products and campaigns on the marketplace; sets, spare parts, installation and consultation on the brand site. Price consistency across channels must be maintained in every case; otherwise the brand site is perceived as the \"expensive channel\"."),
 x("Düşük dönüşümlü hacimli ürünlerde etkileşim modeli", "Engagement model for low-conversion bulky products"),
 x("Banyo mobilyası, duşakabin, küvet ve gömme rezervuar seti gibi ürünlerde kullanıcı siteye gelmekte ancak satın alma yerine bayiye veya yapı markete gitmektedir. Bu ürünlerde karar öncesi dört belirsizlik bulunmaktadır: doğru vakitte teslim, fiyatın aynı olup olmadığı, ek ürün ve usta ihtiyacı, depodan eve giden sürecin nasıl işlediği. Aşağıdaki altı bileşen bu belirsizlikleri sırasıyla ele almaktadır.",
   "For products such as bathroom furniture, shower enclosures, bathtubs and concealed cistern sets the user arrives at the site but goes to a dealer or DIY store instead of buying. Four uncertainties precede the decision for these products: delivery at the right time, whether the price is the same, the need for additional products and an installer, and how the process from warehouse to home works. The six components below address these uncertainties in turn."),
 ADIM,
 insight("Etkileşim modelinin amacı ziyareti hemen satışa değil, ölçülebilir bir lead'e çevirmektir: geri arama, keşif talebi, bayi yönlendirmesi ve montaj talebi ayrı olaylar olarak ölçülebilir. GA4 talebinde bu olaylar (lead olayları) yer almaktadır; mevcut ölçümde bulunmuyorsa tanımlanması, modelin etkisinin izlenmesi için ön koşuldur.",
         "The aim of the engagement model is to turn the visit not into an immediate sale but into a measurable lead: call-back, site survey request, dealer referral and installation request can each be measured as separate events. These events (lead events) are included in the GA4 request; if they are missing from current measurement, defining them is a prerequisite for tracking the model's effect."),
 x("Set ve tamamlayıcı ürün kurgusu", "Set and complementary product design"),
 TAMAMLAYICI,
 insight("Kullanıcı klozet alırken iç takımı, bağlantı borusunu ve montaj aparatını da aramakta; bunları çoğunlukla yapı marketten tamamlamaktadır. VitrA'nın üretmediği, 4-5 bin TL altındaki tamamlayıcı ürünlerin vitra.com.tr üzerinde üçüncü taraf satıcı modeliyle sunulması, sepetin bölünmesini engelleyebilir ve marka sitesini \"tek durak\" hâline getirebilir. Bu model, Amazon ve Hepsiburada'nın kendi ürünleriyle üçüncü taraf ürünlerini aynı sepette birleştiren yapısına benzemektedir; ilk adım olarak montaj malzemesi ve yedek parça gruplarında test edilebilir.",
         "When buying a WC the user also searches for the inner mechanism, connection pipe and fitting kit, and mostly completes these at a DIY store. Offering the complementary products VitrA does not make, priced below 4-5 thousand TL, on vitra.com.tr through a third-party seller model can prevent the basket from splitting and make the brand site the \"one stop\". This model resembles the structure Amazon and Hepsiburada use to combine their own products with third-party products in the same basket; it can be tested first in the fitting material and spare-part groups."),
 x("Satış sonrası döngü", "The after-sales loop"),
 marks([("up", "Yedek parça sayfası: ürün koduna göre iç takım, şamandıra, menteşe, conta; montaj videosuyla birlikte. Tamir aramaları aylık %s, autocomplete önerilerinin %s'i bu temadadır" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values()))), "Spare-part page: inner mechanism, float valve, hinge, gasket by product code, together with the installation video. Repair searches %s per month, %s of autocomplete suggestions are in this theme" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values())).replace("%", "") + "%")),
        ("up", "Satış sonrası memnuniyet ölçümü ve tekrar sipariş takibi: olumsuz deneyim yaşayan müşterinin tekrar sipariş oranı, Şikayetvar kayıtlarıyla eşleştirilerek izlenebilir", "After-sales satisfaction measurement and repeat-order tracking: the repeat-order rate of customers with a poor experience can be tracked by matching with Şikayetvar records"),
        ("up", "Retargeting: ürünü inceleyip satın almayan kullanıcıya teslimat ve taksit mesajı; satın alan kullanıcıya 5 yıl sonra yenileme ve yedek parça hatırlatması", "Retargeting: delivery and instalment message to the user who viewed but did not buy; renewal and spare-part reminder to the buyer five years later"),
        ("at", "Servis süreci belirsizliği: \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\" önerileri; servis sayfasında ücret, randevu ve en yakın servis bilgisi açıkça verilebilir", "Service process uncertainty: suggestions such as \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\"; fee, appointment and nearest service information can be given clearly on the service page"),
        ("at", "\"vitra taksit seçenekleri\", \"vitra 9 taksit\" aramaları: taksit bilgisi ürün sayfasında ve ayrı bir taksit sayfasında görünür olmalıdır", "Searches such as \"vitra taksit seçenekleri\" and \"vitra 9 taksit\": instalment information should be visible on the product page and on a separate instalment page")]),
 kaynak("Bölüm 03-08 verileri · Google Keyword Planner, Search Console, Autocomplete, YouTube, Ahrefs · model önerileri Inbound", "Data from Sections 03-08 · Google Keyword Planner, Search Console, Autocomplete, YouTube, Ahrefs · model proposals by Inbound", "D1", "D2", "D3", "D4", "D5"),
)
