# -*- coding: utf-8 -*-
"""Bolum: Kanal rolleri, etkilesim modeli, set ve tamamlayici urun, satis sonrasi."""
from ortak import *
import gsc12 as _G12
from b_marka import AT as _MAT
from b_marka import AT as _AT
from rapor_parca1 import T
from b_talep import kat
NI = A["niyet"]; GS = A["gsc_sorgu_niyet"]; AU = A["auto"]
KANAL = tablo([th("Kanal", "Channel", "Satış kanalı.", "Sales channel."),
               th("Bugünkü rol", "Current role", "Bu çalışmadaki gözlemlere dayalı mevcut konum.", "Current position based on the observations in this study."),
               th("Önerilen rol", "Proposed role", "Kanalın büyüme planında üstlenebileceği rol.", "The role the channel can take in the growth plan."),
               th("Öne çıkarılabilecek ürün grubu", "Product group to feature", "Talep ve ihtiyaç verisine göre kanalda öne çıkarılabilecek grup.", "Group that can be featured in the channel according to demand and need data.")],
              [[x("vitra.com.tr", "vitra.com.tr"), x("Marka ve kategori aramalarının vardığı bilgi ve satın alma noktası; organik tıkların %s'i kategori sayfalarına gelmektedir" % yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())), "The information and purchase point where brand and category searches arrive; %s of organic clicks land on category pages" % (yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())).replace("%", "") + "%")),
                x("Tam katalog, set kurgusu, yedek parça ve montaj hizmetinin tek adresi; yüksek sepetli ürünlerde danışmanlık ve geri arama", "The single address for the full catalogue, set design, spare parts and installation service; consultation and call-back for high-basket products"),
                x("Gömme rezervuar setleri, akıllı klozet, banyo mobilyası setleri, yedek parça", "Concealed cistern sets, smart WC, bathroom furniture sets, spare parts")],
               [x("Trendyol", "Trendyol"), x("Banyo kategorilerinde en yüksek trafikli pazaryeri (site geneli tahmini aylık %s organik ziyaret); fiyat ve kampanya odaklı karşılaştırma" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com")), "The highest-traffic marketplace in bathroom categories (site-wide estimated %s monthly organic visits); price and campaign-led comparison" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com"))),
                x("Giriş fiyatlı ve hızlı karar ürünlerinde erişim kanalı; kupon ve taksit kampanyalarıyla hacim", "Reach channel for entry-priced and quick-decision products; volume through coupon and instalment campaigns"),
                x("Klozet kapağı, batarya, aksesuar, duş seti, iç takım", "Toilet seats, taps, accessories, shower sets, inner mechanisms")],
               [x("Hepsiburada", "Hepsiburada"), x("İkinci pazaryeri (tahmini aylık %s organik ziyaret); ev ve yapı kategorisinde güçlü, teslimat ve taksit vurgulu" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com")), "The second marketplace (estimated %s monthly organic visits); strong in home and construction, delivery and instalment led" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com"))),
                x("Orta segment ve büyük hacimli ürünlerde taksit ve teslimat vaadiyle ikinci erişim kanalı", "Second reach channel for mid-segment and bulky products with instalment and delivery promise"),
                x("Klozet takımı, banyo dolabı, duşakabin, küvet", "WC sets, bathroom cabinets, shower enclosures, bathtubs")]])
def dr(d): return '<span class="badge %s">%s</span>' % ({"Var": "b-var", "Kısmi": "b-kis", "Yok": "b-yok"}[d], x(d, {"Var": "Available", "Kısmi": "Partial", "Yok": "Not available"}[d]))
ETK = tablo([th("Bileşen", "Component", "Hacimli ve ölçüye bağlı üründe karar öncesi belirsizliği azaltan unsur.", "Element that reduces pre-decision uncertainty for bulky and dimension-dependent products."),
             th("VitrA'da bugün", "At VitrA today", "vitra.com.tr üzerindeki mevcut uygulama (29.09.2026).", "Current implementation on vitra.com.tr (29.09.2026)."),
             th("Durum", "Status", "Var, Kısmi (sınırlı kapsam), Yok.", "Available, Partial (limited scope), Not available."),
             th("Geliştirme alanı", "Area for development", "Mevcut yapının üzerine eklenebilecek adım.", "Step that could be added on top of the current structure.")],
    [[x("Fiyat, taksit ve teslim netliği", "Price, instalment and delivery clarity"), x("Ürün sayfasında fiyat, sepette %10 indirim, taksit tablosu, tahmini kargoya teslim tarihi, 30 gün ücretsiz iade", "Price on the product page, 10% basket discount, instalment table, estimated handover-to-carrier date, 30-day free returns"), dr("Kısmi"),
      x("Taksit mesajının tekleştirilmesi (üst bantta 6 ay vade farksız, kampanya sayfasında 9, ürün sayfasında 12 taksit); hacimli üründe kargoya teslim yerine eve teslim aralığının gösterilmesi", "Unifying the instalment message (6 months interest-free in the top banner, 9 on the campaign page, 12 instalments on the product page); showing the home delivery window instead of the carrier handover date for bulky products")],
     [x("Danışmanlık ve geri arama", "Consultation and call-back"), x("Banyo Asistanı: ihtiyaç, fotoğraf, telefon / mağaza / görüntülü görüşme, randevu, WhatsApp teyidi", "Bathroom Assistant: need, photo, phone / store / video call, appointment, WhatsApp confirmation"), dr("Var"),
      x("Mağaza seçeneğinin 5 VitrA mağazasından bayi ağına genişletilmesi; akış adımlarının GA4'te ölçülmesi", "Extending the store option from 5 VitrA stores to the dealer network; measuring the flow steps in GA4")],
     [x("Keşif", "Site survey"), x("Keşif hizmeti 1.400 TL; ölçü ve tesisat uygunluğu, 2 banyoya kadar", "Site survey 1,400 TL; dimension and plumbing suitability, up to 2 bathrooms"), dr("Kısmi"),
      x("Duşakabin, küvet ve mobilya sayfalarından keşfe bağlantı; keşfin ürün alımına bağlı ücretsiz sunulması (Home Depot ücretsiz evde keşif sunuyor)", "Linking to the survey from shower enclosure, bathtub and furniture pages; offering the survey free with a product purchase (Home Depot offers a free in-home consultation)")],
     [x("Montaj", "Installation"), x("11 montaj kalemi, ürün sayfasında montaj seçeneği, söküm ve imha dahil, 1 yıl garanti; ücretsiz montaj listesinde 89 ürün", "11 installation items, installation option on the product page, removal and disposal included, 1-year warranty; 89 products on the free-installation list"), dr("Kısmi"),
      x("Duşakabin, küvet ve duş teknesi için montaj kalemi; il bazında hizmet kapsamının ürün sayfasında gösterilmesi", "An installation item for shower enclosures, bathtubs and shower trays; showing service coverage by province on the product page")],
     [x("Lokal bayi ve stok", "Local dealer and stock"), x("Servisler ve satış noktaları sayfası 1 Ekim 2025 - 30 Eylül 2026 döneminde %s tık almıştır" % bin(_G12.sayfa("/servisler-ve-satis-noktalari")[0]), "The services and sales points page received %s clicks in 1 October 2025 - 30 September 2026" % f"{_G12.sayfa("/servisler-ve-satis-noktalari")[0]:,}"), dr("Kısmi"),
      x("Siparişin kullanıcıya yakın bayi stoğundan karşılanması ve bayide teslim seçeneği", "Fulfilling orders from stock at a dealer near the user and a pick-up at dealer option")],
     [x("Eksik ürün kontrolü", "Missing item check"), x("\"Birlikte Satın Alınanlar\" alanında iç takım, klozet kapağı, ara musluk; uyumlu rezervuar kodu ürün sayfasında", "\"Frequently bought together\" shows inner mechanism, WC seat, stop valve; compatible cistern code on the product page"), dr("Var"),
      x("Montaj parçalarının (esnek hortum, taharet musluğu, bağlantı borusu) tek pakette sunulması; Trendyol'da İDEVİT seti örneği", "Offering fitting parts (flexible hose, bidet valve, connection pipe) in a single pack; the İDEVİT set on Trendyol as an example")],
     [x("Yedek parça ve satış sonrası", "Spare parts and after-sales"), x("Parçalar tekil ürün olarak satılıyor; yedek parça kategorisi ve parça bulucu yok", "Parts are sold as single products; no spare-parts category or part finder"), dr("Yok"),
      x("Ürün koduna göre parça bulucu ve yedek parça kategorisi (Bölüm [[b:yeni]] ve [[b:benchmark]])", "A part finder by product code and a spare-parts category (Sections [[b:yeni]] and [[b:benchmark]])")]], "uzun")
tam = NI["Tamir ve bakım"]; mon = NI["Montaj"]
TAMAMLAYICI = tablo([th("Ürün grubu", "Product group", "VitrA'nın üretmediği veya sınırlı ürettiği, kategori satın almasıyla birlikte ihtiyaç duyulan grup.", "Group VitrA does not make or makes in limited range, needed together with the category purchase."),
                     th("Talep sinyali", "Demand signal", "Kelime araştırması, autocomplete veya Search Console'daki ifade.", "Phrase in keyword research, autocomplete or Search Console."),
                     th("Bugün nerede satılıyor?", "Where is it sold today?", "Kullanıcının bu ürünü bulduğu kanal; rakip site incelemesine göre.", "Channel where the user finds this product; according to the competitor site review."),
                     th("Model önerisi", "Proposed model", "vitra.com.tr için değerlendirilebilecek satış modeli.", "Sales model that can be considered for vitra.com.tr.")],
                    [[x("Montaj malzemesi ve bağlantı parçaları", "Fitting materials and connection parts"), x("\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\"", "\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\""), x("Yapı market, nalbur, pazaryeri", "DIY retailer, hardware store, marketplace"), x("Üçüncü taraf satıcı veya kendi stok; klozet sepetine otomatik öneri", "Third-party seller or own stock; automatic suggestion in the WC basket")],
                     [x("Taharet musluğu ve ara musluk", "Bidet valve and stop valve"), x("\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\"", "\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\""), x("Artema kataloğu, yapı market", "Artema catalogue, DIY retailer"), x("Artema ürünleriyle klozet seti; tek sepet", "WC set with Artema products; single basket")],
                     [x("Banyo tekstili ve küçük aksesuar", "Bathroom textiles and small accessories"), x("Aksesuar setleri talebi Oca-Ağu 2026'da daralmaktadır (%s); tek parça aksesuar aramaları sürmektedir" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"]), "Accessory set demand contracted in Jan-Aug 2026 (%s); single-item accessory searches continue" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"])), x("Pazaryeri, ev tekstili markaları", "Marketplace, home textile brands"), x("Seçili üçüncü taraf markalarla sepet tamamlama", "Basket completion with selected third-party brands")],
                     [x("Su ısıtıcı, havlupan, aydınlatma", "Water heater, towel radiator, lighting"), x("\"havlupan\" kategori sayfası organik tık almakta (c-havlupanlar); banyo yenilemesinde birlikte alınan ürünler", "The \"havlupan\" category page receives organic clicks (c-havlupanlar); products bought together in a bathroom renovation"), x("Yapı market, pazaryeri", "DIY retailer, marketplace"), x("Yenileme paketi içinde üçüncü taraf ürün; VitrA ürünü sepetin merkezinde", "Third-party product within a renovation package; the VitrA product at the centre of the basket")],
                     [x("Yedek parça (iç takım, şamandıra, menteşe, conta)", "Spare parts (inner mechanism, float valve, hinge, gasket)"), x("İç takım, şamandıra, menteşe, kartuş ve conta aramaları aylık %s (genişletilmiş kelime evreni); autocomplete önerilerinin %s'i tamir ve bakım ifadesi" % (k(YK["tema"]["yedek"]["v12"] + YK["tema"]["ic_takim"]["v12"]), yzd(100 * _AT["Tamir ve bakım"] / sum(_AT.values()))), "Searches for inner mechanisms, float valves, hinges, cartridges and gaskets %s per month; %s of autocomplete suggestions are repair and maintenance phrases" % (k(YK["tema"]["yedek"]["v12"] + YK["tema"]["ic_takim"]["v12"]), yzd(100 * _AT["Tamir ve bakım"] / sum(_AT.values())).replace("%", "") + "%")), x("Yetkili servis, nalbur, pazaryeri üçüncü taraf satıcılar", "Authorised service, hardware store, third-party marketplace sellers"), x("Ürün koduna göre yedek parça sayfası; montaj videosu ile birlikte satış", "Spare-part page by product code; sale together with the installation video")]])
HTML = """
<p class="lede">%s</p>
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
""" % (
 x("VitrA bugün <b>Banyo Asistanı</b>, <b>montaj ve keşif hizmetleri</b> ve ürün sayfası bilgileriyle kanal içinde etkileşim sunmaktadır; kanal rolleri ve etkileşim modeli bu mevcut yapıyı temel almaktadır.",
   "Today VitrA offers engagement within the channel through the <b>Bathroom Assistant</b>, <b>installation and survey services</b> and product page information; the channel roles and engagement model take this existing structure as their basis."),
 x("Kanal rolleri", "Channel roles"), KANAL,
 insight("İncelenen 29 VitrA ürününün 19'unda en düşük fiyat vitra.com.tr dışındadır; bu durumda marka sitesi kullanıcı tarafından \"pahalı kanal\" olarak algılanabilir ve karşılaştırma listesinin dışında kalabilir. Rol ayrımı, her kanalın kendi güçlü olduğu ürün grubu ve hizmetle konumlanmasını sağlayabilir: pazaryerinde hızlı karar ürünleri ve kampanya, marka sitesinde ise set, yedek parça, montaj ve danışmanlık öne çıkarılabilir. Kanallar arası fiyat tutarlılığının her durumda korunması önem taşımaktadır; aksi halde marka sitesi \"pahalı kanal\" olarak algılanabilir.",
         "For 19 of the 29 VitrA products reviewed the lowest price is outside vitra.com.tr; in that case users may see the brand site as the \"expensive channel\" and it may drop off their comparison list. Role separation can let each channel position itself with the product group and service it is strong in: quick-decision products and campaigns on the marketplace; sets, spare parts, installation and consultation on the brand site. Maintaining price consistency across channels in every case is important; otherwise the brand site may be perceived as the \"expensive channel\"."),
 x("Hacimli ve ölçüye bağlı ürünlerde etkileşim modeli", "Engagement model for bulky and dimension-dependent products"),
 ETK,
 insight("Etkileşim modelinin bileşenlerinin çoğu VitrA'da bugün mevcuttur; geliştirme alanı, yeni bir araç kurmaktan çok ölçüye bağlı ürün sayfasını keşfe, keşfi montaja ve Banyo Asistanı'nı bayi ağına bağlamaktır. Bu bağlantıların etkisinin görülebilmesi için Banyo Asistanı adımlarının ve montaj / keşif hizmetlerinin ürünle birlikte satın alınma oranının lead olayı olarak ölçülmesi değerlendirilebilir.",
         "Most components of the engagement model exist at VitrA today; the area for development is connecting the existing pieces rather than building a new tool: from the dimension-dependent product page to the survey, from the survey to installation, from the Bathroom Assistant to the dealer network. To see the effect of these connections, measuring the Bathroom Assistant steps and the rate at which installation / survey services are bought with the product as lead events can be considered.", "D13"),
 x("Tamamlayıcı ürün kurgusu", "Complementary product design"),
 TAMAMLAYICI,
 insight("Kullanıcı klozet alırken iç takımı, bağlantı borusunu ve montaj aparatını da aramaktadır; rakip site incelemesinde bu ürünler yapı market ve pazaryerlerinde listelenmektedir. VitrA'nın üretmediği, örneğin 4.000-5.000 TL altındaki tamamlayıcı ürünlerin vitra.com.tr üzerinde üçüncü taraf satıcı modeliyle sunulması, sepetin bölünmesini engelleyebilir ve marka sitesini \"tek durak\" hâline getirebilir. İlk adım olarak montaj malzemesi ve yedek parça gruplarında test edilebilir.",
         "When buying a WC the user also searches for the inner mechanism, connection pipe and fitting kit; in the competitor site review these products are listed at DIY stores and marketplaces. Offering the complementary products VitrA does not make, for example those below 4,000-5,000 TL, on vitra.com.tr through a third-party seller model can prevent the basket from splitting and make the brand site the \"one stop\". It can be tested first in the fitting material and spare-part groups."),
 x("Satış sonrası döngü", "The after-sales loop"),
 marks([("up", ("Yedek parça kategorisi ve parça bulucu: temel kelime setinde tamir ve bakım aramaları aylık %s (iç takım ve yedek parça temaları genişletilmiş evrende aylık " + k(YK["tema"]["yedek"]["v12"] + YK["tema"]["ic_takim"]["v12"]) + "), autocomplete önerilerinin %s'i bu temada") % (k(tam["a26"]), yzd(100 * _MAT["Tamir ve bakım"] / sum(_MAT.values()))), ("Spare-parts category and part finder: repair and maintenance searches %s per month in the base keyword set (inner mechanism and spare-part themes " + k(YK["tema"]["yedek"]["v12"] + YK["tema"]["ic_takim"]["v12"]).replace(",", ".") + " a month in the extended universe), %s of autocomplete suggestions are in this theme") % (k(tam["a26"]), yzd(100 * _MAT["Tamir ve bakım"] / sum(_MAT.values())).replace("%", "") + "%")),
        ("up", "Satış sonrası memnuniyet ölçümü ve tekrar sipariş takibi: olumsuz deneyim yaşayan müşterinin tekrar sipariş oranı, Şikayetvar kayıtlarıyla eşleştirilerek izlenebilir", "After-sales satisfaction measurement and repeat-order tracking: the repeat-order rate of customers with a poor experience can be tracked by matching with Şikayetvar records"),
        ("up", "Retargeting: ürünü inceleyip satın almayan kullanıcıya montaj ve keşif mesajı; satın alan kullanıcıya ürün ömrüne göre yenileme ve yedek parça hatırlatması", "Retargeting: installation and survey message to the user who viewed but did not buy; renewal and spare-part reminder to the buyer based on product lifetime"),
        ("at", "Servis süreci: \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\" önerileri; servis sayfasında ücret, randevu ve en yakın servis bilgisinin görünür olması fayda sağlayabilir", "Service process: suggestions such as \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\"; making fee, appointment and nearest service information visible on the service page can help")]),
 kaynak("vitra.com.tr ürün, hizmet ve kategori sayfaları (29.09.2026) · Google Keyword Planner, Search Console, Autocomplete · Trendyol arama sonuçları", "vitra.com.tr product, service and category pages (29.09.2026) · Google Keyword Planner, Search Console, Autocomplete · Trendyol search results", "D13", "D1", "D2", "D3", "D15", "D5"),
)
