# -*- coding: utf-8 -*-
"""Bolum: Kanal rolleri, etkilesim modeli, set ve tamamlayici urun, satis sonrasi."""
from ortak import *
from rapor_parca1 import T
from b_talep import kat
NI = A["niyet"]; GS = A["gsc_sorgu_niyet"]; AU = A["auto"]
KANAL = tablo([th("Kanal", "Channel", "Satış kanalı.", "Sales channel."),
               th("Bugünkü rol", "Current role", "Bu çalışmadaki gözlemlere dayalı mevcut konum; VitrA'nın panel verisiyle doğrulanacaktır.", "Current position based on the observations in this study; to be verified with VitrA's panel data."),
               th("Önerilen rol", "Proposed role", "Kanalın büyüme planında üstlenebileceği rol.", "The role the channel can take in the growth plan."),
               th("Öne çıkarılabilecek ürün grubu", "Product group to feature", "Talep ve ihtiyaç verisine göre kanalda öne çıkarılabilecek grup.", "Group that can be featured in the channel according to demand and need data.")],
              [[x("vitra.com.tr", "vitra.com.tr"), x("Marka ve kategori aramalarının vardığı bilgi ve satın alma noktası; organik tıkların %s'i kategori sayfalarına gelmektedir" % yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())), "The information and purchase point where brand and category searches arrive; %s of organic clicks land on category pages" % (yzd(100 * A["gsc_tur"]["kategori"][0] / sum(v[0] for v in A["gsc_tur"].values())).replace("%", "") + "%")),
                x("Tam katalog, set kurgusu, yedek parça ve montaj hizmetinin tek adresi; yüksek sepetli ürünlerde danışmanlık ve geri arama", "The single address for the full catalogue, set design, spare parts and installation service; consultation and call-back for high-basket products"),
                x("Gömme rezervuar setleri, akıllı klozet, banyo mobilyası setleri, yedek parça", "Concealed cistern sets, smart WC, bathroom furniture sets, spare parts")],
               [x("Trendyol", "Trendyol"), x("Kategoride en yüksek trafikli pazaryeri (tahmini aylık %s organik ziyaret); fiyat ve kampanya odaklı karşılaştırma" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com")), "The highest-traffic marketplace in the category (estimated %s monthly organic visits); price and campaign-led comparison" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "trendyol.com"))),
                x("Giriş fiyatlı ve hızlı karar ürünlerinde erişim kanalı; kupon ve taksit kampanyalarıyla hacim", "Reach channel for entry-priced and quick-decision products; volume through coupon and instalment campaigns"),
                x("Klozet kapağı, batarya, aksesuar, duş seti, iç takım", "Toilet seats, taps, accessories, shower sets, inner mechanisms")],
               [x("Hepsiburada", "Hepsiburada"), x("İkinci pazaryeri (tahmini aylık %s organik ziyaret); ev ve yapı kategorisinde güçlü, teslimat ve taksit vurgulu" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com")), "The second marketplace (estimated %s monthly organic visits); strong in home and construction, delivery and instalment led" % k(next(b[4] for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "hepsiburada.com"))),
                x("Orta segment ve büyük hacimli ürünlerde taksit ve teslimat vaadiyle ikinci erişim kanalı", "Second reach channel for mid-segment and bulky products with instalment and delivery promise"),
                x("Klozet takımı, banyo dolabı, duşakabin, küvet", "WC sets, bathroom cabinets, shower enclosures, bathtubs")],
               [x("Yapı market (Koçtaş, Bauhaus, Tekzen)", "DIY retailers (Koçtaş, Bauhaus, Tekzen)"), x("Kategori aramalarında VitrA ile en çok ortak kelimeye sahip kanal; \"vitra klozet fiyatları koçtaş\" gibi aramalar mevcut", "The channel sharing the most keywords with VitrA in category searches; searches such as \"vitra klozet fiyatları koçtaş\" exist"),
                x("Tamamlayıcı ürün ve montaj hizmetiyle birlikte satış; VitrA'nın üretmediği düşük fiyatlı tamamlayıcı ürünlerde kendi kanalına satıcı modeli", "Sales together with complementary products and installation service; a seller model in the own channel for low-priced complementary products VitrA does not make"),
                x("Klozet, lavabo, batarya, montaj malzemesi", "WCs, washbasins, taps, fitting materials")]])
def dr(d): return '<span class="badge %s">%s</span>' % ({"Var": "b-var", "Kısmi": "b-kis", "Yok": "b-yok"}[d], x(d, {"Var": "Available", "Kısmi": "Partial", "Yok": "Not available"}[d]))
ETK = tablo([th("Bileşen", "Component", "Hacimli ve ölçüye bağlı üründe karar öncesi belirsizliği azaltan unsur.", "Element that reduces pre-decision uncertainty for bulky and dimension-dependent products."),
             th("VitrA'da bugün", "At VitrA today", "vitra.com.tr üzerindeki mevcut uygulama (29.09.2026).", "Current implementation on vitra.com.tr (29.09.2026)."),
             th("Durum", "Status", "Var, Kısmi (sınırlı kapsam), Yok.", "Available, Partial (limited scope), Not available."),
             th("Geliştirme alanı", "Area for development", "Mevcut yapının üzerine eklenebilecek adım.", "Step that could be added on top of the current structure.")],
    [[x("Fiyat, taksit ve teslim netliği", "Price, instalment and delivery clarity"), x("Ürün sayfasında fiyat, sepette %10 indirim, taksit tablosu, tahmini kargoya teslim tarihi, 30 gün ücretsiz iade", "Price on the product page, 10% basket discount, instalment table, estimated handover-to-carrier date, 30-day free returns"), dr("Var"),
      x("Taksit mesajının tekleştirilmesi (6 ay vade farksız ve 9 taksit); hacimli üründe kargoya teslim yerine eve teslim aralığının gösterilmesi", "Unifying the instalment message (6 months interest-free and 9 instalments); showing the home delivery window instead of the carrier handover date for bulky products")],
     [x("Danışmanlık ve geri arama", "Consultation and call-back"), x("Banyo Asistanı: ihtiyaç, fotoğraf, telefon / mağaza / görüntülü görüşme, randevu, WhatsApp teyidi", "Bathroom Assistant: need, photo, phone / store / video call, appointment, WhatsApp confirmation"), dr("Var"),
      x("Mağaza seçeneğinin 5 VitrA mağazasından bayi ağına genişletilmesi; akış adımlarının GA4'te ölçülmesi (talep R9)", "Extending the store option from 5 VitrA stores to the dealer network; measuring the flow steps in GA4 (request R9)")],
     [x("Keşif", "Site survey"), x("Keşif hizmeti 1.400 TL; ölçü ve tesisat uygunluğu, 2 banyoya kadar", "Site survey 1,400 TL; dimension and plumbing suitability, up to 2 bathrooms"), dr("Kısmi"),
      x("Duşakabin, küvet ve mobilya sayfalarından keşfe bağlantı; keşif bedelinin ürün alımında düşülmesi (Home Depot örneği)", "Linking to the survey from shower enclosure, bathtub and furniture pages; deducting the survey fee from the product purchase (as at Home Depot)")],
     [x("Montaj", "Installation"), x("11 montaj kalemi, ürün sayfasında montaj seçeneği, söküm ve imha dahil, 1 yıl garanti; 92 üründe ücretsiz montaj", "11 installation items, installation option on the product page, removal and disposal included, 1-year warranty; free installation on 92 products"), dr("Kısmi"),
      x("Duşakabin, küvet ve duş teknesi için montaj kalemi; il bazında hizmet kapsamının ürün sayfasında gösterilmesi", "An installation item for shower enclosures, bathtubs and shower trays; showing service coverage by province on the product page")],
     [x("Lokal bayi ve stok", "Local dealer and stock"), x("Servisler ve satış noktaları sayfası 16 ayda %s tık almış" % bin(36458), "The services and sales points page received %s clicks in 16 months" % f"{36458:,}"), dr("Kısmi"),
      x("Siparişin kullanıcıya yakın bayi stoğundan karşılanması ve bayide teslim seçeneği (VitrA'dan bilgi bekleniyor)", "Fulfilling orders from stock at a dealer near the user and a pick-up at dealer option (information awaited from VitrA)")],
     [x("Eksik ürün kontrolü", "Missing item check"), x("\"Birlikte Satın Alınanlar\" alanında iç takım, klozet kapağı, ara musluk; uyumlu rezervuar kodu ürün sayfasında", "\"Frequently bought together\" shows inner mechanism, WC seat, stop valve; compatible cistern code on the product page"), dr("Var"),
      x("Montaj parçalarının (esnek hortum, taharet musluğu, bağlantı borusu) tek pakette sunulması; Trendyol'da İDEVİT seti örneği", "Offering fitting parts (flexible hose, bidet valve, connection pipe) in a single pack; the İDEVİT set on Trendyol as an example")],
     [x("Yedek parça ve satış sonrası", "Spare parts and after-sales"), x("Parçalar tekil ürün olarak satılıyor; yedek parça kategorisi ve parça bulucu yok", "Parts are sold as single products; no spare-parts category or part finder"), dr("Yok"),
      x("Ürün koduna göre parça bulucu ve yedek parça kategorisi (Bölüm [[b:yeni]] ve [[b:benchmark]])", "A part finder by product code and a spare-parts category (Sections [[b:yeni]] and [[b:benchmark]])")]], "uzun")
tam = NI["Tamir ve bakım"]; mon = NI["Montaj"]
TAMAMLAYICI = tablo([th("Ürün grubu", "Product group", "VitrA'nın üretmediği veya sınırlı ürettiği, kategori satın almasıyla birlikte ihtiyaç duyulan grup.", "Group VitrA does not make or makes in limited range, needed together with the category purchase."),
                     th("Talep sinyali", "Demand signal", "Kelime araştırması, autocomplete veya Search Console'daki ifade.", "Phrase in keyword research, autocomplete or Search Console."),
                     th("Bugün nerede satılıyor?", "Where is it sold today?", "Kullanıcının bu ürünü bulduğu kanal; rakip site incelemesine göre.", "Channel where the user finds this product; according to the competitor site review."),
                     th("Model önerisi", "Proposed model", "vitra.com.tr için değerlendirilebilecek satış modeli.", "Sales model that can be considered for vitra.com.tr.")],
                    [[x("Montaj malzemesi ve bağlantı parçaları", "Fitting materials and connection parts"), x("\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\"", "\"klozet montaj aparatı\", \"klozet bağlantı borusu\", \"klozet montaj vidası\""), x("Yapı market, nalbur, pazaryeri", "DIY retailer, hardware store, marketplace"), x("Üçüncü taraf satıcı veya kendi stok; klozet sepetine otomatik öneri", "Third-party seller or own stock; automatic suggestion in the WC basket")],
                     [x("Taharet musluğu ve ara musluk", "Bidet spray and stop valve"), x("\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\"", "\"klozet taharet musluğu\", \"artema taharet musluğu\", \"filtreli ara musluk\""), x("Artema kataloğu, yapı market", "Artema catalogue, DIY retailer"), x("Artema ürünleriyle klozet seti; tek sepet", "WC set with Artema products; single basket")],
                     [x("Banyo tekstili ve küçük aksesuar", "Bathroom textiles and small accessories"), x("Aksesuar setleri talebi daralmakta (%s); tek parça aksesuar aramaları sürmekte" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"]), "Accessory set demand contracting (%s); single-item accessory searches continue" % yz(A["k2"]["Banyo Aksesuarları|Banyo Aksesuar Setleri"]["yoy"])), x("Pazaryeri, ev tekstili markaları", "Marketplace, home textile brands"), x("Seçili üçüncü taraf markalarla sepet tamamlama", "Basket completion with selected third-party brands")],
                     [x("Su ısıtıcı, havlupan, aydınlatma", "Water heater, towel radiator, lighting"), x("\"havlupan\" kategori sayfası organik tık almakta (c-havlupanlar); banyo yenilemesinde birlikte alınan ürünler", "The \"havlupan\" category page receives organic clicks (c-havlupanlar); products bought together in a bathroom renovation"), x("Yapı market, pazaryeri", "DIY retailer, marketplace"), x("Yenileme paketi içinde üçüncü taraf ürün; VitrA ürünü sepetin merkezinde", "Third-party product within a renovation package; the VitrA product at the centre of the basket")],
                     [x("Yedek parça (iç takım, şamandıra, menteşe, conta)", "Spare parts (inner mechanism, float valve, hinge, gasket)"), x("Tamir ve bakım aramaları aylık %s; autocomplete önerilerinin %s'i" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values()))), "Repair and maintenance searches %s per month; %s of autocomplete suggestions" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values())).replace("%", "") + "%")), x("Yetkili servis, nalbur, pazaryeri üçüncü taraf satıcılar", "Authorised service, hardware store, third-party marketplace sellers"), x("Ürün koduna göre yedek parça sayfası; montaj videosu ile birlikte satış", "Spare-part page by product code; sale together with the installation video")]])
HTML = """
<p class="lede">%s</p>
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
""" % (
 x("Bu bölüm, talep ve davranış verisinin kanal rollerine ve etkileşim modeline nasıl çevrilebileceğini ele almaktadır. VitrA'nın bugün sunduğu uygulamalar (Banyo Asistanı, montaj ve keşif hizmetleri, ürün sayfası bilgileri) incelenmiş; öneriler bu yapının üzerine kurulmuştur. Pazaryeri ve GA4 verisi geldiğinde güncellenecektir.",
   "This section addresses how demand and behaviour data can be translated into channel roles and an engagement model. The applications VitrA offers today (Bathroom Assistant, installation and survey services, product page information) have been examined and the proposals built on top of this structure. It will be updated when marketplace and GA4 data arrive."),
 x("Kanal rolleri", "Channel roles"), KANAL,
 insight("Üç kanal aynı ürünü aynı fiyatla listelediğinde kullanıcı en tanıdık ve en hızlı kanalı seçmekte, marka sitesi karşılaştırma listesinin dışında kalmaktadır. Rol ayrımı, her kanalın kendi güçlü olduğu ürün grubu ve hizmetle konumlanmasını sağlar: pazaryerinde hızlı karar ürünleri ve kampanya, marka sitesinde set, yedek parça, montaj ve danışmanlık. Kanallar arası fiyat tutarlılığının her durumda korunması önem taşımaktadır; aksi halde marka sitesi \"pahalı kanal\" olarak algılanmaktadır.",
         "When three channels list the same product at the same price the user picks the most familiar and fastest channel, and the brand site drops off the comparison list. Role separation lets each channel position itself with the product group and service it is strong in: quick-decision products and campaigns on the marketplace; sets, spare parts, installation and consultation on the brand site. Maintaining price consistency across channels in every case is important; otherwise the brand site is perceived as the \"expensive channel\"."),
 x("Hacimli ve ölçüye bağlı ürünlerde etkileşim modeli", "Engagement model for bulky and dimension-dependent products"),
 ETK,
 insight("Etkileşim modelinin bileşenlerinin çoğu VitrA'da bugün mevcuttur; geliştirme alanı yeni bir araç kurmaktan çok mevcut parçaları birbirine bağlamaktadır: ölçüye bağlı ürün sayfasından keşfe, keşiften montaja, Banyo Asistanı'ndan bayi ağına. Bu bağlantıların etkisi ancak lead olayları ölçüldüğünde görülebilir; GA4 talebinde Banyo Asistanı adımları ve montaj / keşif hizmetlerinin ürünle birlikte satın alınma oranı ayrı başlık olarak yer almaktadır.",
         "Most components of the engagement model exist at VitrA today; the area for development is connecting the existing pieces rather than building a new tool: from the dimension-dependent product page to the survey, from the survey to installation, from the Bathroom Assistant to the dealer network. The effect of these connections can only be seen once lead events are measured; the GA4 request includes the Bathroom Assistant steps and the attach rate of installation / survey services as separate items.", "D13"),
 x("Tamamlayıcı ürün kurgusu", "Complementary product design"),
 TAMAMLAYICI,
 insight("Kullanıcı klozet alırken iç takımı, bağlantı borusunu ve montaj aparatını da aramakta; bunları çoğunlukla yapı marketten tamamlamaktadır. VitrA'nın üretmediği, 4-5 bin TL altındaki tamamlayıcı ürünlerin vitra.com.tr üzerinde üçüncü taraf satıcı modeliyle sunulması, sepetin bölünmesini engelleyebilir ve marka sitesini \"tek durak\" hâline getirebilir. İlk adım olarak montaj malzemesi ve yedek parça gruplarında test edilebilir.",
         "When buying a WC the user also searches for the inner mechanism, connection pipe and fitting kit, and mostly completes these at a DIY store. Offering the complementary products VitrA does not make, priced below 4-5 thousand TL, on vitra.com.tr through a third-party seller model can prevent the basket from splitting and make the brand site the \"one stop\". It can be tested first in the fitting material and spare-part groups."),
 x("Satış sonrası döngü", "The after-sales loop"),
 marks([("up", "Yedek parça kategorisi ve parça bulucu: tamir ve bakım aramaları aylık %s, autocomplete önerilerinin %s'i bu temada" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values()))), "Spare-parts category and part finder: repair and maintenance searches %s per month, %s of autocomplete suggestions are in this theme" % (k(tam["a26"]), yzd(100 * A["auto_tema"]["Tamir ve bakım"] / sum(A["auto_tema"].values())).replace("%", "") + "%")),
        ("up", "Satış sonrası memnuniyet ölçümü ve tekrar sipariş takibi: olumsuz deneyim yaşayan müşterinin tekrar sipariş oranı, Şikayetvar kayıtlarıyla eşleştirilerek izlenebilir", "After-sales satisfaction measurement and repeat-order tracking: the repeat-order rate of customers with a poor experience can be tracked by matching with Şikayetvar records"),
        ("up", "Retargeting: ürünü inceleyip satın almayan kullanıcıya montaj ve keşif mesajı; satın alan kullanıcıya 5 yıl sonra yenileme ve yedek parça hatırlatması", "Retargeting: installation and survey message to the user who viewed but did not buy; renewal and spare-part reminder to the buyer five years later"),
        ("at", "Servis süreci: \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\" önerileri; servis sayfasında ücret, randevu ve en yakın servis bilgisinin görünür olması fayda sağlayabilir", "Service process: suggestions such as \"vitra servis ücreti\", \"vitra servis randevu\", \"vitra servis en yakın\"; making fee, appointment and nearest service information visible on the service page can help")]),
 kaynak("vitra.com.tr ürün, hizmet ve kategori sayfaları (29.09.2026) · Google Keyword Planner, Search Console, Autocomplete · Trendyol arama sonuçları", "vitra.com.tr product, service and category pages (29.09.2026) · Google Keyword Planner, Search Console, Autocomplete · Trendyol search results", "D13", "D1", "D2", "D3", "D15"),
)
