# -*- coding: utf-8 -*-
"""Bolum: Ozet - KPI, kritik tespit, one cikan bulgular."""
from ortak import *
K1 = A["k1"]; TOP = A["toplam"]; NI = A["niyet"]; GT = A["gsc_tur"]; GS = A["gsc_sorgu_niyet"]; AT = A["auto_tema"]
toplam_yoy = (TOP["a26"] / TOP["a25"] - 1) * 100; kloz = A["k2"]["Vitrifiyeler|Klozetler"]["yoy"]; bm = K1["Banyo Mobilyaları"]["yoy"]
ttot = sum(v[0] for v in GT.values()); ktot = sum(v[0] for v in A["gsc_kat"].values())
bm_tik = 100 * sum(v[0] for kk, v in A["gsc_kat"].items() if kk.startswith("Banyo Mobilyaları")) / ktot; bm_talep = 100 * K1["Banyo Mobilyaları"]["a26"] / TOP["a26"]
tam_pay = 100 * AT["Tamir ve bakım"] / sum(AT.values())
vit = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "vitra.com.tr"); koc = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "koctas.com.tr")
son12 = sum(A["gsc_ay_toplam"][m][0] for m in A["gsc_aylar"][-13:-1])
TM = YK["tema"]; SEG = SB["seg"]; OB = SB["oz_bm"]; OSS = SB["oz_ssg"]
def oz(o, ad): return next(z for z in o["ozellik"] if z["ad"] == ad)
yed = TM["yedek"]["v12"] + TM["ic_takim"]["v12"]
KPI = "".join([
 kpi_kart(yz(toplam_yoy), "Kategori arama talebi · Oca-Ağu 2026 / 2025, 2.420 kelime", "Category search demand · Jan-Aug 2026 / 2025, 2,420 keywords", "dn"),
 kpi_kart(yz(SEG["SSG"]["uc"]), "SSG talebi · 3 yıllık değişim; BM %s" % yz(SEG["BM"]["uc"]), "SSG demand · 3-year change; BM %s" % yz(SEG["BM"]["uc"]), "up"),
 kpi_kart(k(yed), "Aylık iç takım ve yedek parça araması · sitede yedek parça kategorisi yok", "Monthly inner-mechanism and spare-part searches · no spare-parts category on the site", "hi"),
 kpi_kart(yzd(oz(OB, "Perakendeci / pazaryeri")["pay"]), "BM aramalarında perakendeci adı geçen pay · VitrA %s" % yzd(oz(OB, "VitrA")["pay"]), "Share of BM searches naming a retailer · VitrA %s" % (yzd(oz(OB, "VitrA")["pay"]).replace("%", "") + "%"), "hi"),
])
KRITIK = marks([
 ("at", "Talep daralması makro kaynaklıdır ve segmentler ayrışmaktadır: SSG üç yılda %s ile yatay, BM %s; ertelenen yenileme talebi 2026 Q4 - 2027 Q1'de geri gelebilir" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"])), "The demand contraction is macro-driven and the segments diverge: SSG flat at %s over three years, BM %s; postponed renovation demand may return in 2026 Q4 - 2027 Q1" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"]))),
 ("at", "Kullanıcı VitrA'dan yedek parça bekliyor: iç takım ve parça aramaları aylık %s, eski yedek parça sayfası bugün tek ürünlü kategoriye yönleniyor" % k(yed), "Users expect spare parts from VitrA: inner-mechanism and part searches total %s per month, and the old spare-parts page now redirects to a one-product category" % k(yed)),
 ("at", "Ürün + hizmet modelinin parçaları mevcut (11 montaj kalemi, keşif, Banyo Asistanı, ücretsiz montajlı mobilya), ancak tek bir teklif altında birleşmiyor; duşakabin gibi ölçüye bağlı ürünlerde montaj ve keşif seçeneği görünmüyor", "The pieces of a product + service model exist (11 installation items, survey, Bathroom Assistant, free-installation furniture) but are not combined into a single offer; installation and survey options are not visible on dimension-dependent products such as shower enclosures"),
 ("up", "Gam dışında VitrA'ya yakın fırsatlar: granit ve çelik evye (%s), arıtmalı batarya, erişilebilir ve çocuk banyosu, havlupan ve ledli ayna derinliği" % k(TM["evye"]["v12"]), "Out-of-range opportunities close to VitrA: granite and steel sinks (%s), purifier taps, accessible and children's bathrooms, depth in towel radiators and LED mirrors" % k(TM["evye"]["v12"])),
 ("at", "Pazaryerinde fiyat ve satıcı kontrolü sınırlıdır: Hepsiburada'da VitrA ürünlerinin %69'u üçüncü taraf satıcıdan sunulmakta, pazaryerindeki VitrA ürünleri kategorinin çok satan ürünlerinden medyanda <b>2 ila 6 kat</b> daha pahalıdır (klozette yaklaşık 2 kat, banyo dolabında 6 kata kadar); banyo mobilyasında fark fiyatla değil <b>set, montaj ve garanti bütünlüğüyle</b> kurulabilir", "Price and seller control on marketplaces is limited: 69% of VitrA products on Hepsiburada are offered by third-party sellers and VitrA products on marketplaces are <b>2 to 6 times</b> more expensive at the median than the category's best sellers (about 2 times in WCs, up to 6 times in bathroom cabinets); in bathroom furniture the difference can be built through <b>set, installation and warranty integrity</b> rather than price"),
 ("at", "Satış sonrası deneyim şikayetlerin ağırlık merkezidir: Şikayetvar'daki 581 VitrA şikayetinin %76,9'u servis, yedek parça, montaj veya iletişim temalarından en az birini taşımakta; marka puanı 18/100, çözüm oranı son yılda %18; yedek parça teması altı ayda %8,1'den %17,8'e çıkmıştır", "The after-sales experience is the centre of gravity of complaints: 76.9% of the 581 VitrA complaints on Şikayetvar carry at least one of the service, spare part, installation or contact themes; brand score 18/100, resolution rate 18% in the last year; the spare-part theme rose from 8.1% to 17.8% within six months"),
 ("at", "Aynı VitrA ürünü pazaryerinde resmi mağazadan daha ucuz bulunmaktadır: 29 üründen 19'unda en ucuz kanal vitra.com.tr dışında (fark medyanı %24,7, armatürde %29,8); Google Shopping satıcı listelerinde resmi mağaza en düşük fiyatın medyan %37 üzerinde ve kategori kelimelerinin 15'inde hiç görünmemektedir", "The same VitrA product is found cheaper on marketplaces than at the official store: for 19 of 29 products the cheapest channel is outside vitra.com.tr (median gap 24.7%, taps 29.8%); in Google Shopping seller lists the official store is a median 37% above the lowest price and does not appear at all for 15 category keywords"),
 ("at", "vitra.com.tr kategori sayfalarında stok ve fiyat gösterimi geliştirme alanıdır: 55 sayfadaki 2.258 varyant kartının %71,1'i stoklu süzgeci dışında, 13 alt kategoride stoklu ürün yok, kartların %89,9'unda \"Sepette %N indirim\" etiketi; aynı model kodunda pazaryeri fiyatı liste fiyatının medyan %14,4 altında ve sepet fiyatına yakın seyrediyor", "Stock and price display on vitra.com.tr category pages is an area for improvement: 71.1% of the 2,258 variant cards on 55 pages fall outside the in-stock filter, 13 sub-categories have no in-stock product, 89.9% of cards carry an \"N% off in basket\" label; for the same model code the marketplace price runs a median 14.4% below the list price and close to the basket price"),
 ("at", "Trendyol resmi mağazasında net adet dört çeyrekte <b>4 katın üzerine</b> çıktı, ancak ortalama net fiyat 3.539 TL'den 1.688 TL'ye indi: büyüme düşük fiyatlı tamamlayıcıdan geliyor. Mağaza cirosunun büyük bölümünü üreten mobilya, batarya, duş ve eviye kategorilerinin Eylül 2026 çok satan ve ciro listelerinde resmi mağaza yok; listelerdeki VitrA markalı satırların %73'si üçüncü taraf satıcıda. İade nedenlerinin %39,6'i ölçü ve uyum", "In the official Trendyol store net units rose <b>more than 4 times</b> in four quarters, but the average net price fell from 3,539 TL to 1,688 TL: growth comes from low-priced complements. The official store is absent from the September 2026 best-seller and revenue lists of furniture, taps, shower and sink, which produce much of the store's revenue; 73% of VitrA-branded rows in the lists are at third-party sellers. 39.6% of return reasons are size and fit"),
 ("at", "Google'da ürün ve kategori aramalarının ön sıraları pazaryerlerindedir (Trendyol 109 kelimenin 86'sında ilk 10'da); VitrA SSG'de güçlüdür, armatür, bitişik ürün ve tamir içeriğinde ise ilk 10 dışında kalmakta, en çok izlenen 14 YouTube tamir ve kurulum konusunun hiçbirinde VitrA kanal videosu bulunmamaktadır", "The top positions of product and category searches on Google belong to marketplaces (Trendyol in the top 10 for 86 of 109 keywords); VitrA is strong in SSG but outside the top 10 in taps, adjacent products and repair content, and none of the 14 most-viewed YouTube repair and installation topics has a VitrA channel video"),
])
FN = '<div class="fnotes">%s</div>' % "".join([
 fnote(1, "SSG dayanıklı, BM daralıyor", "SSG resilient, BM contracting",
       [("SSG üç yılda <b>%s</b>; klozet <b>%s</b>, akıllı klozet seti <b>%s</b>, bide <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"])), "SSG <b>%s</b> over three years; WCs <b>%s</b>, smart WC sets <b>%s</b>, bidets <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"]))),
        ("BM üç yılda <b>%s</b>; yalnız tezgah (<b>%s</b>) ve çamaşır makinesi dolabı (<b>%s</b>) talebini koruyor" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"])), "BM <b>%s</b> over three years; only countertops (<b>%s</b>) and washing machine cabinets (<b>%s</b>) hold demand" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"]))),
        ("Oca-Ağu 2026'da toplam talep <b>%s</b>; tasarım ve model aramaları <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])), "Total demand <b>%s</b> in Jan-Aug 2026; design and model searches <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])))]),
 fnote(2, "Makro ortam: harcama nominal, niyet yükselişte", "Macro environment: nominal spending, rising intent",
       [("Mobilya ve dekorasyon kart harcaması <b>%s</b> nominal; reel kartlı ödeme endeksi <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100)), "Furniture and decoration card spending <b>%s</b> nominal; real card payment index <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100))),
        ("Tüketici güveni Eylül 2026'da <b>%s</b>; konut tamiratına harcama ihtimali <b>%s</b>" % (("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"]).replace(".", ","), ("%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"]).replace(".", ",")), "Consumer confidence <b>%s</b> in September 2026; probability of spending on home repairs <b>%s</b>" % ("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"], "%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"])),
        ("Konut satışları Oca-Ağu 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100), "House sales Jan-Aug 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100))]),
 fnote(3, "Kullanıcı ne arıyor?", "What does the user search for?",
       [("SSG aramalarının <b>%s</b>'i fiyat, <b>%s</b>'i tamir ve parça; rakip marka adı (<b>%s</b>) VitrA adından (<b>%s</b>) fazla" % (yzd(oz(OSS, "Fiyat")["pay"]), yzd(oz(OSS, "Tamir / parça")["pay"]), yzd(oz(OSS, "Rakip marka")["pay"]), yzd(oz(OSS, "VitrA")["pay"])), "<b>%s</b> of SSG searches carry price, <b>%s</b> repair and parts; competitor brand names (<b>%s</b>) exceed VitrA (<b>%s</b>)" % tuple(yzd(v).replace("%", "") + "%" for v in (oz(OSS, "Fiyat")["pay"], oz(OSS, "Tamir / parça")["pay"], oz(OSS, "Rakip marka")["pay"], oz(OSS, "VitrA")["pay"]))),
        ("BM'de PVC ve suya dayanıklı gövde <b>%s</b>, küçük banyo <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"])), "In BM, PVC and water-resistant bodies <b>%s</b>, small bathroom <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"]))),
        ("Autocomplete önerilerinin <b>%s</b>'i tamir ve yedek parça; YouTube'da tesisatçı kanalları görünmelerin <b>%%43,7</b>'sini alıyor" % yzd(tam_pay), "<b>%s</b> of autocomplete suggestions are repair and spare parts; on YouTube plumber channels take <b>43.7%%</b> of appearances" % (yzd(tam_pay).replace("%", "") + "%"))]),
 fnote(4, "Katalog boşlukları ve yakın fırsatlar", "Catalogue gaps and nearby opportunities",
       [("Hela taşı <b>%s</b> arama / 1 ürün; havlupan <b>%s</b> / 2 ürün" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"])), "Squat toilet <b>%s</b> searches / 1 product; towel radiators <b>%s</b> / 2 products" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"]))),
        ("Evye <b>%s</b> (VitrA yalnız seramik), arıtmalı batarya üç yılda <b>%s</b>, erişilebilir ürünler YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"])), "Sinks <b>%s</b> (VitrA ceramic only), purifier taps <b>%s</b> over three years, accessible products YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"]))),
        ("Gam dışı büyük hacimler (arıtma, şofben, tekstil) yalnız tadilat paketinde iş ortağı ürünü olarak uygun", "Large out-of-range volumes (purifiers, water heaters, textiles) fit only as partner products in a renovation package")]),
 fnote(5, "Ürün + hizmet: parçalar var, paket yok", "Product + service: the pieces exist, the package does not",
       [("11 montaj kalemi (klozet 2.750 TL, BM seti 4.000 TL), keşif 1.400 TL, 92 üründe ücretsiz montaj", "11 installation items (WC 2,750 TL, BM set 4,000 TL), survey 1,400 TL, free installation on 92 products"),
        ("Banyo Asistanı: 4 adım, telefon / mağaza / görüntülü görüşme, 5 VitrA mağazası", "Bathroom Assistant: 4 steps, phone / store / video call, 5 VitrA stores"),
        ("Koçtaş, BAUHAUS ve Kohler banyoyu \"proje\" olarak satıyor; VitrA'da tadilat girişi ve planlayıcı yok", "Koçtaş, BAUHAUS and Kohler sell the bathroom as a \"project\"; VitrA has no renovation entry page or planner")]),
 fnote(7, "Satış sonrası: şikayet, garanti ve yedek parça", "After-sales: complaints, warranty and spare parts",
       [("Şikayetvar puanı VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, Geberit 78; çözüm oranı son yılda <b>%18</b>", "Şikayetvar score VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, Geberit 78; resolution rate <b>18%</b> in the last year"),
        ("Yedek parça teması <b>%8,1 → %17,8</b>, montaj ve usta <b>%27,0 → %48,5</b> (altı aylık dönemler); servis ücreti ve garanti reddi 75'er şikayette", "Spare-part theme <b>8.1% → 17.8%</b>, installation and installer <b>27.0% → 48.5%</b> (six-month periods); service fee and warranty refusal in 75 complaints each"),
        ("Ürün sayfalarında garanti süresi ve yedek parça girişi yok; E.C.A. 20 yıl, Grohe 10 yıla kadar garanti ve 48 saatte parça yazıyor", "No warranty period or spare-part entry on product pages; E.C.A. states 20 years, Grohe up to 10 years and parts within 48 hours")]),
 fnote(8, "Fiyat ve kanal politikası", "Price and channel policy",
       [("29 VitrA ürününün <b>19</b>'unda en ucuz kanal pazaryeri; fark medyanı <b>%24,7</b>, sepet indirimleriyle <b>%15,4</b>; asma klozet ve mobilyada fark yok", "For <b>19</b> of 29 VitrA products the cheapest channel is a marketplace; median gap <b>24.7%</b>, <b>15.4%</b> with basket discounts; no gap in wall-hung WCs and furniture"),
        ("Google Shopping'de vitra.com.tr mağazası listelemelerin <b>%0,7</b>'si; VitrA ve Artema ilanlarının <b>%44</b>'ü bağımsız mağazalardan", "On Google Shopping the vitra.com.tr store is <b>0.7%</b> of listings; <b>44%</b> of VitrA and Artema listings come from independent stores"),
        ("Aynı model kodunda <b>200</b> eşleşmede pazaryeri fiyatı liste fiyatının medyan <b>%14,4</b> altında, sepet fiyatına yakın; üçüncü taraf satıcılarda liste fiyatının <b>2-3 katına</b> çıkan ilanlar; 55 kategori sayfasındaki kartların <b>%71,1</b>'i stoklu süzgeci dışında", "For the same model code, in <b>200</b> matches the marketplace price is a median <b>14.4%</b> below the list price and close to the basket price; third-party sellers list at <b>2-3 times</b> the list price; <b>71.1%</b> of cards on 55 category pages fall outside the in-stock filter"),
        ("Taksit mesajı üç yüzeyde farklı (6 / 9 / 12); alışveriş kredisi yalnız pazaryerlerinde; Banyoline İstanbul'da VitrA serilerine ücretsiz montaj veriyor", "Instalment message differs on three surfaces (6 / 9 / 12); consumer credit only on marketplaces; Banyoline gives free installation for VitrA series in Istanbul")]),
 fnote(6, "Rekabet: pazaryeri, arama sonucu ve marka siteleri", "Competition: marketplaces, search results and brand sites",
       [("Google'da Trendyol 109 kelimenin <b>86</b>'sında ilk 10'da; VitrA <b>54</b> kelimede ilk 10'da, <b>19</b>'unda 1. sırada", "On Google, Trendyol is in the top 10 for <b>86</b> of 109 keywords; VitrA is in the top 10 for <b>54</b> and first for <b>19</b>"),
        ("Trendyol banyo kategorileri aylık <b>332K</b> organik ziyaret alıyor; VitrA'nın Trendyol marka sayfası <b>9.174</b> ile E.C.A. (7.771) ve Artema'nın (3.568) önünde", "Trendyol bathroom categories receive <b>332K</b> organic visits a month; VitrA's Trendyol brand page, at <b>9,174</b>, is ahead of E.C.A. (7,771) and Artema (3,568)"),
        ("Marka siteleri içinde VitrA organik lider (<b>%s</b>); karoda Kale VitrA'nın yaklaşık <b>2 katı</b> organik trafik alıyor; yapı kimyasalı ve mutfak tezgahında rakipler önde" % k(vit[4]), "VitrA is the organic leader among brand sites (<b>%s</b>); Kale gets about <b>2 times</b> VitrA's organic traffic in tiles; competitors also lead in building chemicals and kitchen countertops" % k(vit[4]))]),
])
HTML = """
<div class="kpis">%s</div>
%s
<h3>%s</h3>
%s
""" % (
  KPI,
 box("KRİTİK TESPİT", "KEY FINDINGS", KRITIK),
 x("Öne çıkan bulgular", "Highlights"), FN,
)
