# -*- coding: utf-8 -*-
"""Bolum: Ozet - KPI, kritik tespit, one cikan bulgular."""
from ortak import *
K1 = A["k1"]; TOP = A["toplam"]; NI = A["niyet"]; GT = A["gsc_tur"]; GS = A["gsc_sorgu_niyet"]; AT = A["auto_tema"]
toplam_yoy = (TOP["a26"] / TOP["a25"] - 1) * 100; kloz = A["k2"]["Vitrifiyeler|Klozetler"]["yoy"]; bm = K1["Banyo Mobilyaları"]["yoy"]
ttot = sum(v[0] for v in GT.values()); ktot = sum(v[0] for v in A["gsc_kat"].values())
bm_tik = 100 * sum(v[0] for kk, v in A["gsc_kat"].items() if kk.startswith("Banyo Mobilyaları")) / ktot; bm_talep = 100 * K1["Banyo Mobilyaları"]["a26"] / TOP["a26"]
from b_marka import AT as _AT
tam_pay = 100 * _AT["Tamir ve bakım"] / sum(_AT.values())
vit = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "vitra.com.tr"); koc = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "koctas.com.tr")
son12 = sum(A["gsc_ay_toplam"][m][0] for m in A["gsc_aylar"][-13:-1])
TM = YK["tema"]; SEG = SB["seg"]; OB = SB["oz_bm"]; OSS = SB["oz_ssg"]
def oz(o, ad): return next(z for z in o["ozellik"] if z["ad"] == ad)
yed = TM["yedek"]["v12"] + TM["ic_takim"]["v12"]
KPI = "".join([
 kpi_kart(yz(toplam_yoy), "Kategori arama talebi · Oca-Ağu 2026 / 2025, 2.342 kelime", "Category search demand · Jan-Aug 2026 / 2025, 2,342 keywords", "dn"),
 kpi_kart(yz(SEG["SSG"]["uc"]), "SSG talebi · 3 yıllık değişim; BM %s" % yz(SEG["BM"]["uc"]), "SSG demand · 3-year change; BM %s" % yz(SEG["BM"]["uc"]), "up"),
 kpi_kart(k(yed), "Aylık iç takım ve yedek parça araması · sitede yedek parça kategorisi yok", "Monthly inner-mechanism and spare-part searches · no spare-parts category on the site", "hi"),
 kpi_kart(yzd(oz(OB, "Perakendeci / pazaryeri")["pay"]), "BM aramalarında perakendeci adı geçen pay · VitrA %s" % yzd(oz(OB, "VitrA")["pay"]), "Share of BM searches naming a retailer · VitrA %s" % (yzd(oz(OB, "VitrA")["pay"]).replace("%", "") + "%"), "hi"),
])
KRITIK = marks([
 ("at", "Talep daralması makro ortamla ilişkilendirilebilir ve segmentler ayrışmaktadır: SSG üç yılda %s ile yatay seyretmiş, BM %s gerilemiştir; ertelenen yenileme talebinin 2026 Q4 - 2027 Q1 döneminde geri gelebileceği değerlendirilebilir" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"])), "The demand contraction can be linked to the macro environment and the segments diverge: SSG was flat at %s over three years while BM fell %s; postponed renovation demand may return in 2026 Q4 - 2027 Q1" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"]))),
 ("at", "Yedek parça beklentisi öne çıkmaktadır: iç takım, şamandıra, menteşe, kartuş ve conta aramaları aylık %s seviyesindedir; eski yedek parça sayfası bugün tek ürünlü bir kategoriye yönlenmektedir" % k(yed), "Spare-part expectations stand out: searches for inner mechanisms, float valves, hinges, cartridges and gaskets total %s per month, and the old spare-parts page now redirects to a one-product category" % k(yed)),
 ("at", "Ürün + hizmet modelinin parçaları mevcuttur (11 montaj kalemi, keşif, Banyo Asistanı, ücretsiz montajlı mobilya), ancak tek bir teklif altında birleşmemektedir; duşakabin gibi ölçüye bağlı ürünlerde montaj ve keşif seçeneği görünmemektedir", "The pieces of a product + service model exist (11 installation items, survey, Bathroom Assistant, free-installation furniture) but are not combined into a single offer; installation and survey options are not visible on dimension-dependent products such as shower enclosures"),
 ("up", "Gam dışında VitrA'ya yakın fırsatlar bulunmaktadır: evye (%s; granit, çelik ve akıllı evye dahil), arıtmalı batarya, erişilebilir ve çocuk banyosu ile havlupan ve ledli aynada ürün derinliği" % k(TM["evye"]["v12"]), "Outside the current range there are opportunities close to VitrA: sinks (%s; granite, steel and smart sinks included), purifier taps, accessible and children's bathrooms, and product depth in towel radiators and LED mirrors" % k(TM["evye"]["v12"])),
 ("at", "Pazaryerinde fiyat ve satıcı kontrolü sınırlıdır: Hepsiburada'da VitrA ürünlerinde buybox'ın %69'u üçüncü taraf satıcıdadır; pazaryerindeki VitrA ürünlerinin medyan fiyatı aynı kategorinin çok satan ürünlerinin <b>1,5x-6x</b> üzerindedir (takım klozette ~1,5x, klozette ~2x, banyo dolabında 6x'e kadar); banyo mobilyasında farkın fiyatla değil <b>set, montaj ve garanti bütünlüğüyle</b> kurulması değerlendirilebilir", "Price and seller control on marketplaces is limited: on Hepsiburada 69% of the buybox for VitrA products sits with third-party sellers; the median price of VitrA products on marketplaces is <b>1.5x-6x</b> that of the category's best sellers (~1.5x in WC sets, ~2x in WCs, up to 6x in bathroom cabinets); in bathroom furniture the difference can be built on <b>a combined set, installation and warranty offer</b> rather than on price"),
 ("at", "Satış sonrası deneyim şikayetlerin ağırlık merkezidir: Şikayetvar'da son 24 aydaki metinli 581 VitrA şikayetinin %76,9'u servis, yedek parça, montaj veya iletişim temalarından en az birini taşımaktadır; marka puanı 18/100'dür; yedek parça temasının payı Eki 2024 - Mar 2025 döneminde %8,1 iken Nis - Eyl 2026 döneminde %17,8'e çıkmıştır", "The after-sales experience is the centre of gravity of complaints: 76.9% of the 581 text VitrA complaints of the last 24 months on Şikayetvar carry at least one of the service, spare part, installation or contact themes; the brand score is 18/100; the share of the spare-part theme rose from 8.1% in Oct 2024 - Mar 2025 to 17.8% in Apr - Sep 2026"),
 ("at", "Aynı VitrA ürünü pazaryerinde VitrA sitesinden daha ucuz bulunmaktadır: 29 üründen 19'unda en ucuz kanal vitra.com.tr dışında (fark medyanı %24,7, armatürde %29,8); Google Shopping satıcı listelerinde VitrA sitesi en düşük fiyatın medyan %37 üzerindedir ve kategori kelimelerinin 15'inde hiç görünmemektedir", "The same VitrA product is found cheaper on marketplaces than on the VitrA site: for 19 of 29 products the cheapest channel is outside vitra.com.tr (median gap 24.7%, taps 29.8%); in Google Shopping seller lists the VitrA site is a median 37% above the lowest price and does not appear at all for 15 category keywords"),
 ("at", "vitra.com.tr kategori sayfalarında stok ve fiyat gösterimi geliştirme alanıdır: 55 sayfadaki 2.258 varyant kartının %71,1'i stoklu süzgeci dışında, 13 alt kategoride stoklu ürün bulunmamakta, ilk sayfa kartlarının %89,9'unda \"Sepette %N indirim\" etiketi yer almaktadır; aynı model kodunda pazaryeri fiyatı liste fiyatının medyan %14,4 altında ve sepet fiyatına yakın seyretmektedir", "Stock and price display on vitra.com.tr category pages is an area for improvement: 71.1% of the 2,258 variant cards on 55 pages fall outside the in-stock filter, 13 sub-categories have no in-stock product, 89.9% of first-page cards carry an \"N% off in basket\" label; for the same model code the marketplace price runs a median 14.4% below the list price and close to the basket price"),
 ("at", "Trendyol resmi mağazasında net adet dört çeyrekte <b>4,3x</b> artmış, ortalama net fiyat ise 3.539 TL'den 1.688 TL'ye inmiştir: büyüme düşük fiyatlı tamamlayıcı ürünlerden gelmektedir. Mağaza cirosunda öne çıkan mobilya, batarya ve duş kategorilerinin Eylül 2026 çok satan listelerinde resmi mağaza yer almamakta; listelerdeki VitrA markalı satırların %73'ü üçüncü taraf satıcıdadır. İadelerin %27,6'sında neden ölçü, %19,2'sinde yanlış sipariştir.", "In the official Trendyol store net units grew <b>4.3x</b> in four quarters while the average net price fell from 3,539 TL to 1,688 TL: growth comes from low-priced complementary products. The official store is absent from the September 2026 best-seller lists of furniture, taps and showers, which stand out in the store's revenue; 73% of VitrA-branded rows in the lists are at third-party sellers. 27.6% of returns cite size and 19.2% a wrong order."),
 ("at", "Google'da ürün ve kategori aramalarının ön sıraları pazaryerlerindedir (Trendyol 109 kelimenin 86'sında ilk 10'da); VitrA SSG'de ve banyo ile lavabo bataryasında ilk 3'te yer almakta, bitişik ürün, tamamlayıcı armatür ve tamir içeriğinde ise ilk 10 dışında kalmaktadır; en çok izlenen 14 YouTube tamir, kurulum ve karar konusunun hiçbirinde VitrA kanal videosu bulunmamaktadır", "The top positions of product and category searches on Google belong to marketplaces (Trendyol in the top 10 for 86 of 109 keywords); VitrA is in the top 3 in SSG and in bath and basin taps but outside the top 10 in adjacent products, complementary taps and repair content, and none of the 14 most-viewed YouTube repair, installation and decision topics has a VitrA channel video"),
 ("up", "AI aramada görünürlük için fırsat sorun çözen içerikte toplanmaktadır: rehber sayfalarında tıkların %35'i montaj, tamir ve temizlik yazılarından gelmekte, destek bölümünde bu konularda sayfa bulunmamaktadır; VitrA 24 AI Overview'un 7'sinde kaynak gösterilmektedir. Wikidata ve Wikipedia'daki marka kayıtlarının tutarlı hale gelmesi de markanın AI yanıtlarında doğru tanımlanmasını destekleyebilir", "The opportunity for visibility in AI search lies in problem-solving content: 35% of guide page clicks come from installation, repair and cleaning articles, while the support section has no pages on these topics; VitrA is cited in 7 of 24 AI Overviews. Making the brand records on Wikidata and Wikipedia consistent can also support the brand being identified correctly in AI answers"),
])
FN = '<div class="fnotes">%s</div>' % "".join([
 fnote(1, "SSG'de dayanıklılık, BM'de daralma", "SSG resilience, BM contraction",
       [("SSG üç yılda <b>%s</b>; klozet <b>%s</b>, akıllı klozet seti <b>%s</b>, bide <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"])), "SSG <b>%s</b> over three years; WCs <b>%s</b>, smart WC sets <b>%s</b>, bidets <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"]))),
        ("BM üç yılda <b>%s</b>; yalnız tezgah (<b>%s</b>) ve çamaşır makinesi dolabı (<b>%s</b>) talebini korumaktadır" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"])), "BM <b>%s</b> over three years; only countertops (<b>%s</b>) and washing machine cabinets (<b>%s</b>) hold demand" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"]))),
        ("Oca-Ağu 2026'da toplam talep <b>%s</b>; tasarım ve model aramaları <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])), "Total demand <b>%s</b> in Jan-Aug 2026; design and model searches <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])))]),
 fnote(2, "Makro ortam: harcama nominal, niyet yükselişte", "Macro environment: nominal spending, rising intent",
       [("Mobilya ve dekorasyon kart harcaması <b>%s</b> nominal; reel kartlı ödeme endeksi <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100)), "Furniture and decoration card spending <b>%s</b> nominal; real card payment index <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100))),
        ("Tüketici güveni Eylül 2026'da <b>%s</b>; konut tamiratına harcama ihtimali <b>%s</b>" % (("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"]).replace(".", ","), ("%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"]).replace(".", ",")), "Consumer confidence <b>%s</b> in September 2026; probability of spending on home repairs <b>%s</b>" % ("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"], "%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"])),
        ("Konut satışları Oca-Ağu 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100), "House sales Jan-Aug 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100))]),
 fnote(3, "Kullanıcı ne arıyor?", "What does the user search for?",
       [("SSG aramalarının <b>%s</b>'i fiyat, <b>%s</b>'i tamir ve parça ifadesi taşımaktadır; rakip marka adı (<b>%s</b>) VitrA adından (<b>%s</b>) daha sık geçmektedir" % (yzd(oz(OSS, "Fiyat")["pay"]), yzd(oz(OSS, "Tamir / parça")["pay"]), yzd(oz(OSS, "Rakip marka")["pay"]), yzd(oz(OSS, "VitrA")["pay"])), "<b>%s</b> of SSG searches carry price, <b>%s</b> repair and parts; competitor brand names (<b>%s</b>) exceed VitrA (<b>%s</b>)" % tuple(yzd(v).replace("%", "") + "%" for v in (oz(OSS, "Fiyat")["pay"], oz(OSS, "Tamir / parça")["pay"], oz(OSS, "Rakip marka")["pay"], oz(OSS, "VitrA")["pay"]))),
        ("BM'de PVC ve suya dayanıklı gövde <b>%s</b>, küçük banyo <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"])), "In BM, PVC and water-resistant bodies <b>%s</b>, small bathroom <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"]))),
        ("Autocomplete önerilerinin <b>%s</b>'i tamir ve bakım ifadesidir; YouTube'da tesisatçı kanalları görünmelerin <b>%%43,7</b>'sini almaktadır" % yzd(tam_pay), "<b>%s</b> of autocomplete suggestions are repair and maintenance phrases; on YouTube plumber channels take <b>43.7%%</b> of appearances" % (yzd(tam_pay).replace("%", "") + "%"))]),
 fnote(4, "Katalog boşlukları ve yakın fırsatlar", "Catalogue gaps and nearby opportunities",
       [("Hela taşında <b>%s</b> aramaya 1 ürün, havlupanda <b>%s</b> aramaya 2 ürün karşılık gelmektedir" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"])), "Squat toilet <b>%s</b> searches / 1 product; towel radiators <b>%s</b> / 2 products" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"]))),
        ("Evye talebi <b>%s</b> (VitrA'da yalnız seramik), arıtmalı batarya üç yılda <b>%s</b>, erişilebilir ürünler YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"])), "Sink demand <b>%s</b> (VitrA ceramic only), purifier taps <b>%s</b> over three years, accessible products YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"]))),
        ("Gam dışı büyük hacimlerin (arıtma, şofben, tekstil) tadilat paketinde iş ortağı ürünü olarak yer alması değerlendirilebilir", "Large volumes outside the range (purifiers, water heaters, textiles) could be included as partner products in a renovation package")]),
 fnote(5, "Ürün + hizmet: parçalar var, paket yok", "Product + service: the pieces exist, the package does not",
       [("11 montaj kalemi (klozet 2.750 TL, BM seti 4.000 TL), keşif 1.400 TL ve ücretsiz montaj listesinde 89 ürün bulunmaktadır", "11 installation items (WC 2,750 TL, BM set 4,000 TL), survey 1,400 TL, and 89 products on the free-installation list"),
        ("Banyo Asistanı 4 adımda telefon, mağaza ve görüntülü görüşme seçeneği sunmaktadır; 5 VitrA mağazası bulunmaktadır", "Bathroom Assistant (Banyo Asistanı) offers phone, store and video call options in 4 steps; there are 5 VitrA stores"),
        ("Koçtaş, Bauhaus ve Kohler banyoyu \"proje\" olarak satmaktadır; VitrA'da tadilat girişi ve planlayıcı bulunmamaktadır", "Koçtaş, Bauhaus and Kohler sell the bathroom as a \"project\"; VitrA has no renovation entry page or planner")]),
 fnote(6, "Rekabet: pazaryeri, arama sonucu ve marka siteleri", "Competition: marketplaces, search results and brand sites",
       [("Google'da Trendyol 109 kelimenin <b>86</b>'sında ilk 10'dadır; VitrA 29 Eylül 2026 sonuç sayfasında <b>54</b> kelimede ilk 10'da, <b>19</b>'unda 1. sıradadır", "On Google, Trendyol is in the top 10 for <b>86</b> of 109 keywords; on the 29 September 2026 results page VitrA is in the top 10 for <b>54</b> and first for <b>19</b>"),
        ("Trendyol banyo kategorileri aylık tahmini <b>326K</b> organik ziyaret almaktadır", "Trendyol bathroom categories receive an estimated <b>326K</b> organic visits a month"),
        ("Marka siteleri içinde VitrA organik liderdir (<b>%s</b>); karoda Kale VitrA'nın ~<b>2x</b> organik trafiğini almakta, yapı kimyasalı ve mutfak tezgahında rakipler öne çıkmaktadır" % k(vit[4]), "VitrA is the organic leader among brand sites (<b>%s</b>); Kale gets ~<b>2x</b> VitrA's organic traffic in tiles; competitors also lead in building chemicals and kitchen countertops" % k(vit[4]))]),
 fnote(7, "Satış sonrası: şikayet, garanti ve yedek parça", "After-sales: complaints, warranty and spare parts",
       [("Şikayetvar puanı VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, E.C.A. 60, Geberit 78", "Şikayetvar score VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, E.C.A. 60, Geberit 78"),
        ("Yedek parça teması <b>%8,1 → %17,8</b>, montaj ve usta <b>%27,0 → %48,5</b> (Eki 2024 - Mar 2025 → Nis - Eyl 2026); servis ücreti ve garanti reddi 75'er şikayette", "Spare-part theme <b>8.1% → 17.8%</b>, installation and installer <b>27.0% → 48.5%</b> (Oct 2024 - Mar 2025 → Apr - Sep 2026); service fee and warranty refusal in 75 complaints each"),
        ("Ürün sayfalarında garanti süresi ve yedek parça girişi bulunmamaktadır; E.C.A. 20 yıl, Grohe 10 yıla kadar garanti ve 48 saatte parça bilgisi vermektedir", "No warranty period or spare-part entry on product pages; E.C.A. states 20 years, Grohe up to 10 years and parts within 48 hours")]),
 fnote(8, "Fiyat ve kanal politikası", "Price and channel policy",
       [("29 VitrA ürününün <b>19</b>'unda en ucuz kanal pazaryeridir; fark medyanı <b>%24,7</b>, sepet indirimleriyle <b>%15,4</b>; asma klozet ve mobilyada fark medyanı %0'dır", "For <b>19</b> of 29 VitrA products the cheapest channel is a marketplace; median gap <b>24.7%</b>, <b>15.4%</b> with basket discounts; the median gap is 0% in wall-hung WCs and furniture"),
        ("Google Shopping'de VitrA sitesi listelemelerin <b>%0,7</b>'sini almaktadır; VitrA ve Artema ilanlarının <b>%44</b>'ü bağımsız mağazalardan", "On Google Shopping the VitrA site is <b>0.7%</b> of listings; <b>44%</b> of VitrA and Artema listings come from independent stores"),
        ("Aynı model kodunda <b>200</b> eşleşmede pazaryeri fiyatı liste fiyatının medyan <b>%14,4</b> altında, sepet fiyatına yakın; üçüncü taraf satıcılarda liste fiyatının <b>2-3x</b> üzerine çıkan ilanlar bulunmaktadır; 55 kategori sayfasındaki kartların <b>%71,1</b>'i stoklu süzgeci dışında", "For the same model code, in <b>200</b> matches the marketplace price is a median <b>14.4%</b> below the list price and close to the basket price; some third-party sellers list at <b>2-3x</b> the list price; <b>71.1%</b> of cards on 55 category pages fall outside the in-stock filter"),
        ("Taksit mesajı üç yüzeyde farklıdır (üst bantta 6 ay vade farksız, Banyo Asistanı kampanya sayfasında 9, ürün sayfasındaki taksit tablosunda 12); alışveriş kredisi yalnız pazaryerlerinde sunulmaktadır; Banyoline İstanbul'da VitrA serilerine ücretsiz montaj vermektedir", "The instalment message differs on three surfaces (6 months interest-free in the top banner, 9 on the Bathroom Assistant campaign page, 12 in the product page instalment table); consumer credit only on marketplaces; Banyoline gives free installation for VitrA series in Istanbul")]),

])
HTML = """
<div class="kpis">%s</div>
%s
<h3>%s</h3>
%s
""" % (
  KPI,
 box("KRİTİK TESPİT", "KEY FINDINGS", KRITIK),
 x("Öne çıkan bulgular", "Highlights"), FN,
)
