# -*- coding: utf-8 -*-
"""Bolum: Ozet - KPI, kritik tespit, one cikan bulgular."""
import serp_ozet as _S
import b_seomonitor as _BS
_STR = ".".join(reversed(_S.TARIH.split("-")))
_AY = {"01": ("Ocak", "January"), "02": ("Şubat", "February"), "03": ("Mart", "March"), "04": ("Nisan", "April"), "05": ("Mayıs", "May"), "06": ("Haziran", "June"), "07": ("Temmuz", "July"), "08": ("Ağustos", "August"), "09": ("Eylül", "September"), "10": ("Ekim", "October"), "11": ("Kasım", "November"), "12": ("Aralık", "December")}
_y, _m, _d = _S.TARIH.split("-"); _STR_TR = "%d %s %s" % (int(_d), _AY[_m][0], _y); _STR_EN = "%d %s %s" % (int(_d), _AY[_m][1], _y)
from ortak import *
K1 = A["k1"]; TOP = A["toplam"]; NI = A["niyet"]; GT = A["gsc_tur"]; GS = A["gsc_sorgu_niyet"]; AT = A["auto_tema"]
toplam_yoy = (TOP["a26"] / TOP["a25"] - 1) * 100; kloz = A["k2"]["Vitrifiyeler|Klozetler"]["yoy"]; bm = K1["Banyo Mobilyaları"]["yoy"]
ttot = sum(v[0] for v in GT.values()); ktot = sum(v[0] for v in A["gsc_kat"].values())
bm_tik = 100 * sum(v[0] for kk, v in A["gsc_kat"].items() if kk.startswith("Banyo Mobilyaları")) / ktot; bm_talep = 100 * K1["Banyo Mobilyaları"]["a26"] / TOP["a26"]
from b_marka import AT as _AT
tam_pay = 100 * _AT["Tamir ve bakım"] / sum(_AT.values())
vit = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "vitra.com.tr"); koc = next(b for b in veri.AHREFS["ahrefs_batch_tr"] if b[0] == "koctas.com.tr")
son12 = sum(A["gsc_ay_toplam"][m][0] for m in A["gsc_aylar"][-13:-1])
TM = YK["tema"]; SEG = SB["seg"]; OB = SB["oz_bm"]; OSS = SB["oz_ssg"]
def oz(o, ad): return next(z for z in o["ozellik"] if z["ad"] == ad)
yed = TM["yedek"]["v12"] + TM["ic_takim"]["v12"]
KPI = "".join([
 kpi_kart(yz(toplam_yoy), "Kategori arama talebi · Oca-Ağu 2026 / 2025, 2.349 kelime", "Category search demand · Jan-Aug 2026 / 2025, 2,349 keywords", "dn"),
 kpi_kart(yz(SEG["SSG"]["uc"]), "SSG talebi · 3 yıllık değişim; BM %s" % yz(SEG["BM"]["uc"]), "SSG demand · 3-year change; BM %s" % yz(SEG["BM"]["uc"]), "up"),
 kpi_kart(k(yed), "Aylık iç takım ve yedek parça araması · sitede yedek parça kategorisi yok", "Monthly inner-mechanism and spare-part searches · no spare-parts category on the site", "hi"),
 kpi_kart(yzd(oz(OB, "Perakendeci / pazaryeri")["pay"]), "BM aramalarında perakendeci adı geçen pay · VitrA %s" % yzd(oz(OB, "VitrA")["pay"]), "Share of BM searches naming a retailer · VitrA %s" % (yzd(oz(OB, "VitrA")["pay"]).replace("%", "") + "%"), "hi"),
])
from ortak import _J
_YA = _J("islenmis", "yorum_analiz.json"); _YBD = next(g_ for g_ in _YA["grup"] if g_["grup"] == "Banyo dolabı")
def _e(v): return ("%.1f" % v) + "%"
_UY = dict((t_, r_) for t_, _, r_ in _YA["soru"]["VitrA"]["tema"]).get("uyum", 0)
def mk_git(maddeler):
    """[(isaret, tr, en, hedef)] -> isaretli liste; her maddenin sonunda ilgili alt basliga ok."""
    from ortak import _kc, git as _git
    return '<ul class="marks">%s</ul>' % "".join('<li><span class="mk %s">%s</span><span class="mt">%s%s</span></li>' % (s_, "✓" if s_ == "up" else "▲", x(*_kc(a, b)), _git(h)) for s_, a, b, h in maddeler)
KRITIK = mk_git([
 ("at", "**Banyo ürünlerine olan arama talebi gerilemektedir ve iki ana grup farklı seyretmektedir**: klozet, lavabo gibi vitrifiye ürünlerde (SSG) aylık arama sayısı üç yıl önceki düzeyindedir (%s), **banyo mobilyasında (BM) ise %s azalmıştır**. Bu gerileme ekonomik koşullarla ilişkilendirilebilir; ertelenen banyo yenileme talebinin 2026'nın son çeyreği ile 2027'nin ilk çeyreğinde geri gelmesi beklenebilir" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"])),
  "**Search demand for bathroom products is declining and the two main groups diverge**: monthly searches for vitreous china products such as WCs and washbasins (SSG) are at the level of three years ago (%s), **while bathroom furniture (BM) fell %s**. The decline can be linked to economic conditions; postponed bathroom renovation demand may return in the last quarter of 2026 and the first quarter of 2027" % (yz(SEG["SSG"]["uc"]), yz(SEG["BM"]["uc"])), "SSG: ürün tipi düzeyinde değişim"),
 ("at", "**Yedek parçaya ilgi yüksektir ancak sitede karşılığı bulunmamaktadır**: Google'da **her ay yaklaşık %s kez iç takım, şamandıra, menteşe, kartuş ve conta gibi yedek parçalar aranmaktadır**. vitra.com.tr'de yedek parça kategorisi yoktur; eski yedek parça sayfası yalnızca tek ürün içeren bir kategoriye yönlenmektedir" % k(yed),
  "**Interest in spare parts is high but has no counterpart on the site**: **inner mechanisms, float valves, hinges, cartridges and gaskets are searched on Google about %s times a month**. vitra.com.tr has no spare-parts category; the old spare-parts page redirects to a category containing a single product" % k(yed), "#katalog"),
 ("at", "**VitrA'nın hizmetleri mevcuttur ancak tek bir paket olarak sunulmamaktadır**: sitede 11 ayrı montaj hizmeti, yerinde keşif, Banyo Asistanı (danışmanlık) ve ücretsiz montajlı mobilya bulunmaktadır; ancak **bunlar \"ürün + montaj + keşif\" şeklinde tek bir teklifte birleşmemektedir**. Duşakabin gibi ölçü alınmadan seçilemeyen ürünlerin sayfasında montaj veya keşif seçeneği görünmemektedir",
  "**VitrA's services exist but are not offered as one package**: the site has 11 separate installation services, on-site survey, the Bathroom Assistant (advice) and furniture with free installation, but **these are not combined into a single \"product + installation + survey\" offer**. Installation or survey options do not appear on pages of products such as shower enclosures that cannot be chosen without measuring", "VitrA'nın mevcut hizmet kalemleri"),
 ("up", "**VitrA'nın bugün satmadığı ama markaya yakın ürünlerde talep bulunmaktadır**: **evye (mutfak lavabosu; aylık %s arama**, granit, çelik ve akıllı evye dahil), su arıtmalı batarya, engelli ve çocuk banyosu ürünleri. Havlupan ve ledli aynada ise talebe göre ürün çeşidi azdır" % k(TM["evye"]["v12"]),
  "**There is demand in products VitrA does not sell today but which are close to the brand**: **sinks (kitchen sinks; %s searches a month**, including granite, steel and smart sinks), purifier taps, and accessible and children's bathroom products. In towel radiators and LED mirrors the product range is narrow relative to demand" % k(TM["evye"]["v12"]), "Öncelikli dört fırsat"),
 ("at", "**Pazaryerinde VitrA ürünlerinin fiyatı ve satıcısı VitrA'nın kontrolünde değildir**: Hepsiburada'da **VitrA ürünlerinin %69'unda \"sepete ekle\" düğmesini (buybox) VitrA değil başka bir satıcı kazanmaktadır**. Pazaryerindeki VitrA ürünleri, aynı kategoride en çok satan ürünlerden tipik olarak <b>1,5 ile 6 kat</b> daha pahalıdır: takım klozette yaklaşık 1,5 kat, klozette 2 kat, banyo dolabında 6 kata kadar. Banyo mobilyasında VitrA'nın fiyatla değil <b>set, montaj ve garanti</b> avantajıyla öne çıkması değerlendirilebilir",
  "**VitrA does not control the price and seller of its products on marketplaces**: on Hepsiburada, **for 69% of VitrA products the \"add to basket\" button (buybox) is won by another seller, not VitrA**. VitrA products on marketplaces are typically <b>1.5 to 6 times</b> more expensive than the best sellers in the same category: about 1.5 times in WC sets, 2 times in WCs and up to 6 times in bathroom cabinets. In bathroom furniture VitrA may stand out through <b>set, installation and warranty</b> advantages rather than price", "Fiyat konumu"),
 ("at", "**Şikayetler ağırlıkla satın alma sonrası süreçle ilgilidir**: Şikayetvar'da son 24 ayda yazılan **581 VitrA şikayetinin %76,9'u servis, yedek parça, montaj veya müşteri hizmetlerine ulaşma konularından en az birini içermektedir**. VitrA'nın Şikayetvar marka puanı 100 üzerinden 18'dir. Yedek parça şikayetlerinin payı Eki 2024 - Mar 2025 döneminde %8,1 iken Nis - Eyl 2026 döneminde %17,8'e çıkmıştır",
  "**Complaints mainly concern the after-purchase process**: **76.9% of the 581 VitrA complaints written on Şikayetvar in the last 24 months mention at least one of service, spare parts, installation or reaching customer service**. VitrA's Şikayetvar brand score is 18 out of 100. The share of spare-part complaints rose from 8.1% in Oct 2024 - Mar 2025 to 17.8% in Apr - Sep 2026", "Altı aylık dönemlerde tema geçişi"),
 ("at", "**Aynı VitrA ürünü çoğu zaman pazaryerinde vitra.com.tr'den daha ucuza satılmaktadır**: incelenen **29 VitrA ürününün 19'unda en düşük fiyat vitra.com.tr'de değil**, Hepsiburada, Trendyol veya Koçtaş'taki bir satıcıdadır. Bu 19 üründe pazaryerindeki en düşük fiyat, vitra.com.tr liste fiyatından tipik olarak <b>%24,7 daha düşüktür</b> (medyan; armatürde %29,8). Örneğin sitede 1.000 TL olan bir ürün pazaryerinde yaklaşık 750 TL'ye bulunabilmektedir; sitedeki sepet indirimi hesaba katıldığında fark %15,4'e inmektedir. Google Alışveriş'te (Shopping) aynı ürünün satıcılarının listelendiği 24 ürünün 9'unda VitrA sitesi de yer almakta, bu ürünlerde VitrA sitesinin fiyatı en düşük satıcı fiyatından tipik olarak %37 yüksek kalmaktadır. 27 kategori aramasının 15'inde VitrA sitesi Google Alışveriş sonuçlarında hiç görünmemektedir",
  "**The same VitrA product is often sold cheaper on marketplaces than on vitra.com.tr**: **for 19 of the 29 VitrA products reviewed, the lowest price is not on vitra.com.tr** but at a seller on Hepsiburada, Trendyol or Koçtaş. For these 19 products the lowest marketplace price is typically <b>24.7% lower</b> than the vitra.com.tr list price (median; 29.8% for taps). For example, a product priced at 1,000 TL on the site can be found for about 750 TL on a marketplace; with the site's basket discount the gap falls to 15.4%. On Google Shopping, the VitrA site appears in 9 of the 24 products whose sellers are listed, and in these products its price is typically 37% above the lowest seller price. In 15 of 27 category searches the VitrA site does not appear in Google Shopping results at all", "VitrA ürünlerinde kanal fiyat farkı: 29 ürün"),
 ("at", "**vitra.com.tr kategori sayfalarında ürünlerin büyük bölümü stokta görünmemektedir**: 55 kategori sayfasındaki 2.258 ürün seçeneğinin (renk ve ölçü varyantları) %71,1'i \"stoktakiler\" filtresine girmemekte, **13 alt kategoride stokta hiç ürün bulunmamaktadır**. İlk sayfadaki ürünlerin %89,9'unda \"Sepette %N indirim\" etiketi yer almaktadır; yani kartta görünen fiyat ödenecek fiyat değildir. Aynı model kodlu ürün pazaryerinde vitra.com.tr liste fiyatından tipik olarak %14,4 daha ucuza ve sitedeki sepet fiyatına yakın bir fiyata satılmaktadır",
  "**Most products on vitra.com.tr category pages do not appear in stock**: 71.1% of the 2,258 product options (colour and size variants) on 55 category pages fall outside the \"in stock\" filter, and **13 sub-categories have no product in stock at all**. 89.9% of first-page products carry an \"N% off in basket\" label, so the price shown on the card is not the price paid. The same model code sells on marketplaces typically 14.4% below the vitra.com.tr list price, close to the site's basket price", "vitra.com.tr kategori sayfaları: ürün, fiyat aralığı ve stok"),
 ("at", "**vitra.com.tr'de satın alma adımları kullanıcıyı gereğinden fazla ekrandan geçirmektedir**: üye olmadan alışveriş yapmak isteyen kullanıcı \"Sepeti Onayla\" dedikten sonra **adres adımına gelmeden iki ara ekran** (giriş paneli ve ayrı e-posta ekranı) geçmektedir. Site içi aramada yazarken açılan anlık sonuçlar çoğunlukla ilgili ürünleri getirirken, Enter sonrası açılan sonuç sayfası 38 test ifadesinin 8'inde boş ya da ilgisiz dönmektedir; kartuş, conta, yedek parça, garanti ve servis aramalarında iki yolda da ilgili ürün ya da destek sayfası çıkmamaktadır. Sepetteki montaj hizmetleri ve öneri alanları sayfanın altında kalmaktadır. **Sepette tek adımlı üyeliksiz satın alma ve iki arama yolunun tekleştirilmesi** sitenin kendi kontrolündeki dönüşüm fırsatlarıdır",
  "**Purchase steps on vitra.com.tr take the user through more screens than needed**: a user who wants to buy without an account passes **two intermediate screens before the address step** (a sign-in panel and a separate e-mail screen) after \"Confirm cart\". In site search, instant results while typing mostly return relevant products, but the results page after Enter is empty or off-target for 8 of the 38 test terms; cartridge, seal, spare part, warranty and service searches return no relevant product or support page on either path. Installation services and recommendation areas in the cart sit at the bottom of the page. **One-step guest purchase in the cart and aligning the two search paths** are conversion opportunities under the site's own control", "Yolculuk adımları: gözlem, etki ve öneri"),
 ("at", "**Trendyol'daki VitrA resmi mağazasında satış adedi artarken ortalama fiyat düşmüştür**: son dört çeyrekte satılan ürün adedi 4,3 katına çıkmış, ortalama satış fiyatı ise 3.539 TL'den 1.688 TL'ye inmiştir; **büyüme ağırlıkla ara musluk ve aksesuar gibi düşük fiyatlı ürünlerden gelmektedir**. Mağaza cirosunda öne çıkan banyo mobilyası, batarya ve duş kategorilerinde, Trendyol'un Eylül 2026 çok satanlar listelerinde resmi mağaza yer almamaktadır; bu listelerdeki VitrA ürünlerinin %73'ü başka satıcılar üzerinden satılmaktadır. İadelerin %27,6'sı ölçünün uymaması, %19,2'si yanlış ürün siparişi nedeniyle yapılmaktadır",
  "**In the official VitrA store on Trendyol, unit sales grew while the average price fell**: units sold rose 4.3 times over the last four quarters while the average selling price fell from 3,539 TL to 1,688 TL; **growth comes mainly from low-priced products such as angle valves and accessories**. In bathroom furniture, taps and showers, which stand out in the store's revenue, the official store is absent from Trendyol's September 2026 best-seller lists; 73% of VitrA products in these lists are sold through other sellers. 27.6% of returns are due to the size not fitting and 19.2% to ordering the wrong product", "Çeyreklik satış, fiyat ve karışım"),
 ("at", "**Google'da ürün ve kategori aramalarında üst sıraları pazaryerleri almaktadır**: **Trendyol VitrA gamındaki %d ürün ve kategori aramasının %s ilk 10 sonuç arasındadır**. VitrA klozet ve lavabo gibi vitrifiye ürünlerde ve banyo ile lavabo bataryasında ilk 3'tedir; ancak taharet musluğu ve robot duş gibi tamamlayıcı armatürlerde, su arıtma ve şofben gibi banyoyla birlikte alınan ürünlerde ve tamir içeriklerinde ilk 10'un dışında kalmaktadır. YouTube'da en çok izlenen 14 tamir, kurulum ve ürün seçimi konusunun hiçbirinde VitrA kanalının videosu çıkmamaktadır" % (_S.N, ek(_S.D10["trendyol.com"], "inde")),
  "**Marketplaces take the top positions in product and category searches on Google**: **Trendyol is in the top 10 results for %d of the %d product and category searches in VitrA's range**. VitrA is in the top 3 for vitreous china products such as WCs and washbasins and for bath and basin taps, but outside the top 10 for complementary taps such as bidet taps and shower sets, for products bought together with the bathroom such as water purifiers and water heaters, and for repair content. None of the 14 most-viewed repair, installation and product choice topics on YouTube shows a VitrA channel video" % (_S.D10["trendyol.com"], _S.N), "A · VitrA gamı: kategori bazında VitrA nerede?"),
 ("at", "**Pazaryeri yorumlarında genel memnuniyet rakiplerle aynı düzeydedir, banyo dolabı ayrışmaktadır**: Trendyol ve Hepsiburada'da VitrA ve Artema ürünlerine 1-2 puan veren yorumların payı %s, rakip markalarda %s'tir. VitrA ve Artema banyo dolaplarında ise düşük puanlı yorumların payı %s'dir (rakiplerde %s) ve **bu yorumların %s'i ürünün kırık veya hasarlı gelmesinden kaynaklanmaktadır**. VitrA ürünlerine sorulan soruların %s'i \"bu ürün benim klozetime veya tesisatıma uyar mı\" türünden uyumluluk sorularıdır" % (yzd(_YA["vg"]["olumsuz"]), yzd(_YA["rakip"]["olumsuz"]), yzd(_YBD["vitra"]["olumsuz"]), yzd(_YBD["rakip"]["olumsuz"]), yzd(_YBD["vitra"]["tema_neg"].get("kirik", 0)), yzd(_UY)),
  "**In marketplace reviews overall satisfaction is in line with competitors, while bathroom cabinets diverge**: on Trendyol and Hepsiburada the share of 1-2 star reviews is %s for VitrA and Artema products and %s for competitor brands. For VitrA and Artema bathroom cabinets the share of low-rated reviews is %s (competitors %s), and **%s of these reviews are due to the product arriving broken or damaged**. %s of questions on VitrA products are compatibility questions such as \"will this product fit my WC or plumbing\"" % (_e(_YA["vg"]["olumsuz"]), _e(_YA["rakip"]["olumsuz"]), _e(_YBD["vitra"]["olumsuz"]), _e(_YBD["rakip"]["olumsuz"]), _e(_YBD["vitra"]["tema_neg"].get("kirik", 0)), _e(_UY)), "Ürün grubu karşılaştırması"),
 ("up", "**Yapay zeka destekli aramalarda (Google AI Overview, ChatGPT gibi) görünürlük için en büyük fırsat sorun çözen içeriktedir**: vitra.com.tr rehber yazılarına gelen tıkların %35'i montaj, tamir ve temizlik konularından gelmektedir, ancak **destek bölümündeki 23 SSS sayfası ve yaklaşık 530 soru dağınık yapıdadır: 4 sayfada sayfa başlığı ve soru-cevap işaretlemesi eksik, 4 ürün grubunda çift SSS sayfası bulunmaktadır**. Google'ın yapay zeka özetlerinin (AI Overview) incelendiği " + "%d aramanın %s" % (len(_S.AI_ICERIK), ek(len(_S.AI_VITRA), "inde")) + " VitrA kaynak olarak gösterilmektedir; SEOmonitor'de takip edilen " + "%s kelimenin %s AI Overview çıkmakta, VitrA bunların %s kaynak gösterilmektedir." % (bin(_BS.TOP["n"]), ek(_BS.TOP["aio"], "inde"), yzd(100 * _BS.TOP["vitra"] / _BS.TOP["aio"], 0) + "'" + ek(round(100 * _BS.TOP["vitra"] / _BS.TOP["aio"]), "inde").split("'")[1]) + " **ChatGPT, Gemini ve AI Overview'a sorulan, marka adı geçmeyen 111 soruda VitrA yanıtların %52-74'ünde adıyla geçen en sık üretici markadır**; ancak \"nereden alınır\", teslimat ve iade gibi satın almaya yakın sorularda kaynak olarak çoğunlukla Koçtaş, Trendyol ve Bauhaus gösterilmektedir. Wikidata ve Wikipedia'daki VitrA kayıtlarının tutarlı hale getirilmesi, yapay zeka yanıtlarında markanın doğru tanıtılmasına katkı sağlayabilir",
  "**The biggest opportunity for visibility in AI-assisted search (Google AI Overview, ChatGPT and similar) lies in problem-solving content**: 35% of clicks to vitra.com.tr guide articles come from installation, repair and cleaning topics, while **the 23 FAQ pages and about 530 questions in the support section are scattered: 4 pages lack a page title and Q&A markup, and 4 product groups have duplicate FAQ pages**. VitrA is cited as a source in " + "%d of the %d searches" % (len(_S.AI_VITRA), len(_S.AI_ICERIK)) + " where Google's AI summaries (AI Overview) were reviewed; " + "%d of the %s keywords tracked in SEOmonitor show an AI Overview, and VitrA is cited in %s of them." % (_BS.TOP["aio"], f"{_BS.TOP['n']:,}", ("%.0f" % (100 * _BS.TOP["vitra"] / _BS.TOP["aio"])) + "%") + " **In 111 questions without a brand name asked to ChatGPT, Gemini and AI Overview, VitrA is the manufacturer brand named most often, in 52-74% of answers**; however for questions close to purchase such as where to buy, delivery and returns, the sources cited are mostly Koçtaş, Trendyol and Bauhaus. Making the VitrA records on Wikidata and Wikipedia consistent can help the brand be introduced correctly in AI answers", "Mevcut durum: rehber içerik ve soru sorguları"),
])
ACIK = {
 1: ("Google'daki 2.349 banyo kelimesinin aylık arama hacmi (Keyword Planner), Eyl 2022 - Ağu 2023 ile Eyl 2025 - Ağu 2026 dönemleri karşılaştırılarak incelendi.", "The monthly search volume of 2,349 bathroom keywords on Google (Keyword Planner) was reviewed by comparing Sep 2022 - Aug 2023 with Sep 2025 - Aug 2026."),
 2: ("Merkez Bankası verileriyle kart harcamaları, tüketici güveni ve konut satışları izlendi; bu göstergeler banyo talebinin arka planını anlatır.", "Card spending, consumer confidence and house sales were tracked with central bank data; these indicators describe the background to bathroom demand."),
 3: ("Banyo aramalarına eklenen ifadeler (fiyat, tamir, marka, mağaza), Google'ın arama önerileri ve YouTube sonuçları incelendi.", "Phrases added to bathroom searches (price, repair, brand, store), Google's search suggestions and YouTube results were reviewed."),
 4: ("Aranan ürün grupları vitra.com.tr'deki ürün sayısıyla karşılaştırıldı; aranıp VitrA'da az bulunan ya da hiç bulunmayan ürünler belirlendi.", "Searched product groups were compared with the number of products on vitra.com.tr; products that are searched but scarce or missing at VitrA were identified."),
 5: ("vitra.com.tr'deki montaj, keşif ve danışmanlık hizmetleri ile Koçtaş, Bauhaus ve Kohler'in banyo yenileme teklifleri karşılaştırıldı.", "The installation, survey and advice services on vitra.com.tr were compared with the bathroom renovation offers of Koçtaş, Bauhaus and Kohler."),
 6: ("Kategori kelimelerinde Google sonuç sayfası (" + _STR + "), pazaryerlerinin banyo kategorisi trafiği ve marka sitelerinin organik trafiği incelendi.", "The Google results page for category keywords (" + _STR + "), marketplaces' bathroom category traffic and brand sites' organic traffic were reviewed."),
 7: ("Şikayetvar'daki VitrA ve rakip marka sayfaları (son 24 ay) ile ürün sayfalarındaki garanti ve yedek parça bilgisi incelendi.", "VitrA and competitor brand pages on Şikayetvar (last 24 months) and warranty and spare-part information on product pages were reviewed."),
 8: ("vitra.com.tr'den seçilen 29 VitrA ve Artema ürününün (klozet, lavabo, armatür, gömme rezervuar, klozet kapağı, iç takım ve banyo mobilyası) fiyatı, 29.09.2026'da ürün koduyla Trendyol, Hepsiburada ve Koçtaş'ta aranarak karşılaştırıldı. Ürünler 39 adaydan en az iki kanalda satılanlar arasından seçildi. Ayrıca Google Alışveriş ilanları ve vitra.com.tr ile aynı model kodunu taşıyan 200 pazaryeri ilanı incelendi.", "The prices of 29 VitrA and Artema products chosen from vitra.com.tr (WCs, washbasins, taps, concealed cisterns, toilet seats, inner mechanisms and bathroom furniture) were compared on 29.09.2026 by searching the product code on Trendyol, Hepsiburada and Koçtaş. The products were chosen from 39 candidates as those sold in at least two channels. Google Shopping listings and 200 marketplace listings carrying the same model code as vitra.com.tr were also reviewed."),
}
def fnote_git(no, h_tr, h_en, maddeler, hedefler):
    """maddeler: [(tr, en)], hedefler: her madde icin hedef -> bulgu karti; her maddenin sonunda ilgili alt basliga ok."""
    from ortak import _kc, git as _git
    ac = ACIK.get(no)
    return ('<article class="fnote"><span class="fc">%s</span><h3>%s</h3>%s<ul>%s</ul></article>'
            % (x("Bulgu %02d" % no, "Finding %02d" % no), x(h_tr, h_en), ('<p class="fac">%s</p>' % x(*ac)) if ac else "", "".join("<li>%s%s</li>" % (x(*_kc(a, b)), _git(h)) for (a, b), h in zip(maddeler, hedefler))))
    
FN = '<div class="fnotes">%s</div>' % "".join([
 fnote_git(1, "SSG'de dayanıklılık, BM'de daralma", "SSG resilience, BM contraction",
       [("SSG üç yılda <b>%s</b>; klozet <b>%s</b>, akıllı klozet seti <b>%s</b>, bide <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"])), "SSG <b>%s</b> over three years; WCs <b>%s</b>, smart WC sets <b>%s</b>, bidets <b>%s</b>" % (yz(SEG["SSG"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Klozetler"]["uc"]), yz(SB["k3"]["SSG|Klozetler|Akıllı Klozet Seti"]["uc"]), yz(SB["k3"]["SSG|Bideler|Bideler"]["uc"]))),
        ("BM üç yılda <b>%s</b>; yalnız tezgah (<b>%s</b>) ve çamaşır makinesi dolabı (<b>%s</b>) talebini korumaktadır" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"])), "BM <b>%s</b> over three years; only countertops (<b>%s</b>) and washing machine cabinets (<b>%s</b>) hold demand" % (yz(SEG["BM"]["uc"]), yz(SB["k3"]["BM|Banyo Tezgahları|Banyo Tezgahları"]["uc"]), yz(SB["k3"]["BM|Banyo Dolapları|Çamaşır Makinesi Dolapları"]["uc"]))),
        ("Oca-Ağu 2026'da toplam talep <b>%s</b>; tasarım ve model aramaları <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])), "Total demand <b>%s</b> in Jan-Aug 2026; design and model searches <b>%s</b>" % (yz(toplam_yoy), yz(NI["Tasarım ve fikir"]["yoy"])))], ['SSG: ürün tipi düzeyinde değişim', 'BM: ürün tipi düzeyinde değişim', 'Ana kategori düzeyinde değişim']),
 fnote_git(2, "Ekonomik ortam: harcama artışı fiyat kaynaklı, yenileme niyeti yükseliyor", "Economic environment: spending growth is price-driven, renovation intent is rising",
       [("Mobilya ve dekorasyon kartlı harcaması fiyat artışları dahil (nominal) <b>%s</b> değişmiştir; enflasyondan arındırılmış (reel) kartlı ödeme endeksi <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100)), "Furniture and decoration card spending changed <b>%s</b> including price increases (nominal); the inflation-adjusted (real) card payment index <b>%s</b>" % (yz(A["kart"]["mobilya_dekorasyon"]["yoy"]), yz((sum(A["koe"]["2026-%d" % m]["genel_reel"] for m in range(1, 8)) / sum(A["koe"]["2025-%d" % m]["genel_reel"] for m in range(1, 8)) - 1) * 100))),
        ("Tüketici güveni Eylül 2026'da <b>%s</b>; konut tamiratına harcama ihtimali <b>%s</b>" % (("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"]).replace(".", ","), ("%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"]).replace(".", ",")), "Consumer confidence <b>%s</b> in September 2026; probability of spending on home repairs <b>%s</b>" % ("%.1f" % A["tuketici"]["2026-9"]["guven_endeksi"], "%.1f" % A["tuketici"]["2026-9"]["konut_tamirat_harcama_ihtimali"])),
        ("Konut satışları Oca-Ağu 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100), "House sales Jan-Aug 2026 <b>%s</b>" % yz((sum(A["konut"]["2026-%d" % m]["toplam"] for m in range(1, 9)) / sum(A["konut"]["2025-%d" % m]["toplam"] for m in range(1, 9)) - 1) * 100))], ['Kart harcamaları: banyo ile ilişkili sektörler', 'Tüketici eğilimi ve yenileme niyeti', 'Konut hareketliliği ve kredi koşulları']),
 fnote_git(3, "Kullanıcı ne arıyor?", "What does the user search for?",
       [("SSG aramalarının <b>%s</b>'i fiyat, <b>%s</b>'i tamir ve parça ifadesi taşımaktadır; rakip marka adı (<b>%s</b>) VitrA adından (<b>%s</b>) daha sık geçmektedir" % (yzd(oz(OSS, "Fiyat")["pay"]), yzd(oz(OSS, "Tamir / parça")["pay"]), yzd(oz(OSS, "Rakip marka")["pay"]), yzd(oz(OSS, "VitrA")["pay"])), "<b>%s</b> of SSG searches carry price, <b>%s</b> repair and parts; competitor brand names (<b>%s</b>) exceed VitrA (<b>%s</b>)" % tuple(yzd(v).replace("%", "") + "%" for v in (oz(OSS, "Fiyat")["pay"], oz(OSS, "Tamir / parça")["pay"], oz(OSS, "Rakip marka")["pay"], oz(OSS, "VitrA")["pay"]))),
        ("BM'de PVC ve suya dayanıklı gövde <b>%s</b>, küçük banyo <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"])), "In BM, PVC and water-resistant bodies <b>%s</b>, small bathroom <b>%s</b>" % (yz(oz(OB, "PVC / suya dayanıklı")["yoy"]), yz(oz(OB, "Küçük / dar banyo")["yoy"]))),
        ("Autocomplete önerilerinin <b>%s</b>'i tamir ve bakım ifadesidir; YouTube'da tesisatçı kanalları görünmelerin <b>%%43,7</b>'sini almaktadır" % yzd(tam_pay), "<b>%s</b> of autocomplete suggestions are repair and maintenance phrases; on YouTube plumber channels take <b>43.7%%</b> of appearances" % (yzd(tam_pay).replace("%", "") + "%"))], ['Kullanıcı hangi özellikle arıyor? SSG', 'Kullanıcı hangi özellikle arıyor? BM', 'Autocomplete önerilerinin tema oranı']),
 fnote_git(4, "Katalog boşlukları ve yakın fırsatlar", "Catalogue gaps and nearby opportunities",
       [("Hela taşında <b>%s</b> aramaya 1 ürün, havlupanda <b>%s</b> aramaya 2 ürün karşılık gelmektedir" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"])), "Squat toilet <b>%s</b> searches / 1 product; towel radiators <b>%s</b> / 2 products" % (k(TM["hela"]["v12"]), k(TM["havlupan"]["v12"]))),
        ("Evye talebi <b>%s</b> (VitrA'da yalnız seramik), arıtmalı batarya üç yılda <b>%s</b>, erişilebilir ürünler YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"])), "Sink demand <b>%s</b> (VitrA ceramic only), purifier taps <b>%s</b> over three years, accessible products YoY <b>%s</b>" % (k(TM["evye"]["v12"]), yz(TM["aritma_bat"]["uc_yil"]), yz(TM["engelli"]["yoy"]))),
        ("Gam dışı büyük hacimlerin (arıtma, şofben, tekstil) tadilat paketinde iş ortağı ürünü olarak yer alması değerlendirilebilir", "Large volumes outside the range (purifiers, water heaters, textiles) could be included as partner products in a renovation package")], ['#katalog', 'Öncelikli dört fırsat', 'Öncelikli dört fırsat']),
 fnote_git(5, "Ürün + hizmet: parçalar var, paket yok", "Product + service: the pieces exist, the package does not",
       [("11 montaj kalemi (klozet 2.750 TL, BM seti 4.000 TL), keşif 1.400 TL ve ücretsiz montaj listesinde 89 ürün bulunmaktadır", "11 installation items (WC 2,750 TL, BM set 4,000 TL), survey 1,400 TL, and 89 products on the free-installation list"),
        ("Banyo Asistanı 4 adımda telefon, mağaza ve görüntülü görüşme seçeneği sunmaktadır; 5 VitrA mağazası bulunmaktadır", "Bathroom Assistant (Banyo Asistanı) offers phone, store and video call options in 4 steps; there are 5 VitrA stores"),
        ("Koçtaş, Bauhaus ve Kohler banyoyu \"proje\" olarak satmaktadır; VitrA'da tadilat girişi ve planlayıcı bulunmamaktadır", "Koçtaş, Bauhaus and Kohler sell the bathroom as a \"project\"; VitrA has no renovation entry page or planner")], ["VitrA'nın mevcut hizmet kalemleri", "VitrA'nın mevcut hizmet kalemleri", 'Rakip ve benzer modeller']),
 fnote_git(6, "Rekabet: pazaryeri, arama sonucu ve marka siteleri", "Competition: marketplaces, search results and brand sites",
       [(("Google'da Trendyol %d kelimenin <b>%d</b>'%s ilk 10'dadır; VitrA aynı kelimelerin <b>%d</b>'%s ilk 10'da, <b>%d</b>'%s 1. sıradadır") % (_S.N, _S.D10["trendyol.com"], ek(_S.D10["trendyol.com"], "inde").split("'")[1], _S.VITRA["ilk10"], ek(_S.VITRA["ilk10"], "inde").split("'")[1], _S.VITRA["bir"], ek(_S.VITRA["bir"], "inde").split("'")[1]),
         ("On Google, Trendyol is in the top 10 for <b>%d</b> of %d keywords; VitrA is in the top 10 for <b>%d</b> and first for <b>%d</b>") % (_S.D10["trendyol.com"], _S.N, _S.VITRA["ilk10"], _S.VITRA["bir"])),
        ("SEOmonitor'de takip edilen %s kelimede mobil click payı vitra.com.tr <b>%s</b>, Trendyol <b>%s</b>, Koçtaş <b>%s</b> (19 Eyl - 3 Eki 2026)" % (bin(_BS.TOP["n"]), yzd(_BS._vs(_BS.SOC["Tümü"]), 1), yzd(_BS.SOC["Tümü"]["trendyol.com"], 1), yzd(_BS.SOC["Tümü"]["koctas.com.tr"], 1)),
         "Mobile click share across %s keywords tracked in SEOmonitor: vitra.com.tr <b>%s</b>, Trendyol <b>%s</b>, Koçtaş <b>%s</b> (19 Sep - 3 Oct 2026)" % (f"{_BS.TOP['n']:,}", ("%.1f" % _BS._vs(_BS.SOC["Tümü"])) + "%", ("%.1f" % _BS.SOC["Tümü"]["trendyol.com"]) + "%", ("%.1f" % _BS.SOC["Tümü"]["koctas.com.tr"]) + "%")),
        ("Trendyol'un banyo kategori sayfaları Google'dan ayda tahmini <b>326K</b> ücretsiz (organik) ziyaret almaktadır", "Trendyol's bathroom category pages receive an estimated <b>326K</b> free (organic) visits a month from Google"),
        ("Marka siteleri içinde VitrA organik liderdir (<b>%s</b>); karoda Kale VitrA'nın ~<b>2x</b> organik trafiğini almakta, yapı kimyasalı ve mutfak tezgahında rakipler öne çıkmaktadır" % k(vit[4]), "VitrA is the organic leader among brand sites (<b>%s</b>); Kale gets ~<b>2x</b> VitrA's organic traffic in tiles; competitors also lead in building chemicals and kitchen countertops" % k(vit[4]))], ['Kim sıralanıyor?', 'Banyo trafiği hangi sitelerde?', 'Tema bazında VitrA ve en yüksek rakip']),
 fnote_git(7, "Satış sonrası: şikayet, garanti ve yedek parça", "After-sales: complaints, warranty and spare parts",
       [("Şikayetvar puanı VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, E.C.A. 60, Geberit 78", "Şikayetvar score VitrA <b>18</b>, Artema <b>15</b>; Kale 36, Creavit 32, E.C.A. 60, Geberit 78"),
        ("Şikayetlerde yedek parça konusunun payı <b>%8,1'den %17,8'e</b>, montaj ve usta konusunun payı <b>%27,0'dan %48,5'e</b> çıkmıştır (Eki 2024 - Mar 2025 ile Nis - Eyl 2026 karşılaştırması); servis ücreti ve garantinin kabul edilmemesi 75'er şikayette geçmektedir", "In complaints, the share of the spare-part topic rose <b>from 8.1% to 17.8%</b> and installation and installer <b>from 27.0% to 48.5%</b> (Oct 2024 - Mar 2025 compared with Apr - Sep 2026); service fees and refused warranty claims appear in 75 complaints each"),
        ("Ürün sayfalarında garanti süresi ve yedek parça girişi bulunmamaktadır; E.C.A. 20 yıl, Grohe 10 yıla kadar garanti ve 48 saatte parça bilgisi vermektedir", "No warranty period or spare-part entry on product pages; E.C.A. states 20 years, Grohe up to 10 years and parts within 48 hours")], ['Marka sayfası göstergeleri ve rakipler', 'Altı aylık dönemlerde tema geçişi', 'Garanti, yedek parça ve servis iletişimi']),
 fnote_git(8, "Fiyat ve kanal politikası", "Price and channel policy",
       [("Bu 29 ürünün <b>19</b>'unda en düşük fiyat vitra.com.tr'de değil, bir pazaryeri satıcısındadır; bu ürünlerde pazaryeri fiyatı vitra.com.tr liste fiyatından tipik olarak <b>%24,7</b> düşüktür (sitedeki sepet indirimi hesaba katıldığında fark <b>%15,4</b>); asma klozet ve banyo mobilyasında fiyatlar genelde aynıdır", "For <b>19</b> of these 29 products the lowest price is not on vitra.com.tr but at a marketplace seller; for these products the marketplace price is typically <b>24.7%</b> below the vitra.com.tr list price (<b>15.4%</b> once the site's basket discount is included); in wall-hung WCs and bathroom furniture prices are generally the same"),
        ("Google Alışveriş'te (Shopping) kategori aramalarında çıkan ilanların yalnız <b>%0,7</b>'si VitrA sitesine aittir; VitrA ve Artema ürün ilanlarının <b>%44</b>'ü bağımsız banyo ve yapı mağazalarından gelmektedir", "On Google Shopping only <b>0.7%</b> of the listings shown for category searches belong to the VitrA site; <b>44%</b> of VitrA and Artema product listings come from independent bathroom and building stores"),
        ("vitra.com.tr ile aynı model kodunu taşıyan <b>200</b> pazaryeri ilanında fiyat, site liste fiyatından tipik olarak <b>%14,4</b> düşüktür ve sitedeki sepet fiyatına yakındır; bazı üçüncü taraf satıcılar ise liste fiyatının <b>2-3 katına</b> ilan açmaktadır; 55 kategori sayfasındaki ürün kartlarının <b>%71,1</b>'i stokta görünmemektedir", "In <b>200</b> marketplace listings carrying the same model code as vitra.com.tr, the price is typically <b>14.4%</b> below the site list price and close to the site's basket price; some third-party sellers list at <b>2-3 times</b> the list price; <b>71.1%</b> of product cards on 55 category pages do not appear in stock"),
        ("Taksit mesajı üç yüzeyde farklıdır (üst bantta 6 ay vade farksız, Banyo Asistanı kampanya sayfasında 9, ürün sayfasındaki taksit tablosunda 12); alışveriş kredisi yalnız pazaryerlerinde sunulmaktadır; Banyoline İstanbul'da VitrA serilerine ücretsiz montaj vermektedir", "The instalment message differs on three surfaces (6 months interest-free in the top banner, 9 on the Bathroom Assistant campaign page, 12 in the product page instalment table); consumer credit only on marketplaces; Banyoline gives free installation for VitrA series in Istanbul")], ['VitrA ürünlerinde kanal fiyat farkı: 29 ürün', 'VitrA sitesinin göründüğü kelimeler', 'Aynı model kodunda vitra.com.tr ve pazaryeri fiyatı', 'Ödeme ve taksit koşulları']),

])
HTML = """
<div class="kpis">%s</div>
%s
<h3>%s</h3>
%s
""" % (
  KPI,
 box("KRİTİK TESPİT", "KEY FINDINGS", KRITIK),
 x("Öne çıkan bulgular", "Highlights"), FN,
)
