# -*- coding: utf-8 -*-
"""Bolum: Kanal politikalari ve kesif kanallari (odeme, teslimat, garanti, sosyal, Business Profile, Shopping)."""
from ortak import *
import json, os
D = os.path.join(veri.V, "ham", "derin", "kanal_politikalari")
GB = json.load(open(os.path.join(D, "gbp.json"), encoding="utf-8"))
SH = json.load(open(os.path.join(D, "shopping_blok.json"), encoding="utf-8"))["ozet"]
M = GB["magaza"]; SV = GB["servis"]
def sl(dom, ad=None): return u("https://www." + dom, ad or dom)
TAK = [("vitra.com.tr", "Şeritte tüm ürünlerde vade farksız 6 ay (eşiksiz); ürün tablosunda 12 taksite kadar, 8-12 çoğunlukla vade farklı; Banyo Asistanı kampanya sayfasında 9 aya varan taksit", "Banner: 6 months interest-free on all products (no threshold); product table up to 12 instalments, 8-12 mostly with interest; up to 9 instalments on the Bathroom Assistant campaign page", "Bulunamadı", "Not found", "Yok (yalnızca kredi kartı)", "None (card only)", "Var (sepette)", "Yes (in basket)"),
       ("koctas.com.tr", "Yardım sayfasında 10.000 TL ve üzeri vade farksız (World 2-7 taksit); taksitler sayfasında online 5.000 TL, mağaza 10.000 TL eşiği yazıyor", "Help page: interest-free above 10,000 TL (World 2-7 instalments); the instalments page states 5,000 TL online and 10,000 TL in store", "Koçtaş Kart", "Koçtaş Card", "Yok", "Not available", "Bulunamadı", "Not found"),
       ("bauhaus.com.tr", "2.500 TL ve üzeri anlaşmalı kartlarla vade farksız", "2,500 TL and above interest-free with partner cards", "Bulunamadı", "Not found", "Havale / EFT", "Bank transfer", "Kurumsal kart", "Corporate card"),
       ("ikea.com.tr", "1.500 TL üzeri 3 taksit; IKEA Aile üyelerine 7.500 TL üzeri 6, 20.000 TL üzeri 9 taksit", "3 instalments above 1,500 TL; IKEA Family 6 above 7,500 TL, 9 above 20,000 TL", "Bulunamadı", "Not found", "Yok", "Not available", "IKEA Kurumsal Kart", "IKEA Corporate Card"),
       ("shop.creavit.com.tr", "Peşin fiyatına 6 ve 9 taksit ifadeleri birlikte", "6 and 9 instalments at cash price shown together", "Bulunamadı", "Not found", "Bulunamadı", "Not found", "Bulunamadı", "Not found"),
       ("banyomarka.com", "Ürün kartında 4 taksit", "4 instalments on the product card", "Bulunamadı", "Not found", "İstanbul içi kapıda nakit", "Cash on delivery within Istanbul", "Bulunamadı", "Not found"),
       ("banyoline.com", "Şeritte peşin fiyatına 12 ay taksit", "Banner: 12 months at cash price", "Bulunamadı", "Not found", "Bulunamadı", "Not found", "Bulunamadı", "Not found"),
       ("hepsiburada.com", "12 aya varan taksit (platform limiti; doğrulanamadı)", "Up to 12 instalments (platform limit; unverified)", "Var", "Available", "Uygun ürünlerde kapıda ödeme (doğrulanamadı)", "Cash on delivery on eligible products (unverified)", "Mümkün (doğrulanamadı)", "Possible (unverified)"),
       ("trendyol.com", "Taksit yapılabilen ürünlerde seçenek sunuluyor; her üründe yok", "Offered on products where instalments are enabled; not on every product", "500 TL üzeri sepette 36 aya kadar", "Up to 36 months on baskets above 500 TL", "Yok (kapıda ödeme ve havale yok)", "None (no cash on delivery or transfer)", "Mümkün (doğrulanamadı)", "Possible (unverified)"),
       ("n11.com", "Banka bazlı taksit; vade farksız koşul belirtilmemiş", "Bank-based instalments; interest-free terms not stated", "750-15.000 TL arası, 48 aya kadar", "750-15,000 TL, up to 48 months", "Yok", "Not available", "Bulunamadı", "Not found")]
T_TAK = tablo([th("Site", "Site", "Ödeme ve taksit sayfası okunan site; bağlantı ana sayfaya gider.", "Site whose payment and instalment page was read; link opens the home page."),
               th("Taksit ve vade farksız koşul", "Instalments and interest-free terms", "Sitenin yardım, taksit veya ödeme rehberi sayfasındaki ifade; 29.09.2026.", "Statement on the site's help, instalment or payment guide page; 29.09.2026."),
               th("Alışveriş kredisi", "Consumer credit", "Sitede alışveriş kredisi veya mağaza kartı seçeneği.", "Consumer credit or store card option on the site."),
               th("Kapıda ödeme / havale", "Cash on delivery / transfer", "Kredi kartı dışındaki ödeme yolları.", "Payment routes other than credit card."),
               th("Kurumsal fatura", "Corporate invoice", "Kurumsal fatura veya kurumsal kart seçeneği.", "Corporate invoice or corporate card option.")],
              [[sl(a), x(b, c), x(d, e), x(f, g), x(h, i)] for a, b, c, d, e, f, g, h, i in TAK], "uzun")
KAR = [("vitra.com.tr", "Eşiksiz ücretsiz kargo", "Free shipping, no threshold", "3 iş günü içinde kargoya; ürün sayfasında tahmini tarih", "Shipped within 3 working days; estimated date on product page", "30 gün (ürün sayfasında; iade rehberinde gün yazmıyor)", "30 days (on product page; the returns guide gives no number)", "Sitede fiyatlı 11 montaj kalemi ve keşif: klozet 2.750 TL, banyo mobilyası seti 4.000 TL, keşif 1.400 TL; ücretsiz montaj listesinde 89 ürün, 40.000 TL üzeri kampanyada ücretsiz", "11 priced installation items and a survey on site: WC 2,750 TL, bathroom furniture set 4,000 TL, survey 1,400 TL; 89 products on the free-installation list, free above 40,000 TL in campaign"),
       ("shop.creavit.com.tr", "3.000 TL üzeri", "Above 3,000 TL", "5 iş günü içinde kargoya", "Shipped within 5 working days", "30 gün", "30 days", "11 kalem: klozet 2.450 TL, armatür 1.750 TL, boy dolabı 1.400 TL", "11 items: WC 2,450 TL, tap 1,750 TL, tall cabinet 1,400 TL"),
       ("bauhaus.com.tr", "1.000 TL ve üzeri (seçili ürün); 40.000 TL üzeri şehir içi nakliye", "1,000 TL and above (selected products); city delivery above 40,000 TL", "30 desi üstü lojistik firması; adalar kapsam dışı", "Above 30 desi via logistics firm; islands excluded", "14 gün; klozet takımında ambalaj açılmamış şartı", "14 days; unopened packaging condition for WC sets", "Usta temini müşteri hizmetleri üzerinden", "Installer via customer service"),
       ("ikea.com.tr", "Eşik yok; kargo 299-799 TL, üstü %11", "No threshold; delivery 299-799 TL, 11% above", "Daire kapısına teslim", "Delivery to apartment door", "İnternet 14 gün, mağaza 30 gün", "Online 14 days, store 30 days", "Sepette montaj; bölgeye göre fiyat; 2 yıl kurulum garantisi", "Assembly in basket; regional price; 2-year installation warranty"),
       ("koctas.com.tr", "300 TL ve üzeri; altı 49,90 TL", "300 TL and above; 49.90 TL below", "Ürün sayfasındaki tarih aralığı; 30 desi üstü lojistikle kata teslim, altı apartman kapısına", "Date range on the product page; above 30 desi delivered to the floor by logistics, below to the building door", "14 gün; iade kodu 7 gün; montajı yapılmış demonte ürün ve ambalajı açılmış klozet takımı iade dışı", "14 days; return code valid 7 days; assembled flat-pack products and opened WC sets excluded", "Koçtaş ve Koçtaş Fix illerinde ücretli montaj, 2 yıl işçilik garantisi; söküm ek ücretli", "Paid installation in Koçtaş and Koçtaş Fix provinces, 2-year labour warranty; removal charged extra"),
       ("banyoline.com", "Tüm alışverişlerde ücretsiz", "Free on all orders", "Bölgeye bağlı, 30 günü aşmaz", "Regional, within 30 days", "İptal ve iade formu", "Cancellation and return form", "İstanbul'da ücretsiz montaj: VitrA Metropole Edge, Valarte, Nest Trendy, Sento, Root", "Free installation in Istanbul: VitrA Metropole Edge, Valarte, Nest Trendy, Sento, Root"),
       ("hepsiburada.com", "Eşik herkese açık sayfada yok; Bugün Kapında 54,90 TL, Yarın Kapında 49,90 TL (Premium ücretsiz)", "Threshold not on public pages; same-day 54.90 TL, next-day 49.90 TL (free with Premium)", "Mobilya birden fazla pakette, HepsiJET XL; büyük ürün iadesi adresten randevuyla", "Furniture in several parcels, HepsiJET XL; bulky returns collected by appointment", "14 gün, demonte ve orijinal kutu; Kapında İade ücretsiz", "14 days, disassembled in original box; free doorstep return", "69 ilde sepete eklenebilir montaj; klozet montajı 2.730 TL (Mr Usta); tekrar kurulumda servis bedeli", "Installation addable in 69 provinces; WC installation 2,730 TL (Mr Usta); service fee for re-installation"),
       ("trendyol.com", "Genel eşik yok; standart kargo 59,99 TL, \"kargo bedava\" etiketli ürünlerde ücretsiz", "No general threshold; standard shipping 59.99 TL, free on \"free shipping\" labelled products", "30 desi üstü lojistikle (Horoz, Ceva) kata teslim", "Above 30 desi delivered to the floor by logistics (Horoz, Ceva)", "15 gün; kurulum gerektiren ürün yetkili servis dışında açılırsa iade dışı", "15 days; products needing installation are excluded if opened outside authorised service", "Ürün sayfasında ek montaj hizmeti; 30 gün içinde randevu", "Add-on installation on product page; appointment within 30 days")]
T_KAR = tablo([th("Site", "Site", "Teslimat, iade ve montaj sayfaları okunan site.", "Site whose delivery, returns and installation pages were read."),
               th("Ücretsiz kargo", "Free shipping", "Ücretsiz kargo eşiği.", "Free shipping threshold."),
               th("Büyük ürün teslimat", "Bulky delivery", "Klozet, dolap, duşakabin gibi büyük ürünlerde teslimat süresi ve yöntemi.", "Delivery time and method for bulky products such as WCs, cabinets and shower enclosures."),
               th("İade", "Returns", "İade süresi ve büyük ürün koşulu.", "Return period and bulky product condition."),
               th("Montaj", "Installation", "Montaj seçeneği, kapsamı ve fiyatı; 29.09.2026.", "Installation option, scope and price; 29.09.2026.")],
              [[sl(a), x(b, c), x(d, e), x(f, g), x(h, i)] for a, b, c, d, e, f, g, h, i in KAR], "uzun")
GAR = [("VitrA", "vitra.com.tr", "Ürün sayfalarında süre yazmıyor; V-Care 2 yıl (+2 yıl paket); ek garanti sayfası var", "No period on product pages; V-Care 2 years (+2 with package); extended warranty page exists", "Ayrı yedek parça sayfası bulunamadı; iç takım ve tamamlayıcı ürün kategorileri var", "No separate spare-part page found; inner mechanism and complementary product categories exist", "Online servis randevusu, garanti talep formu, 0850 hattı, WhatsApp düğmesi", "Online service appointment, warranty form, 0850 line, WhatsApp button"),
       ("Kale", "kale.com.tr", "Seramik sağlık gereçleri ve armatür 10 ve 5 yıl, musluk 2, duş sistemi ve gömme rezervuar 5, klozet kapağı ve banyo mobilyası 2 yıl; servis işçiliği 1 yıl", "Sanitaryware and taps 10 and 5 years, valves 2, shower systems and concealed cisterns 5, toilet seats and bathroom furniture 2; service labour 1 year", "Ayrı sayfa yok; kullanım kılavuzları", "No separate page; user manuals", "Yetkili servis sayfası, 0850 hattı, WhatsApp destek", "Authorised service page, 0850 line, WhatsApp support"),
       ("Creavit", "creavit.com.tr", "Seramik sağlık gereçleri için 12 yıl; ayrıca 2 yıllık garanti belgesi (PDF, ürün grubu belirtilmemiş)", "12 years for sanitaryware; also a 2-year warranty document (PDF, product group not stated)", "Sitede yedek parça girişi bulunamadı", "No spare-part entry found on the site", "Yetkili servis sayfası, e-mağaza hattı", "Authorised service page, e-store line"),
       ("E.C.A.", "eca.com.tr", "Ürün sayfasında 20 yıl (Life lavabo bataryası)", "20 years on the product page (Life basin tap)", "Ürün sayfasında yedek parça resmi", "Spare-part drawing on the product page", "Servis haritası, 444 hattı, WhatsApp", "Service map, 444 line, WhatsApp"),
       ("Geberit", "geberit.com.tr", "Garanti koşulları PDF olarak medya merkezinde; süre sayfada yazmıyor", "Warranty terms as a PDF in the media centre; period not stated on the page", "Ayrı yedek parça sayfası bulunamadı; bayi ve yetkili servis üzerinden", "No separate spare-part page found; via dealers and authorised service", "Bayi ve servis sayfası, 0850 hattı", "Dealer and service page, 0850 line"),
       ("Grohe", "grohe.com", "Seçili ürünlerde 10 yıla kadar; 2 yıl (+1 kayıtla) ve 5 yıl", "Up to 10 years on selected products; 2 years (+1 with registration) and 5 years", "Yedek parça bulucu; garanti kapsamında 48 saatte teslim", "Spare-part finder; 48-hour delivery under warranty", "Servis talebi formu, bayi bulucu", "Service request form, dealer finder")]
T_GAR = tablo([th("Marka", "Brand", "Garanti ve servis sayfaları okunan marka; bağlantı sitesine gider.", "Brand whose warranty and service pages were read; link opens the site."),
               th("Garanti süresi", "Warranty period", "Sitede yazılı garanti süresi.", "Warranty period stated on the site."),
               th("Yedek parça", "Spare parts", "Yedek parça sayfası, aracı veya listesi.", "Spare-part page, tool or list."),
               th("Servis ve iletişim", "Service and contact", "Servis randevu akışı, telefon ve anlık mesaj kanalı.", "Service appointment flow, phone and instant messaging channel.")],
              [[sl(d, a), x(b, c), x(e, f), x(g, h)] for a, d, b, c, e, f, g, h in GAR])
SOS = [("VitrA Türkiye", "~144K", "1,58M · 402 video · 55,8M", "1.58M · 402 videos · 55.8M", "1.478 + 3.825 (iki hesap)", "1,478 + 3,825 (two accounts)", "Yok", "Not available"),
       ("Artema", "~20K", "4,75K · 33 video · 19,7M", "4.75K · 33 videos · 19.7M", "3.825 (ortak hesap)", "3,825 (shared account)", "Yok", "Not available"),
       ("Grohe (global kanal)", "-", "75,1K · 627 video · 21,9M", "75.1K · 627 videos · 21.9M", "10.325", "10,325", "Yok", "Not available"),
       ("Geberit Türkiye", "~39K", "Ayrı TR kanalı yok", "No separate TR channel", "Yok", "Not available", "Yok", "Not available"),
       ("E.C.A.", "~24K", "Ayrı TR kanalı yok", "No separate TR channel", "Yok", "Not available", "Yok", "Not available"),
       ("Creavit", "-", "2,17K · 227 video · 7,1M", "2.17K · 227 videos · 7.1M", "187", "187", "118 takipçi", "118 followers"),
       ("Kale", "-", "948 · 577 video · 1,4M", "948 · 577 videos · 1.4M", "943", "943", "Yok", "Not available")]
T_SOS = tablo([th("Marka", "Brand", "Kanal büyüklükleri karşılaştırılan marka.", "Brand whose channel sizes are compared."),
               th("Instagram", "Instagram", "Takipçi; profil girişe kapalı olduğu için Google sonuç özetinden, yaklaşık. \"-\" alınamadı.", "Followers; approximate, from the Google result snippet since the profile is login-gated. \"-\" not available."),
               th("YouTube", "YouTube", "Abone, video ve toplam görüntüleme; kanal hakkında sayfası, 29.09.2026.", "Subscribers, videos and total views; channel about page, 29.09.2026."),
               th("Pinterest", "Pinterest", "Profil takipçisi.", "Profile followers."),
               th("TikTok", "TikTok", "Resmi hesap ve takipçi.", "Official account and followers.")],
              [[veri_m(a), veri_m(b), x(c, d), x(e, f), x(g, h)] for a, b, c, d, e, f, g, h in SOS])
IL = tablo([th("İl", "Province", "Google Maps'te VitrA etiketli satış noktası profillerinin ili.", "Province of VitrA-labelled sales point profiles on Google Maps."),
            th("Profil", "Profiles", "Tekil profil sayısı (cid ile).", "Number of unique profiles (by cid).", True),
            th("Toplam yorum", "Total reviews", "Profillerin toplam yorum sayısı.", "Total reviews of the profiles.", True),
            th("Ortalama puan", "Average rating", "Yorum ağırlıklı ortalama puan.", "Review-weighted average rating.", True)],
           [[veri_m(r["il"]), cell(r["satis_noktasi"]), cell(r["toplam_yorum"]), n(f1(r["ortalama_puan_yorum_agirlikli"]))] for r in GB["il_dagilimi"][:8]], "dar")
HTML = """
<p class="lede">%s</p>
<div class="kpis">%s%s%s%s</div>
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
%s
%s
<h3>%s</h3>
<div class="two"><div>%s</div><div>%s</div></div>
%s
<h3>%s</h3>
%s
%s
""" % (
 x("VitrA'nın ve rakiplerinin kamuya açık ödeme, teslimat, iade, montaj ve garanti koşulları ile sosyal kanal, Google Business Profile ve Google Shopping görünürlüğü karşılaştırılmıştır. Değerler 29-30.09.2026 tarihlerinde sitelerden okunmuştur. \"Bulunamadı\" bilginin sayfada görünmediğini gösterir, bulunmadığı anlamına gelmeyebilir.",
   "The public payment, delivery, returns, installation and warranty terms of VitrA and its competitors, together with social channel, Google Business Profile and Google Shopping visibility, were compared. Values were read from the sites on 29-30.09.2026. \"Not found\" means the information was not visible on the page, not necessarily that it does not exist."),
 kpi_kart("0 / 15", "Google TR mobil sonuçlarında Shopping veya ürün bloğu çıkan kategori kelimesi", "Category keywords with a Shopping or product block in Google TR mobile results", "hi"),
 kpi_kart("3", "vitra.com.tr'de taksit bilgisinin farklı biçimde yer aldığı yüzey (şeritte vade farksız 6 ay, kampanyada seçili ürünlerde 9, ürün tablosunda vade farklı dahil 12)", "Surfaces on vitra.com.tr where instalment information appears in different forms (6 months interest-free in the banner, 9 on selected products in the campaign, up to 12 including interest-bearing options in the product table)", "hi"),
 kpi_kart(k(M["kayit"]), "Google Maps'te VitrA etiketli satış noktası profili · %s yorum, ortalama %s" % (bin(M["toplam_yorum"]), f1(M["ortalama_puan_yorum_agirlikli"])), "VitrA-labelled sales point profiles on Google Maps · %s reviews, average %s" % (f"{M['toplam_yorum']:,}", "%.1f" % M["ortalama_puan_yorum_agirlikli"]), "up"),
 kpi_kart("1,58M", "VitrA Türkiye YouTube abonesi · rakiplerin toplamının üzerinde", "VitrA Türkiye YouTube subscribers · above the total of the competitors", "up"),
 x("Ödeme ve taksit koşulları", "Payment and instalment terms"), T_TAK,
 insight("VitrA sitesinde taksit bilgisi üç yüzeyde farklı biçimde yer almaktadır: şeritte tüm ürünlerde vade farksız 6 ay, kampanya sayfasında seçili ürünlerde 9 aya varan taksit, ürün tablosunda vade farklı seçenekler dahil 12 taksite kadar; vade farksız ve vade farklı seçeneklerin ve kampanya kapsamının aynı ifadeyle gösterilmesi karar anındaki belirsizliği azaltabilir. Rakiplerde vade farksız taksit tutar eşiğine bağlıdır (Koçtaş online 5.000 TL, mağazada 10.000 TL; Bauhaus 2.500 TL; IKEA 1.500 TL); VitrA şeridi eşik belirtmemektedir. Alışveriş kredisi mağaza kartı dışında yalnızca pazaryerlerinde bulunmaktadır (Hepsiburada; n11'de 48 aya kadar; Trendyol'da 500 TL üzeri sepette 36 aya kadar); markalı sitelerin hiçbirinde görülmemiştir. Kapıda ödeme Banyomarka'da (İstanbul içi) bulunmakta, Hepsiburada'da uygun ürünlerde sunulduğu belirtilmektedir; Koçtaş, Trendyol ve n11 kapıda ödeme sunmamaktadır.",
         "Instalment information on the VitrA site appears differently on three surfaces: 6 months interest-free on all products in the banner, up to 9 instalments on selected products on the campaign page, and up to 12 including interest-bearing options in the product table; showing interest-free and interest-bearing options and the campaign scope in one consistent wording can reduce uncertainty at the moment of decision. At competitors interest-free instalments depend on an amount threshold (Koçtaş 5,000 TL online and 10,000 TL in store; Bauhaus 2,500 TL; IKEA 1,500 TL); the VitrA banner states no threshold. Apart from store cards, consumer credit exists only on marketplaces (Hepsiburada; n11 up to 48 months; Trendyol up to 36 months on baskets above 500 TL); none of the brand sites offers it. Cash on delivery is available at Banyomarka (within Istanbul) and is stated to be offered on eligible products at Hepsiburada; Koçtaş, Trendyol and n11 do not offer it.", "D23", "D28"),
 x("Kargo, teslimat, iade ve montaj", "Shipping, delivery, returns and installation"), T_KAR,
 insight("VitrA eşiksiz ücretsiz kargo ve ürün sayfasında 30 gün ücretsiz iade ile karşılaştırılan sitelerin çoğundan geniş bir vaat taşımaktadır (Bauhaus 1.000 TL, Creavit 3.000 TL, Koçtaş 300 TL eşik; IKEA ücretli kargo; iade Bauhaus, IKEA, Koçtaş ve Hepsiburada'da 14 gün). İade rehberi sayfasında gün sayısı yazmamakta, süre yalnızca ürün sayfasında görünmektedir. Sitedeki \"3 iş günü içinde kargoya\" ifadesi, pazaryeri operasyonundaki ortalama 31,7 saatlik kargoya teslim süresinden (Bölüm [[b:panel]]) daha temkinlidir. Klozet gibi ürünlerde iade koşulu Bauhaus ve Koçtaş'ta açık yazılıdır (ambalaj açılmamış ve denenmemiş; Koçtaş'ta montajı yapılmış demonte ürün iade dışı); VitrA sayfalarında klozete özel koşul ve kurulum sonrası iade kuralı bulunamamıştır. Montajda Creavit e-mağazası klozet için 2.450 TL, VitrA 2.750 TL istemektedir; Banyoline ise İstanbul'da VitrA'nın Metropole Edge, Valarte, Nest Trendy, Sento ve Root serilerine ücretsiz montaj vermektedir.",
         "With free shipping without a threshold and 30-day free returns on the product page, VitrA carries a broader promise than most compared sites (Bauhaus 1,000 TL, Creavit 3,000 TL and Koçtaş 300 TL thresholds; IKEA paid delivery; 14-day returns at Bauhaus, IKEA, Koçtaş and Hepsiburada). The returns guide page gives no number of days; the period appears only on the product page. The site's \"shipped within 3 working days\" wording is more cautious than the average 31.7-hour handover to the carrier in marketplace operations (Section [[b:panel]]). For products such as WCs the return condition is explicit at Bauhaus and Koçtaş (unopened and untested; at Koçtaş assembled flat-pack products are excluded); no WC-specific condition or post-installation return rule was found on VitrA pages. For installation the Creavit e-store charges 2,450 TL for a WC, VitrA 2,750 TL; Banyoline gives free installation in Istanbul for VitrA's Metropole Edge, Valarte, Nest Trendy, Sento and Root series.", "D23", "D28"),
 x("Garanti, yedek parça ve servis iletişimi", "Warranty, spare parts and service contact"), T_GAR,
 insight("E.C.A. (20 yıl), Kale (10 ve 5 yıl tablosu) ve Grohe (10 yıla kadar, garanti kapsamında 48 saatte yedek parça) garanti sürelerini açık yazmaktadır; VitrA ürün sayfalarında süre bilgisi bulunamamıştır, yalnızca V-Care ve ek garanti paketi için vardır. Yedek parça yüzeyi E.C.A.'da ürün sayfasında (yedek parça resmi), Grohe'de araçla (parça bulucu) mevcuttur; Creavit ve Geberit TR sitelerinde de VitrA gibi ayrı bir yedek parça girişi bulunamamıştır. WhatsApp kanalı Kale, E.C.A., Banyomarka ve VitrA'da bulunmaktadır; VitrA'nın güçlü yönü online servis randevusu ve 76 servis noktasıdır.",
         "E.C.A. (20 years), Kale (10 and 5-year table) and Grohe (up to 10 years, spare parts within 48 hours under warranty) state warranty periods explicitly; no period information was found on VitrA product pages, only for V-Care and the extended warranty package. The spare-part surface exists at E.C.A. on the product page (spare-part drawing) and at Grohe as a tool (part finder); like VitrA, the Creavit and Geberit TR sites have no separate spare-part entry either. A WhatsApp channel exists at Kale, E.C.A., Banyomarka and VitrA; VitrA's strength is the online service appointment and 76 service points.", "D23", "D28"),
 x("Sosyal ve keşif kanalları", "Social and discovery channels"), T_SOS,
 insight("YouTube'da VitrA 1,58M abone ve 55,8M görüntülemeyle karşılaştırılan markaların belirgin biçimde önündedir; Instagram'da yaklaşık 144K takipçiyle takipçi sayısı okunabilen markalar içinde ilk sıradadır. Pinterest hesapları küçüktür (1.478 ve 3.825 takipçi) ve markasız banyo aramalarında (banyo dolabı modelleri, küçük banyo dekorasyonu, modern banyo tasarımları) VitrA pini görünmemektedir; bu aramalarda banyo markaları genel olarak yoktur. TikTok'ta VitrA ve Artema için resmi hesap bulunamamıştır. YouTube abone avantajı, YouTube bölümünde (Bölüm [[b:youtube]]) görülen tamir ve kurulum videosu boşluğuyla birlikte okunduğunda kullanılmayan bir dağıtım gücüne işaret etmektedir.",
         "On YouTube VitrA is clearly ahead of the compared brands with 1.58M subscribers and 55.8M views, and with about 144K followers it also leads on Instagram. Its Pinterest accounts are small (1,478 and 3,825 followers) and no VitrA pin appears in unbranded bathroom searches (bathroom cabinet models, small bathroom decoration, modern bathroom designs); bathroom brands are generally absent from these searches. No official TikTok account was found for VitrA or Artema. Read together with the repair and installation video gap seen in the YouTube section (Section [[b:youtube]]), the YouTube subscriber advantage points to unused distribution power.", "D23"),
 x("Google Business Profile: mağaza ve servis noktaları", "Google Business Profile: stores and service points"),
 IL,
 marks([("at", "%s profilin %s'ünde puan ve yorum var; medyan yorum %s, %s profilde 10'dan az yorum, %s profilde puan 4,0'ın altında" % (M["kayit"], M["puanli_kayit"], M["medyan_yorum"], M["yorum_10_alti"], M["puan_4_alti"]), "%s of %s profiles have a rating and reviews; median %s reviews, %s profiles with fewer than 10 reviews, %s profiles below 4.0" % (M["puanli_kayit"], M["kayit"], M["medyan_yorum"], M["yorum_10_alti"], M["puan_4_alti"])),
        ("up", "Yetkili servis: %s profil, %s yorum, ortalama %s" % (SV["kayit"], bin(SV["toplam_yorum"]), f1(SV["ortalama_puan_yorum_agirlikli"])), "Authorised service: %s profiles, %s reviews, average %s" % (SV["kayit"], f"{SV['toplam_yorum']:,}", SV["ortalama_puan_yorum_agirlikli"])),
        ("at", "Profil adları tutarsız (\"VitrA - Artema - bayi\", büyük harfli, yalnız marka adı); %s profilde web sitesi alanı başka adres, %s profilde boş" % (GB["vitra_web_alani"]["diger"], GB["vitra_web_alani"]["web_yok"]), "Profile names are inconsistent (\"VitrA - Artema - dealer\", all caps, brand name only); %s profiles carry another address in the website field, %s are empty" % (GB["vitra_web_alani"]["diger"], GB["vitra_web_alani"]["web_yok"])),
        ("up", "Resmi mağaza bulucuda 161 satış ve 76 servis noktası; Maps'teki 262 profil bayi ve mükerrer kayıtları da içermektedir", "The official store finder lists 161 sales and 76 service points; the 262 Maps profiles also include dealer and duplicate records")]),
 insight("Mağaza profillerinin yorum ağırlıklı ortalaması 4,5'tir ve İstanbul 64 profil, 3.732 yorumla merkezdedir. Profil adı ve kategori standardı, web sitesi alanının vitra.com.tr mağaza sayfasına bağlanması ve düşük yorumlu 123 profilde yorum toplama desteği, Banyo Asistanı'nın mağaza görüşmesi adımını besleyen yerel görünürlüğü güçlendirebilir.",
         "The review-weighted average of store profiles is 4.5 and Istanbul is the centre with 64 profiles and 3,732 reviews. A naming and category standard, linking the website field to the vitra.com.tr store page and review collection support for the 123 low-review profiles can strengthen the local visibility that feeds the store appointment step of the Bathroom Assistant.", "D23"),
 x("Google Shopping ve ürün bloğu", "Google Shopping and product blocks"),
 insight("15 kategori kelimesinin hiçbirinde, mobil ve masaüstünde, organik sonuç sayfasında Shopping veya ürün bloğu (popular products, product considerations) görünmemiştir (Shopping sekmesi ayrıca Bölüm [[b:fiyat]]'da incelenmiştir); 10 ek kontrol sorgusunda da yoktur. Ürün keşfi organik sonuçlardaki Trendyol, Akakçe, Koçtaş ve Amazon TR sayfalarına gitmektedir. Yerel paket mobilde 8, masaüstünde 1 kelimede; AI Overview mobilde 4, masaüstünde 8 kelimede çıkmaktadır; vitra.com.tr mobil ilk 10'da 7 kelimede yer almaktadır. Bu tabloda ürün feed'inin Google Merchant Center üzerinden ücretsiz listelemelere açık tutulması, blok göründüğü anda hazır olmayı sağlayabilir; bugün için öncelik organik kategori sayfaları ve pazaryeri listelemeleridir.",
         "In none of the 15 category keywords, on mobile or desktop, did a Shopping or product block (popular products, product considerations) appear on the organic results page (the Shopping tab is examined separately in Section [[b:fiyat]]); nor in 10 additional control queries. Product discovery goes to Trendyol, Akakçe, Koçtaş and Amazon TR pages in the organic results. The the local pack appears for 8 keywords on mobile and 1 on desktop; AI Overview for 4 on mobile and 8 on desktop; vitra.com.tr is in the mobile top 10 for 7 keywords. In this picture keeping the product feed open to free listings via Google Merchant Center can ensure readiness when the block appears; for now the priority is organic category pages and marketplace listings.", "D23", "D19"),
 kaynak("Site yardım, ödeme, teslimat, iade, garanti ve servis sayfaları (29.09.2026) · YouTube ve Pinterest profil sayfaları · Google sonuç özetleri (Instagram, TikTok) · Google Maps (103 sorgu) · Google TR mobil ve masaüstü sonuç sayfası (15 + 10 kelime)",
        "Site help, payment, delivery, returns, warranty and service pages (29.09.2026) · YouTube and Pinterest profile pages · Google result snippets (Instagram, TikTok) · Google Maps (103 queries) · Google TR mobile and desktop results pages (15 + 10 keywords)", "D23"),
)
