# -*- coding: utf-8 -*-
"""Bolum: Yontem ve kapsam."""
from ortak import *
from ortak import _J
import serp_ozet as _SO
_YT = _J("islenmis", "yorum_analiz.json")["toplam"]
HTML = """
<p class="lede">%s</p>
%s
""" % (
 x("Veri kaynaklarına, dönemlerine ve yöntem notlarına aşağıda yer verilmektedir.", "Data sources, periods and method notes are listed below."),
 tablo([th("Veri kaynağı", "Data source", "Kullanılan kaynak.", "Source used."),
        th("Kapsam", "Scope", "Dönem, coğrafya ve örneklem.", "Period, geography and sample."),
        th("Kullanıldığı bölüm", "Used in section", "Verinin işlendiği bölüm.", "Section where the data is processed."),
        th("Not", "Note", "Ölçüm sınırı veya yöntem notu.", "Measurement limit or method note.")],
       [[x("Google Ads Keyword Planner", "Google Ads Keyword Planner"), x("2.349 tekil kelime · Türkiye, Türkçe · aylık hacim Eyl 2022 - Ağu 2026 (talep grafiğinde Oca 2023 - Ağu 2026)", "2,349 unique keywords · Turkey, Turkish · monthly volume Sep 2022 - Aug 2026 (Jan 2023 - Aug 2026 in the demand chart)"), x("[[b:talep]], [[b:ssgbm]], [[b:ihtiyac]], [[b:model]]", "[[b:talep]], [[b:ssgbm]], [[b:ihtiyac]], [[b:model]]"), x("Google Ads yakın yazım varyantlarına (çoğul, yazım farkı) aynı aylık seriyi döndürür; aynı seriye sahip kelimeler tek kelime olarak sayılmıştır (2.437 satırdan 2.349 tekil kelime); birleşen varyantlarda Türkçe ve yaygın yazım gösterilir (banyo batarya yerine banyo bataryası). Sezonsallık listesinde bulunmayan 19 kategori baş kelimesi (duşakabin, klozet fiyatları, tuvalet fırçası, musluk başlığı vb.) 04.10.2026 tarihinde eklenmiştir", "Google Ads returns the same monthly series for close spelling variants (plurals, misspellings); keywords with an identical series are counted once (2,349 unique keywords from 2,437 rows); merged variants show the Turkish and common spelling (banyo bataryası instead of banyo batarya). 19 category head keywords missing from the seasonality list (duşakabin, klozet fiyatları, tuvalet fırçası, musluk başlığı, etc.) were added on 04.10.2026")],
        [x("Google Search Console", "Google Search Console"), x("sc-domain:vitra.com.tr · 1 Haz 2025 - 25 Eyl 2026 · sayfa, sorgu, cihaz, ülke", "sc-domain:vitra.com.tr · 1 Jun 2025 - 25 Sep 2026 · page, query, device, country"), x("[[b:ihtiyac]], [[b:organik]], [[b:marka]], [[b:serp]], [[b:benchmark]], [[b:model]], [[b:adimlar]]", "[[b:ihtiyac]], [[b:organik]], [[b:marka]], [[b:serp]], [[b:benchmark]], [[b:model]], [[b:adimlar]]"), x("Sayfa ve sorgu raporları ilk 25.000 satırla sınırlıdır; sayfa×gün tablosu 100.000 satır", "Page and query reports are limited to the top 25,000 rows; the page×day table to 100,000 rows")],
        [x("Google Autocomplete", "Google Autocomplete"), x("66 kök ifade: \"vitra\" ile başlayan 14 (%s) ve kategori, hizmet, fiyat, rakip marka ve perakendeci için 52 (30.09.2026) · Türkiye, Türkçe, masaüstü Chrome" % veri.TARIH, "66 seed phrases: 14 starting with \"vitra\" (%s) and 52 for categories, services, price, competitor brands and retailers (30.09.2026) · Turkey, Turkish, desktop Chrome" % veri.TARIH), x("[[b:marka]], [[b:model]]", "[[b:marka]], [[b:model]]"), x("Öneriler tek günlük anlık görüntüdür; sıralama Google'ın sırasıdır", "Suggestions are a single-day snapshot; the order is Google's")],
        [x("YouTube arama", "YouTube search"), x("30 ifade · Türkiye · ilk sayfa · %s" % veri.TARIH, "30 phrases · Turkey · first page · %s" % veri.TARIH), x("[[b:youtube]]", "[[b:youtube]]"), x("İzlenme sayıları video yayın tarihinden itibaren kümülatiftir", "View counts are cumulative from the video's publication date")],
        [x("Ahrefs Site Explorer", "Ahrefs Site Explorer"), x("Organik rakipler ve Batch Analysis · Türkiye · 27.09.2026", "Organic competitors and Batch Analysis · Turkey · 27.09.2026"), x("[[b:rakip]]", "[[b:rakip]]"), x("Organik ve paid trafik değerleri Ahrefs tahminidir; gerçek ziyaret sayısı değildir", "Organic and paid traffic values are Ahrefs estimates, not actual visit counts")],
        [x("Google Ads keyword ideas", "Google Ads keyword ideas"), x("10 kök ifade grubu, 52.973 kelime · 48 ay (Eyl 2022 - Ağu 2026)", "10 seed groups, 52,973 keywords · 48 months (Sep 2022 - Aug 2026)"), x("[[b:ssgbm]], [[b:katalog]], [[b:yeni]], [[b:set]]", "[[b:ssgbm]], [[b:katalog]], [[b:yeni]], [[b:set]]"), x("Kelimeler 58 temalı sözlükle sınıflandırılmış, gürültü ifadeleri ayıklanmış, aynı aylık seriyi taşıyan yazım varyantları tek sayılmıştır; tema toplamları yaklaşık büyüklük gösterir", "Keywords were classified with a 58-theme dictionary, noise phrases removed, and spelling variants with the same monthly series counted once; theme totals indicate approximate size")],
        [x("vitra.com.tr ürün sitemap'i ve site incelemesi", "vitra.com.tr product sitemap and site review"), x("7.804 ürün adresi · hizmet, kategori ve ürün sayfaları · Banyo Asistanı · %s" % veri.TARIH, "7,804 product URLs · service, category and product pages · Bathroom Assistant · %s" % veri.TARIH), x("[[b:katalog]], [[b:set]], [[b:benchmark]], [[b:model]]", "[[b:katalog]], [[b:set]], [[b:benchmark]], [[b:model]]"), x("Ürün sayısı renk ve ölçü varyantlarını ayrı sayar; model sayısı renk ekleri ayıklanarak yaklaşık hesaplanmıştır", "Product counts include colour and size variants separately; model counts are approximated by removing colour suffixes")],
        [x("Rakip kategori sitemap'leri", "Competitor category sitemaps"), x("Bauhaus, IKEA, Tekzen, Evidea, Banyomarka, Kale, Banyoline · Koçtaş tarayıcı ile", "Bauhaus, IKEA, Tekzen, Evidea, Banyomarka, Kale, Banyoline · Koçtaş via browser"), x("[[b:yeni]], [[b:benchmark]]", "[[b:yeni]], [[b:benchmark]]"), x("Kategori varlığı gözlemidir; ürün derinliği ve satış hacmi ölçülmemiştir", "An observation of category presence; product depth and sales volume were not measured")],
        [x("Trendyol arama sonuçları", "Trendyol search results"), x("13 tema, ilk 40-45 ürün · %s" % veri.TARIH, "13 themes, top 40-45 products · %s" % veri.TARIH), x("[[b:ssgbm]], [[b:katalog]], [[b:yeni]]", "[[b:ssgbm]], [[b:katalog]], [[b:yeni]]"), x("Değerlendirme sayısı satış hacmine yaklaşık gösterge olarak kullanılmıştır; sonuç sırası kişiselleştirmeye bağlı olarak değişebilir", "Review count is used as an approximate indicator of sales volume; result order may vary with personalisation")],
        [x("Rakip ve benzer oyuncuların siteleri", "Websites of competitors and comparable players"), x("Koçtaş, IKEA, Hepsiburada, Kale, Banyomarka, Bauhaus, Home Depot, Kohler, Villeroy & Boch, Duravit, Hansgrohe, Grohe, Geberit, Victorian Plumbing", "Koçtaş, IKEA, Hepsiburada, Kale, Banyomarka, Bauhaus, Home Depot, Kohler, Villeroy & Boch, Duravit, Hansgrohe, Grohe, Geberit, Victorian Plumbing"), x("[[b:set]], [[b:benchmark]]", "[[b:set]], [[b:benchmark]]"), x("Hizmet ve kampanya koşulları erişim tarihindeki haliyle aktarılmıştır", "Service and campaign terms are reported as of the access date")],
        [x("Inbound sezonsallık ve rakip ürün analizi", "Inbound seasonality and competitor product analysis"), x("Haziran 2026 · Ahrefs content gap, 4.202 kelime, 7 rakip", "June 2026 · Ahrefs content gap, 4,202 keywords, 7 competitors"), x("[[b:yeni]]", "[[b:yeni]]"), x("Dört ürün kümesi güncel veriyle yeniden ölçülmüştür", "The four product clusters have been re-measured with current data")],
        [x("Google arama sonuçları", "Google search results"), x("%d kelime: A · VitrA gamı %d (her alt kategoriden en az bir baş kelime), B · yakın kategori fırsatları %d, C · marka ve karşılaştırma %d; Keyword Planner'da hacmi olan · Türkiye, Türkçe, mobil · ilk 20 organik sonuç, AI Overview, PAA · %s" % (_SO.NT, len(_SO.GRUP["A"]), len(_SO.GRUP["B"]), len(_SO.GRUP["C"]), ".".join(reversed(_SO.TARIH.split("-")))), "%d keywords: A · VitrA range %d (at least one head keyword per subcategory), B · adjacent category opportunities %d, C · brand and comparison %d; with Keyword Planner volume · Turkey, Turkish, mobile · top 20 organic results, AI Overview, PAA · %s" % (_SO.NT, len(_SO.GRUP["A"]), len(_SO.GRUP["B"]), len(_SO.GRUP["C"]), ".".join(reversed(_SO.TARIH.split("-"))))), x("[[b:serp]]", "[[b:serp]]"), x("Sıralamalar tek günlük gözlemdir ve gün içinde değişebilir; AI Overview içeriği %d bloğun %s alınabilmiştir" % (len(_SO.AI_GORULEN), ek(len(_SO.AI_ICERIK), "inde")), "Rankings are a single-day observation and may change within the day; AI Overview content could be retrieved for %d of %d blocks" % (len(_SO.AI_ICERIK), len(_SO.AI_GORULEN)))],
        [x("Yapay zeka yanıt takibi", "AI answer tracking"), x("125 soru (111 markasız, 14 VitrA adıyla) · ChatGPT, Gemini ve Google AI Overview · tekrarlı koşu (30 günde soru ve platform başına ortalama 5-7 yanıt), 4 Eyl - 3 Eki 2026; satın alma ve montaj soruları 28.09.2026'dan itibaren", "125 questions (111 without a brand name, 14 naming VitrA) · ChatGPT, Gemini and Google AI Overview · repeated runs (5-7 answers on average per question and platform in 30 days), 4 Sep - 3 Oct 2026; purchase and installation questions from 28.09.2026"), x("[[b:geo]]", "[[b:geo]]"), x("Yanıtlar kişiselleştirilmemiş oturumlardan alınmıştır ve aynı soruya gün içinde farklı yanıt verilebilir; oranlar yön göstericidir", "Answers come from non-personalised sessions and the same question can receive different answers within the day; rates are indicative")],
        [x("YouTube arama ve yorumlar (genişletilmiş)", "YouTube search and comments (extended)"), x("68 ifade · Türkiye · ilk 20 sonuç · 33 videonun 2.218 yorumu · 29.09.2026", "68 phrases · Turkey · top 20 results · 2,218 comments on 33 videos · 29.09.2026"), x("[[b:youtube]]", "[[b:youtube]]"), x("Kanal türü ve yorum teması anahtar ifadelerle atanmıştır; bir yorum birden fazla temaya girebilir", "Channel type and comment theme were assigned by key phrases; a comment may fall into several themes")],
        [x("Ahrefs Site Explorer ve Keywords Explorer (marka siteleri)", "Ahrefs Site Explorer and Keywords Explorer (brand sites)"), x("24 marka ve uzman site top pages ve 69 baş kelimenin sıralama verisi · Türkiye · 28.09.2026; bu bölümdeki arama hacimleri Google Keyword Planner (Eyl 2024 - Ağu 2026)", "Top pages of 24 brand and specialist sites and ranking data for 69 head keywords · Turkey · 28.09.2026; search volumes in this section are from Google Keyword Planner (Sep 2024 - Aug 2026)"), x("[[b:trafik]]", "[[b:trafik]]"), x("Sayfalar URL ve en iyi kelimeye göre temalara eşlenmiştir; listelenen sayfalar site toplamının %66-93'ünü kapsar", "Pages were mapped to themes by URL and top keyword; listed pages cover 66-93% of each site's total")],
        [x("Ahrefs Site Explorer (pazaryeri ve yapı market)", "Ahrefs Site Explorer (marketplaces and DIY retailers)"), x("9 site, banyo kategori sayfaları ve kelimeleri · Türkiye · 28.09.2026", "9 sites, bathroom category pages and keywords · Turkey · 28.09.2026"), x("[[b:pazaryeri]]", "[[b:pazaryeri]]"), x("Kategori trafiği listelenen sayfalarla sınırlıdır ve alt sınır olarak okunmalıdır", "Category traffic is limited to the listed pages and should be read as a lower bound")],
        [x("Trendyol ve Hepsiburada tarayıcı incelemesi", "Trendyol and Hepsiburada browser review"), x("Kategori ağacı, arama önerileri, marka filtreleri, mağaza ve çok satan listeleri · 29.09.2026", "Category tree, search suggestions, brand filters, store and best-seller lists · 29.09.2026"), x("[[b:pazaryeri]]", "[[b:pazaryeri]]"), x("Hepsiburada'da her listede ilk sayfa (36 ürün) okunmuştur; sıralama kişiselleştirmeye bağlı olarak değişebilir", "On Hepsiburada the first page (36 products) of each list was read; order may vary with personalisation")],
        [x("Şikayetvar", "Şikayetvar"), x("VitrA (978) ve Artema (544) marka sayfaları; son 24 ay 600 / 294 şikayetin tam metni · 29.09.2026", "VitrA (978) and Artema (544) brand pages; full text of 600 / 294 complaints from the last 24 months · 29.09.2026"), x("[[b:sikayet]]", "[[b:sikayet]]"), x("Tema ataması anahtar ifadeyle; şikayetler tek taraflı beyandır, paylar yön gösterir; kişisel veriler çıkarılmıştır", "Themes assigned by key phrase; complaints are one-sided statements and shares indicate direction; personal data removed")],
        [x("Google Shopping", "Google Shopping"), x("27 kategori + 3 marka kelimesi × 120 ilan; 24 satıcı listesi · Türkiye, masaüstü · 29.09.2026", "27 category + 3 brand keywords × 120 listings; 24 seller lists · Turkey, desktop · 29.09.2026"), x("[[b:fiyat]]", "[[b:fiyat]]"), x("Mecra medyanı marka ve model karışımından etkilenir; aynı ürün kıyası yalnız satıcı listelerinde", "Channel medians are affected by brand and model mix; like-for-like only in seller lists")],
        [x("Trendyol ve Hepsiburada çok satan ve ürün sayfaları", "Trendyol and Hepsiburada best-seller and product pages"), x("14 kategori × 36 ürün × 2 kanal; 29 VitrA ve Artema ürününde 4 kanal liste fiyatı · 29.09.2026", "14 categories × 36 products × 2 channels; list prices of 29 VitrA and Artema products in 4 channels · 29.09.2026"), x("[[b:fiyat]]", "[[b:fiyat]]"), x("Çok satan sırası platform algoritmasıdır; fiyatlar tek günlük liste fiyatıdır, sepet indirimi ayrıca not edilmiştir; Hepsiburada'da ilk sayfa", "Best-seller order is the platform's algorithm; prices are single-day list prices, basket discounts noted separately; first page on Hepsiburada")],
        [x("Akakçe ve Cimri", "Akakçe and Cimri"), x("29 SKU arama ve ürün sayfası, 12 + 10 kategori sayfası, Cimri 19 ürün sayfası · 30.09.2026", "29 SKU search and product pages, 12 + 10 category pages, 19 Cimri product pages · 30.09.2026"), x("[[b:fiyat]]", "[[b:fiyat]]"), x("Akakçe satıcı listesi ilk 16 satıcıyla sınırlıdır; 10 SKU için Cimri kaydı bulunmamaktadır; paket ve set kayıtları fiyat kıyasına alınmamıştır", "Akakçe seller lists are limited to the first 16 sellers; there is no Cimri record for 10 SKUs; bundle and set records were excluded from the price comparison")],
        [x("Pazaryeri alt kategori taraması", "Marketplace sub-category scan"), x("Trendyol 42, Hepsiburada 40, Akakçe 42 + 8, Cimri 30 kategori (ilk 2 sayfa); 6 rakip mağaza 110 kategori sayfası · 30.09.2026", "Trendyol 42, Hepsiburada 40, Akakçe 42 + 8, Cimri 30 categories (first 2 pages); 6 competitor stores, 110 category pages · 30.09.2026"), x("[[b:derin]]", "[[b:derin]]"), x("Çok satan sırası platform algoritmasıdır; aksesuar karışan listeler işaretlidir; mağazalarda Koçtaş dışında varsayılan sıralama; Kale ve IKEA kapsam dışı", "Best-seller order is the platform's algorithm; lists with mixed accessories are marked; default order at stores other than Koçtaş; Kale and IKEA out of scope")],
        [x("Resmi mağaza panel verisi", "Official store panel data"), x("Trendyol satıcı paneli: satış ve sipariş dağılımı (2025 Q4 - 2026 Q3), favori-görüntüleme (2025, 2026), 1.023 ürün ve 149 satıcı değerlendirmesi, 352 ürün sorusu, 44 Enleri listesi · Hepsiburada: hak ediş, görüntülenme, iptal, değerlendirme · 30.09.2026; ürün bazlı satış raporu, son 12 ay · 02.10.2026", "Trendyol seller panel: sales and order distribution (2025 Q4 - 2026 Q3), favourite-views (2025, 2026), 1,023 product and 149 seller reviews, 352 product questions, 44 Top Lists · Hepsiburada: settlement, views, cancellations, reviews · 30.09.2026; product-level sales report, last 12 months · 02.10.2026"), x("[[b:panel]], [[b:ozet]], [[b:adimlar]]", "[[b:panel]], [[b:ozet]], [[b:adimlar]]"), x("Yalnız resmi mağaza; ciro tutarı verilmez, pay ve oran kullanılır; temalar anahtar kelimeyle; Enleri ekran görüntüsünden okunmuştur", "Official store only; revenue amounts not shown, shares and rates used; themes keyword-based; Top Lists read from screenshots")],
        [x("Rehber içerik, soru sorguları ve marka kayıtları", "Guide content, question queries and brand records"), x("Search Console /ilham-veren-fikirler/ sayfaları ve \"nasıl\", \"su kaçır\" sorguları (1 Eki 2025 - 25 Eyl 2026); Wikidata ve Wikipedia VitrA ve Artema kayıtları; vitra.com.tr llms.txt ve site haritaları · 02.10.2026", "Search Console /ilham-veren-fikirler/ pages and \"nasıl\", \"su kaçır\" queries (1 Oct 2025 - 25 Sep 2026); Wikidata and Wikipedia VitrA and Artema records; vitra.com.tr llms.txt and sitemaps · 02.10.2026"), x("[[b:geo]]", "[[b:geo]]"), x("Rehber sayfaları adres yapısına göre konu gruplarına ayrılmıştır; en az 5 tık alan 93 sayfa değerlendirilmiştir", "Guide pages are grouped by topic from the address structure; the 93 pages with at least 5 clicks are assessed")],
        [x("Alt kategori tamamlayıcı taraması", "Sub-category complementary scan"), x("vitra.com.tr 55 kategori + 3 özel sayfa; Trendyol, Hepsiburada, Akakçe, Cimri aramaları (57 kesit); 6 rakip mağaza araması; 11.982 ürün satırı · 30.09.2026", "vitra.com.tr 55 category + 3 special pages; Trendyol, Hepsiburada, Akakçe, Cimri searches (57 segments); 6 competitor store searches; 11,982 product rows · 30.09.2026"), x("[[b:derin]]", "[[b:derin]]"), x("Kategori sayfası olmayan kesitlerde arama sırası; eşleşme ürün adında kesit anahtar sözcüğüyle; Cimri'de 17 kesitte veri bulunmamaktadır; stok sayımı süzgeç ve \"Gelince Haber Ver\" işaretine dayanır", "Search order where no category page exists; matching by segment keyword in the product name; no Cimri data for 17 segments; stock count based on the filter and the \"notify when available\" mark")],
        [x("Site politika sayfaları, sosyal profiller, Google Maps ve SERP", "Site policy pages, social profiles, Google Maps and SERP"), x("13 site ve markanın ödeme, teslimat, iade, garanti ve servis sayfaları; 7 markanın sosyal hesapları; 103 Maps sorgusu; 15 + 10 kelime SERP · 29.09.2026", "Payment, delivery, returns, warranty and service pages of 13 sites and brands; social accounts of 7 brands; 103 Maps queries; 15 + 10 keyword SERP · 29.09.2026"), x("[[b:politika]]", "[[b:politika]]"), x("Değerler 29-30.09.2026'da sitelerden okunmuştur; Instagram ve TikTok sayıları yaklaşıktır", "Values were read from the sites on 29-30.09.2026; Instagram and TikTok figures are approximate")],
        [x("Similarweb site trafiği", "Similarweb site traffic"), x("31 alan adı: marka, uzman, yapı market, pazaryeri ve fiyat karşılaştırma siteleri; aylık ziyaret, kanal kırılımı, etkileşim · Haz - Ağu 2026 · 03.10.2026", "31 domains: brand, specialist, DIY, marketplace and price comparison sites; monthly visits, channel breakdown, engagement · Jun - Aug 2026 · 03.10.2026"), x("[[b:rakip]]", "[[b:rakip]]"), x("Ziyaretler tüm ülkeleri kapsayan tahminlerdir; aylık ziyareti ~35 binin altındaki 9 sitede kanal dağılımı modellendiği için gösterilmemiştir", "Visits are estimates covering all countries; for 9 sites below ~35 thousand monthly visits the channel distribution is modelled and therefore not shown")],
        [x("Pazaryeri yorum ve soru-cevap kayıtları", "Marketplace review and Q&A records"), x("Trendyol ve Hepsiburada'da VitrA, Artema ve rakip markaların %s ürün sayfası: %s yorum (%s metinli), %s soru-cevap; VitrA resmi mağaza Trendyol paneli dahil · 03.10.2026" % (bin(_YT["urun"]), bin(_YT["yorum"]), bin(_YT["metinli"]), bin(_YT["soru"])), "%s product pages of VitrA, Artema and competitor brands on Trendyol and Hepsiburada: %s reviews (%s with text), %s Q&A; VitrA official store Trendyol panel included · 03.10.2026" % (f"{_YT['urun']:,}", f"{_YT['yorum']:,}", f"{_YT['metinli']:,}", f"{_YT['soru']:,}")), x("[[b:yorum]]", "[[b:yorum]]"), x("Duygu puandan türetilmiştir (4-5 olumlu, 1-2 olumsuz); temalar anahtar ifade kurallarıyla atanmıştır; rakip örneklemi çok satan ve en çok değerlendirilen ürünlerdir; ürün başına en fazla 50-100 yorum ve 20 soru; yorumcu adları kaydedilmemiştir", "Sentiment is derived from the rating (4-5 positive, 1-2 negative); themes are assigned with key phrase rules; the competitor sample is best-selling and most-reviewed products; at most 50-100 reviews and 20 questions per product; reviewer names were not recorded")],
        [x("TCMB EVDS", "CBRT EVDS"), x("Kart harcamaları, kartlı ödeme endeksi, tüketici eğilimi, konut, banka kredileri, hane halkı beklentileri · 2024-2026", "Card spending, card payment index, consumer tendency, housing, bank lending, household expectations · 2024-2026"), x("[[b:makro]]", "[[b:makro]]"), x("Kart harcamaları nominaldir; reel karşılaştırma için kartlı ödeme endeksinin reel serisi kullanılmıştır", "Card spending is nominal; the real series of the card payment index is used for real comparison")]])
)
