# -*- coding: utf-8 -*-
"""Bolum: Yontem ve kapsam."""
from ortak import *
HTML = """
<p class="lede">%s</p>
%s
%s
""" % (
 x("Bu raporun ilk sürümü, Inbound'un erişimindeki veri kaynaklarıyla hazırlanmıştır. VitrA'dan beklenen pazaryeri performansı, GA4 dönüşüm ve site içi arama raporları, iade ve çağrı merkezi verisi geldiğinde ilgili bölümler eklenecek ve öneriler güncellenecektir.",
   "The first version of this report was prepared with the data sources available to Inbound. When the marketplace performance, GA4 conversion and site search reports, and return and call centre data expected from VitrA arrive, the related sections will be added and the proposals updated."),
 tablo([th("Veri kaynağı", "Data source", "Kullanılan kaynak.", "Source used."),
        th("Kapsam", "Scope", "Dönem, coğrafya ve örneklem.", "Period, geography and sample."),
        th("Kullanıldığı bölüm", "Used in section", "Verinin işlendiği bölüm.", "Section where the data is processed."),
        th("Not", "Note", "Ölçüm sınırı veya yöntem notu.", "Measurement limit or method note.")],
       [[x("Google Ads Keyword Planner", "Google Ads Keyword Planner"), x("2.420 kelime · Türkiye, Türkçe · aylık hacim Eyl 2022 - Ağu 2026", "2,420 keywords · Turkey, Turkish · monthly volume Sep 2022 - Aug 2026"), x("03, 04, 05", "03, 04, 05"), x("Google Ads benzer kelimeler için birleşik hacim döndürür; aynı hacimli yazım varyantları toplamda tekrar sayılmıştır ve toplamlar üst sınır olarak okunmalıdır", "Google Ads returns combined volume for similar keywords; spelling variants with identical volume are counted repeatedly in totals, which should be read as an upper bound")],
        [x("Google Search Console", "Google Search Console"), x("sc-domain:vitra.com.tr · 1 Haz 2025 - 25 Eyl 2026 · sayfa, sorgu, cihaz, ülke", "sc-domain:vitra.com.tr · 1 Jun 2025 - 25 Sep 2026 · page, query, device, country"), x("05, 06, 07", "05, 06, 07"), x("Sayfa ve sorgu raporları ilk 25.000 satırla sınırlıdır; sayfa×gün tablosu 100.000 satır", "Page and query reports are limited to the top 25,000 rows; the page×day table to 100,000 rows")],
        [x("Google Autocomplete", "Google Autocomplete"), x("49 tohum ifade · Türkiye, Türkçe, masaüstü Chrome · %s" % veri.TARIH, "49 seed phrases · Turkey, Turkish, desktop Chrome · %s" % veri.TARIH), x("07, 14", "07, 14"), x("Öneriler tek günlük anlık görüntüdür; sıralama Google'ın sırasıdır", "Suggestions are a single-day snapshot; the order is Google's")],
        [x("YouTube arama", "YouTube search"), x("30 ifade · Türkiye · ilk sayfa · %s" % veri.TARIH, "30 phrases · Turkey · first page · %s" % veri.TARIH), x("08", "08"), x("İzlenme sayıları video yayın tarihinden itibaren kümülatiftir", "View counts are cumulative from the video's publication date")],
        [x("Ahrefs Site Explorer", "Ahrefs Site Explorer"), x("Organik rakipler ve Batch Analysis · Türkiye · 27.09.2026", "Organic competitors and Batch Analysis · Turkey · 27.09.2026"), x("12", "12"), x("Organik ve paid trafik değerleri Ahrefs tahminidir; gerçek ziyaret sayısı değildir", "Organic and paid traffic values are Ahrefs estimates, not actual visit counts")],
        [x("Google Ads keyword ideas", "Google Ads keyword ideas"), x("10 tohum grubu, 52.973 kelime · 48 ay (Eyl 2022 - Ağu 2026)", "10 seed groups, 52,973 keywords · 48 months (Sep 2022 - Aug 2026)"), x("04, 09, 10, 11", "04, 09, 10, 11"), x("Kelimeler 58 temalı sözlükle sınıflandırılmış, gürültü ifadeleri ayıklanmış, aynı aylık seriyi taşıyan yazım varyantları tek sayılmıştır; tema toplamları yaklaşık büyüklük gösterir", "Keywords were classified with a 58-theme dictionary, noise phrases removed, and spelling variants with the same monthly series counted once; theme totals indicate approximate size")],
        [x("vitra.com.tr ürün sitemap'i ve site incelemesi", "vitra.com.tr product sitemap and site review"), x("7.804 ürün adresi · hizmet, kategori ve ürün sayfaları · Banyo Asistanı · %s" % veri.TARIH, "7,804 product URLs · service, category and product pages · Bathroom Assistant · %s" % veri.TARIH), x("09, 11, 13, 14", "09, 11, 13, 14"), x("Ürün sayısı renk ve ölçü varyantlarını ayrı sayar; model sayısı renk ekleri ayıklanarak yaklaşık hesaplanmıştır", "Product counts include colour and size variants separately; model counts are approximated by removing colour suffixes")],
        [x("Rakip kategori sitemap'leri", "Competitor category sitemaps"), x("Bauhaus, IKEA, Tekzen, Evidea, Banyomarka, Kale, Banyoline · Koçtaş tarayıcı ile", "Bauhaus, IKEA, Tekzen, Evidea, Banyomarka, Kale, Banyoline · Koçtaş via browser"), x("10, 13", "10, 13"), x("Kategori varlığı gözlemidir; ürün derinliği ve satış hacmi ölçülmemiştir", "An observation of category presence; product depth and sales volume were not measured")],
        [x("Trendyol arama sonuçları", "Trendyol search results"), x("13 tema, ilk 40-45 ürün · %s" % veri.TARIH, "13 themes, top 40-45 products · %s" % veri.TARIH), x("04, 09, 10", "04, 09, 10"), x("Değerlendirme sayısı satış hacmine yaklaşık gösterge olarak kullanılmıştır; sonuç sırası kişiselleştirmeye bağlı olarak değişebilir", "Review count is used as an approximate indicator of sales volume; result order may vary with personalisation")],
        [x("Rakip ve benzer oyuncuların siteleri", "Websites of competitors and comparable players"), x("Koçtaş, IKEA, Hepsiburada, Kale, Banyomarka, BAUHAUS, Home Depot, Kohler, Villeroy & Boch, Duravit, hansgrohe, GROHE, Geberit, Victorian Plumbing", "Koçtaş, IKEA, Hepsiburada, Kale, Banyomarka, BAUHAUS, Home Depot, Kohler, Villeroy & Boch, Duravit, hansgrohe, GROHE, Geberit, Victorian Plumbing"), x("11, 13", "11, 13"), x("Hizmet ve kampanya koşulları erişim tarihindeki haliyle aktarılmıştır", "Service and campaign terms are reported as of the access date")],
        [x("Inbound sezonsallık ve rakip ürün analizi", "Inbound seasonality and competitor product analysis"), x("Haziran 2026 · Ahrefs content gap, 4.202 kelime, 7 rakip", "June 2026 · Ahrefs content gap, 4,202 keywords, 7 competitors"), x("10", "10"), x("Dört ürün kümesi güncel veriyle yeniden ölçülmüştür", "The four product clusters have been re-measured with current data")],
        [x("TCMB EVDS", "CBRT EVDS"), x("Kart harcamaları, kartlı ödeme endeksi, tüketici eğilimi, konut, banka kredileri, hane halkı beklentileri · 2024-2026", "Card spending, card payment index, consumer tendency, housing, bank lending, household expectations · 2024-2026"), x("02", "02"), x("Kart harcamaları nominaldir; reel karşılaştırma için kartlı ödeme endeksinin reel serisi kullanılmıştır", "Card spending is nominal; the real series of the card payment index is used for real comparison")]]),
 box("BEKLENEN VERİ", "DATA EXPECTED", marks([("at", "VitrA panelinden Trendyol ve Hepsiburada ürün-kategori bazında görüntülenme, sepete ekleme, satın alma, iade ve müşteri soruları (son 12 ay)", "From the VitrA panel: Trendyol and Hepsiburada views, add-to-basket, purchases, returns and customer questions by product category (last 12 months)"),
                                             ("at", "GA4: ürün performansı, dönüşüm hunisi, site içi arama, kanal ve cihaz kırılımı, lead olayları (ayrı talep dokümanı iletilmiştir)", "GA4: product performance, conversion funnel, site search, channel and device breakdown, lead events (a separate request document has been sent)"),
                                             ("at", "Ürün listesi, iade nedenleri, çağrı merkezi konu başlıkları, kargo ve teslimat süreç bilgisi", "Product list, return reasons, call centre topics, shipping and delivery process information"),
                                             ("at", "Yapay zeka görünürlüğü: Inbound görünürlük aracındaki VitrA prompt seti (montaj ve e-ticaret prompt'ları eklenmiş, koşu birikince rapora alınacak)", "AI visibility: the VitrA prompt set in the Inbound visibility tool (installation and e-commerce prompts added, to be included once runs accumulate)")])),
)
