# -*- coding: utf-8 -*-
"""Kaynak dokumu · F: kok adres aciklamalari (kaynakca kodundan turetilen bolumlerle) ve yontem maddeleri."""
from kaynak_ortak import *
from kaynak_veri_a import D28, D29, D30

def doldur():
    ekle("https://www.trendyol.com", "Trendyol: arama sonuçları, kategori ağacı, mağaza sayfaları ve çok satan listeleri (SSG, BM ve fiyat incelemesi)",
         "13 tema arama sonucu (Apify, ilk 40-45 ürün), banyo kategori ağacı ve sonuç sayıları, VitrA mağazası (833 ürün) ve 180 mağaza sayfası, 14 kategori × 36 ürün çok satan listeleri; VitrA'nın klozet listeleme payı %11,8, lavabo %3,2, banyo dolabı %0,4; yardım sayfaları 30.09.2026'da Chrome ile doğrulandı; doğrudan erişimde 403",
         yontem=["tarayıcı", "API (Apify)", "tarayıcı (Chrome, kullanıcı oturumu)"], tarih=[D29, D30], kod=["D15", "D21", "D26"])
    ekle("https://www.hepsiburada.com", "Hepsiburada: banyo kategori listeleri, marka filtreleri, satıcı ve hizmet ürünleri (ilk sayfa, 36 ürün) ve çok satan listeleri",
         "Kategori ağacı ve marka filtreli toplamlar, 14 kategori × 36 ürün çok satan listeleri, 29 VitrA ve Artema SKU'sunun buybox ve satıcı listesi, Mr Usta montaj hizmet ürünleri (klozet montajı 2.730 TL); bot korumalı sayfalar tarayıcıda okundu",
         yontem=["tarayıcı", "tarayıcı (Playwright)", "API (Apify)"], tarih=[D29, D30], kod=["D22", "D26", "D28"])
    ekle("https://www.koctas.com.tr", "Koçtaş: banyo kategori yapısı, VitrA ve Artema ürün fiyatları, taksit, nakliye ve montaj koşulları",
         "Kategori sitemap'i 403 döndüğü için kategori yapısı tarayıcıyla okundu; 16 VitrA ve Artema ürün sayfasının liste ve sepet fiyatı; Koçtaş, VitrA kelimelerinin %63'ünde sıralanıyor ve organik trafiği VitrA'nın yaklaşık 8x'i",
         yontem=["tarayıcı", "API (Apify)"], tarih=[D29], kod=["D26"], bolum=["yeni", "fiyat", "politika"], kodbolum=False)

import kaynakca
def yontem_maddeleri(n_satir, n_alan):
    return [
        "Kapsam: Bu döküm, rapor HTML'indeki %d kaynakça girdisinin tüm adreslerini, rapordaki bağlantıları, derin araştırma turlarında (veri/ham/derin) okunan sayfaları ve API kaynaklarını içerir; %d satır, %d alan adı. Toplu okunan sayfalar kalıp adres ve adet olarak tek satırdadır." % (len(kaynakca.K), n_satir, n_alan),
        "Erişim tarihleri: 27.09.2026 (Ahrefs organik rakipler ve Batch Analysis), 28.09.2026 (Ahrefs Site Explorer ve Keywords Explorer, Search Console, Keyword Planner, autocomplete, EVDS), 29.09.2026 (derin araştırma turu: SERP, YouTube, Trendyol, Hepsiburada, Şikayetvar, kanal politikaları, Google Shopping, pazaryeri fiyatı, sitemap'ler), 30.09.2026 (Chrome ile Akakçe, Cimri, yardım sayfaları ve Hepsiburada çok satanlar sayfa 2-3), 02.10.2026 (Wikidata, Wikipedia, llms.txt, site haritaları, rehber içerik), 03.10.2026 (Similarweb, SEOmonitor, pazaryeri yorum ve soru çekimleri, rakip Şikayetvar aylık serileri), 04.10.2026 (Google arama sonuçları üç gözlem, ek Keyword Planner kelimeleri, site içi arama, sepet ekranları, destek SSS envanteri).",
        "DataForSEO API: Google Ads uç noktaları (search_volume ve keywords_for_keywords), SERP (organic live advanced ve regular, mobil ve masaüstü, Türkiye 2792, Türkçe), autocomplete, YouTube arama ve yorum, Google Maps, merchant (Google Shopping ürün ve satıcı). Canlı uç noktalar istek başına tek görev aldığından her kelime ayrı istekle çekildi; 04.10.2026 SERP çekiminde her kelime üç kez gözlenmiş; aynı aramada farklı ve 10'dan kısa sonuç listeleri döndüğünden rakip sıraları tam gözlemlerin medyanından, SEOmonitor'de takip edilen 158 kelimede ise tüm sıralar SEOmonitor 03.10.2026 mobil verisinden alınmıştır.",
        "Ahrefs MCP: Site Explorer (top pages, organic keywords, organik rakipler, Batch Analysis), Keywords Explorer (overview ve aylık hacim serisi), SERP overview; ülke Türkiye, tüm trafik değerleri Ahrefs tahminidir. Top pages sorguları satır sınırına ulaştığından pazaryeri değerleri alt sınırdır.",
        "Google Search Console API: sc-domain:vitra.com.tr, OAuth kullanıcı hesabı (salt okunur kapsam); sayfa ve sorgu raporları ilk 25.000 satırla, sayfa × gün tablosu 100.000 satırla sınırlıdır.",
        "TCMB EVDS API: evds3.tcmb.gov.tr/igmevdsms-dis, anahtar HTTP başlığıyla gönderildi; 10 veri grubunun seri listeleri ve seçilen seriler okundu.",
        "curl: tarayıcı User-Agent'ı, istekler arası 2-6 sn; vitra.com.tr ürün sitemap'i ve sitemap dizini, rakip kategori sitemap'leri, marka ve politika sayfaları, YouTube ve Pinterest profil sayfaları, Şikayetvar marka sayfaları ve şikayet detayları.",
        "Apify: rag-web-browser (Koçtaş, Bauhaus ve bazı Hepsiburada sayfaları; yaklaşık 16 çağrı) ve automation-lab/trendyol-scraper (13 tema, 14 kategori × 36 ürün; yaklaşık 1,50 USD). Şikayetvar için hazır actor'lar bulundu ancak marka sayfaları curl ile okunabildiğinden çalıştırılmadı.",
        "Tarayıcı: Trendyol ve Hepsiburada kategori, marka, mağaza ve arama sayfaları (giriş, form ve sepet işlemi yapılmadı, yavaş tempo); Hepsiburada çok satanlar Playwright ile sayfa durumundan okundu. 30.09.2026'da kullanıcının Chrome'unda tek sekme, open_url ve execute_javascript ile Akakçe, Cimri ve yardım sayfaları okundu; giriş, form ve doğrulama çözümü yapılmadı.",
        "Akakçe: doğrudan erişim yaklaşık 15 istekten sonra doğrulama sayfası verdi (29.09.2026); 30.09.2026'da Chrome ile 29 SKU'nun 24'ü eşleşti ve 12 kategori sayfası okundu. Aramada Akakçe ürün numarasının kısa ürün kodlarını içerebildiği görüldü; eşleşme ürün adresi slug'ından yapıldı.",
        "Cimri: arama sayfası doğrulama katmanı nedeniyle açılamadı (curl, Apify ve Chrome); kategori, marka ve ürün sayfaları okundu, 19 SKU için 110 teklif alındı. Sayfa açma sırasında iki kez 429 ve bir kez 'Just a moment' yanıtı alındığından okumaya son verildi; 10 SKU eşleşmedi. Akakçe ve Cimri sonuçlarının bir bölümü Google SERP özetlerinden (DataForSEO) okundu.",
        "Kanal politikaları: Koçtaş, Trendyol, n11 ve Amazon TR yardım sayfaları curl ile 403 döndü ya da Apify'da boş geldi; ilk turda ilgili hücreler arama sonucu özetinden alındı, 30.09.2026'da Chrome ile 31 hücre kontrol edildi (14 doğrulandı, 10 kısmen, 4 yeni bilgi, 2 bulunamadı, 1 düzeltildi). Bu dökümde arama sonucu özetinden alınan sayfalar 'Yöntem' sütununda işaretlidir.",
        "Alınamayanlar: Hepsiburada yardım merkezi giriş istediği için açılmadı (yalnızca mobilya ve büyük ürün sayfası ile /teslimat okundu); n11 /yardim 404 döndü; Geberit garanti adresi 404 döndü (garanti PDF'i Medya Merkezi'nden okundu); Duravit TR curl 403 (Chrome ile okundu); Creavit yedek parça listesi katalog sayfasında bulunamadı; Artema garanti sayfasının içeriği statik HTML'de görünmedi; Koçtaş yardım sayfaları Apify'da boş geldi (Chrome ile okundu).",
        "Alınamayanlar (devam): Instagram ve TikTok girişe kapalıdır, takipçi sayıları Google SERP snippet'inden alınmıştır (yaklaşık, bir bölümü alınamadı); Şikayetvar pazaryeri, kampanya ve iade konu sayfaları 404 döndü ve marka yanıt metni görünmedi; grohe.com Ahrefs API'sinde yanıt vermedi (Grohe Türkiye verisi alınamadı); serel.com.tr, ecebanyo.com, bien.com.tr ve grohe.com.tr Ahrefs'te sıfıra yakın trafik gösterdiğinden gerçek alan adları (eca.com.tr, bienbanyo.com.tr, serelseramik.com.tr) ayrıca sorgulandı.",
        "Alınamayanlar (devam): Koçtaş kategori sitemap'i 403 döndü (kategori yapısı tarayıcıyla okundu); Creavit sitemap dosyası boş döndü; 15 kategori kelimesinde mobil ve masaüstü SERP'te Shopping veya ürün bloğu görünmedi (5 genel ürün kontrol sorgusunda da 0); Hepsiburada çok satanlar 29.09.2026'da Playwright ile okundu; Hepsiburada yorum ve soru sayfaları 03.10.2026'da Apify aktörüyle alındı.",
        "Dış bağlantı kontrolü (29.09.2026, o tarihteki rapor sürümü): rapordaki 118 dış bağlantının 99'u 200 döndü, 17'si bot koruması nedeniyle 403 verdi (Trendyol, Hepsiburada, Koçtaş, Bauhaus, Duravit, Home Depot, Villeroy & Boch); ecebanyo.com curl ile bağlanmadı.",
        "Bu dökümün dışında kalanlar: VitrA panelinden GA4 (dönüşüm hunisi, site içi arama terimleri, kanal performansı), iade ve çağrı merkezi verisi beklenmektedir; bu veriler henüz alınmamıştır. Yapay zeka yanıt takibi (D39) ve pazaryeri panel verisi (D31, D36) dökümde yer almaktadır.",
        "Sayım kuralı: 'Sayfa/sorgu sayısı' sütunu 01 Kaynaklar'daki adet değerlerinin alan adı bazında toplamıdır; Ahrefs ve DataForSEO kayıt sayıları (top pages satırları, sorgu sonuçları) toplama katılmaz, ilgili satırın 'Hangi bilgiler alındı' alanında yazılıdır.",
        "Eşleme notu: Kaynakça kodunun rapordaki atıf bölümleri yalnızca genel kaynak satırlarında (API, taban adres, sitemap, repo) birleştirilmiştir; tek tek sayfa satırlarında yalnızca o sayfanın veri sağladığı bölüm yazılıdır.",
    ]
